feat: add docxf icon mapping and fix document icon colors
owncloud/web pull request #10037
Opened 2023-11-22 13:33 UTC by kulmann

## Description
Followup for https://github.com/owncloud/web/pull/9911 - adding the docxf icon mapping and adjusting colors.

## Related Issue
- Fixes https://github.com/owncloud/web/issues/9847 again

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-11-22 17:06 UTC, tbsbdr commented
I suggest to stick to the current colors but with the following changes:
- Forms (new color as already implemented by you)
- MD (dedicated as already implemented by you)
- All other file-extension colors should not change - sorry, this was a misunderstanding. I see no reason to change them. Do you argee?

2023-11-22 17:07 UTC, tbsbdr requested changes
I suggest to stick to the current colors but with the following changes:

- Forms (new color as already implemented by you)
- MD (dedicated as already implemented by you)
- All other file-extension colors should not change - sorry, this was a misunderstanding. I see no reason to change them. Do you argee?

2023-11-22 21:24 UTC, kulmann commented
> I suggest to stick to the current colors but with the following changes:
> 
> * Forms (new color as already implemented by you)
> * MD (dedicated as already implemented by you)
> * All other file-extension colors should not change - sorry, this was a misunderstanding. I see no reason to change them. Do you argee?

Thanks for checking. Updated the PR 👍

2023-11-23 08:59 UTC, tbsbdr approved these changes
lgtm

2023-11-24 07:20 UTC, merged