Bugfix: Gridview whitespace autosize
owncloud/web pull request #10118
Opened 2023-12-05 10:23 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-12-05 13:34 UTC, kulmann approved these changes
Yeah, awesome!!! :heart:

2023-12-05 13:34 UTC, JanAckermann approved these changes

2023-12-05 15:07 UTC, tbsbdr commented
love it 🔥
 I found 1 thing:
if you have only few items, these are streched over the whole width, ignoring the slider setting 😬 

![screenshot_002107](https://github.com/owncloud/web/assets/26610733/3361ac22-ac42-4a35-b271-e641df2e2fea)
![screenshot_002108](https://github.com/owncloud/web/assets/26610733/e644f2c0-2660-4c6e-ad65-cb3517f08852)

2023-12-05 16:13 UTC, tbsbdr submitted a review, later dismissed
please see https://github.com/owncloud/web/pull/10118#issuecomment-1840980892

2023-12-11 20:47 UTC, kulmann submitted a review, later dismissed
Having an empty folder and inserting items one by one feels very weird, since the tile size is shrinking with every new item. I would expect the tile size to be stable. Having only one non-filled line also looks wrong, since the gap sizes are quite huge. I'll attach a series of screenshots to visualize the issue.

I'd expect the tile size like in the last screenshots for all other screenshots as well. Maybe a solution with aria-hidden dummy items, like @JanAckermann proposed in a call earlier today, is working better. Could you give that a try?

<img width="1579" alt="Screenshot 2023-12-11 at 21 43 34" src="https://github.com/owncloud/web/assets/3532843/8192d324-b100-4a0a-b5b4-63a8888e5b5e">
<img width="1579" alt="Screenshot 2023-12-11 at 21 43 49" src="https://github.com/owncloud/web/assets/3532843/81c69bf0-f4ad-4660-85cb-8d96919a458b">
<img width="1579" alt="Screenshot 2023-12-11 at 21 43 58" src="https://github.com/owncloud/web/assets/3532843/832d7ab6-6059-4af2-a41c-8686db27b598">
<img width="1579" alt="Screenshot 2023-12-11 at 21 44 07" src="https://github.com/owncloud/web/assets/3532843/17905103-a0af-4eac-9f19-0147821940f6">
<img width="1579" alt="Screenshot 2023-12-11 at 21 44 17" src="https://github.com/owncloud/web/assets/3532843/d1f002d9-798a-47d5-af17-97543ffe91be">
<img width="1579" alt="Screenshot 2023-12-11 at 21 44 26" src="https://github.com/owncloud/web/assets/3532843/ed728331-cdc1-4217-adce-6dc893a59657">
<img width="1579" alt="Screenshot 2023-12-11 at 21 44 35" src="https://github.com/owncloud/web/assets/3532843/bbf750f7-95f4-48fe-acc3-6d060446b283">
<img width="1579" alt="Screenshot 2023-12-11 at 21 44 43" src="https://github.com/owncloud/web/assets/3532843/0299bef7-f7a7-40bd-bf6a-746a6b34afc9">

2023-12-11 20:47 UTC, kulmann commented on packages/web-pkg/src/components/ViewOptions.vue
> +      const newSize2 = `${((unref(viewSizeQuery) as any) * 1) / 10}fr`
dev leftovers?

2023-12-12 07:46 UTC, lookacat commented
@kulmann yes will try to do it that way

2023-12-16 11:43 UTC, JanAckermann commented on packages/web-app-files/src/components/FilesList/ResourceTiles.vue
> +    const ghostTileCount = computed(() => {
```suggestion
    const ghostTilesCount = computed(() => {
```

2023-12-16 11:44 UTC, JanAckermann commented on packages/web-app-files/src/components/FilesList/ResourceTiles.vue
> +        <li class="ghost-tile" v-for="index in ghostTileCount" :key="index">
please hide from a11y readers

2023-12-16 11:54 UTC, JanAckermann commented on packages/web-app-files/src/components/FilesList/ResourceTiles.vue
> +      var style = getComputedStyle(document.documentElement)
```suggestion
      const style = getComputedStyle(document.documentElement)
```

2023-12-16 12:18 UTC, JanAckermann commented
@lookacat I cleaned up the code a little, I like the way where this is going and it looks already fine, but unfortantly the pr renders too much ghost tiles

![image](https://github.com/owncloud/web/assets/26169327/99002be1-03d4-4813-b989-427c8c645278)

2023-12-16 12:18 UTC, JanAckermann requested changes
Check why too many ghost tiles are rendered

2023-12-16 12:31 UTC, JanAckermann commented on packages/web-app-files/src/components/FilesList/ResourceTiles.vue
> +      return Math.max(0, unref(maxTileCount) - props.data.length)
Solves your negative count problem

2023-12-18 09:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/web?pullRequest=10118) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/web?pullRequest=10118) before we can accept your contribution.<br/>**6** out of **7** committers have signed the CLA.<br/><br/>:white_check_mark: phil-davis<br/>:white_check_mark: SwikritiT<br/>:white_check_mark: kulmann<br/>:white_check_mark: JammingBen<br/>:white_check_mark: lookacat<br/>:white_check_mark: JanAckermann<br/>:x: ownclouders<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/web?pullRequest=10118) it.</sub>

2023-12-18 13:29 UTC, JanAckermann commented on packages/web-pkg/src/composables/viewMode/useTileSize.ts
> +    // FIXME: css root vars are undefined o_O
maybe nextTick thingy ?

2023-12-19 12:44 UTC, kulmann commented on packages/web-app-files/tests/unit/components/FilesList/ResourceTiles.spec.ts
> +    tileSizePixels: 10
```suggestion
    tileSizePixels: 100
```

Could you please increase the tile size to 100px? Snapshot looks super ugly otherwise.

2023-12-19 19:01 UTC, kulmann approved these changes

2023-12-20 08:53 UTC, JanAckermann requested changes

2023-12-20 08:53 UTC, JanAckermann commented on packages/web-app-files/src/components/FilesList/ResourceTiles.vue
> +      if (remainder) {
I'd flip that and return 0 early

2023-12-20 09:01 UTC, JammingBen approved these changes
LGTM overall. We should probably resolve my first remark, but IMO not a blocker since it works for now.

2023-12-20 11:02 UTC, JanAckermann approved these changes

2023-12-20 13:52 UTC, merged