refactor: remove opinionated components from ODS
owncloud/web pull request #10293
Opened 2024-01-04 16:45 UTC by JammingBen

## Description
Removes the following opinionated components from the ODS and moves them to `web-pkg` instead:

- `OcResource` (now `ResourceListItem`)
- `OcTile` (now `ResourceTile`)
- `OcResourceIcon` (now `ResourceIcon`)
- `OcGhostElement` (now `DragGhostElement`)

Those components hold logic about resources, which is something that is not supposed to live in the ODS. The ODS should only contain design- and layout-specific components.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

2024-01-05 19:54 UTC, kulmann requested changes

2024-01-05 19:54 UTC, kulmann commented on packages/design-system/changelog/unreleased/change-remove-opinionated-components
> +We've removed the following opinionated components from the ODS and moved them to `web-pkg` instead:
Please add a breaking change for developers notice, like we usually do.

2024-01-05 19:54 UTC, kulmann commented on packages/design-system/changelog/unreleased/change-remove-opinionated-components
> +- `OcResource` (now `ResourceListItem`)
There are three more components about resources:
- `OcResourceLink`
- `OcResourceName`
- `OcResourceSize`

Could you please move and rename those as well?

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/components/DragGhostElement.vue
move into subfolder `FilesList`?

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/components/ResourceListItem.vue
Move into subfolder `FilesList`?

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/components/ResourceIcon.vue
Move into a new subfolder `Resource`?

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/components/ResourceTile.vue
Move into subfolder `FilesList`? The `ResourceTiles.vue` component still lives in the files app, but it would make sense to move it here into the `FilesList` folder anyway... if you think the scope of this PR can handle that move as well, then go for it 😇

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/helpers/resource/icon.ts
> +export type OcResourceIconMapping = Record<'mimeType' | 'extension', Record<string, IconType>>
Small nitpick: If we keep the provide/inject of icon mappings, these two lines should also not contain `oc`-prefixes anymore.

2024-01-05 19:54 UTC, kulmann commented on packages/web-pkg/src/components/ResourceIcon.vue
Since this component now moved from the (potentially standalone) design system into `web-pkg` we don't need to provide/inject the icon mappings anymore. Instead the component could query that from the runtime / a composable / whatever. But maybe something for a followup... could you create an issue? Or just add a todo in your PR description, so that I can create the issue before we merge and after we agreed that we want to change it. 😅

2024-01-08 09:35 UTC, JammingBen commented on packages/web-pkg/src/components/ResourceTile.vue
Moving `ResourceTiles.vue` is a little more work to do, I created an issue for this: https://github.com/owncloud/web/issues/10304

2024-01-08 10:04 UTC, dschmidt commented
`DragGhostElement` - I think this should *somehow* also contain `Resource` in the name

2024-01-08 12:28 UTC, JammingBen commented on packages/web-pkg/src/components/ResourceIcon.vue
Good catch, I've created https://github.com/owncloud/web/issues/10305 for this.

2024-01-08 12:31 UTC, JammingBen commented
> `DragGhostElement` - I think this should _somehow_ also contain `Resource` in the name

I decided for `ResourceGhostElement`, IMO we don't necessarily need the information "drag" here.

2024-01-08 13:25 UTC, kulmann requested changes
Nice! Now my last request for change: remove `web-client` from the dependency list please 😅

2024-01-08 15:25 UTC, kulmann approved these changes
Hooray, thank you 🥳

2024-01-08 15:26 UTC, merged