[tests-only][full-ci] added e2e test to create a new file with existing name
owncloud/web pull request #10588
Opened 2024-03-12 11:28 UTC by PrajwolAmatya

## Description

## Related Issue

- https://github.com/owncloud/web/issues/10259

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

2024-03-18 08:22 UTC, saw-jan commented on tests/acceptance/features/webUIFilesList/fileList.feature
> -  Scenario: Resources are listed and files list displays quicklink quick action
Please, add comments if these scenarios have been covered or not. And also provide the link for scenarios where they are covered

2024-03-18 09:55 UTC, ScharfViktor commented on tests/acceptance/features/webUIFilesList/sort.feature
> -    Then these resources should be listed in the folder "test_sort" on the webUI
I think it would be nice to have a couple of tests for that

2024-03-21 06:03 UTC, saw-jan requested changes

2024-03-21 06:03 UTC, saw-jan commented on tests/e2e/cucumber/features/smoke/sort.feature
> +  So that I can make the file/folder list more clear
According to https://github.com/owncloud/web/issues/10259#issuecomment-2009826676, we wont be adding sorting e2e tests

2024-03-21 06:04 UTC, saw-jan commented on tests/acceptance/features/webUIFilesList/sort.feature
> -    Then these resources should be listed in the folder "test_sort" on the webUI
According to https://github.com/owncloud/web/issues/10259#issuecomment-2009826676, we wont be adding sorting e2e tests

2024-03-21 06:10 UTC, saw-jan approved these changes

2024-03-21 07:28 UTC, ScharfViktor approved these changes

2024-03-21 08:17 UTC, merged