Fix 10814: Make OcModal vertically scrollable
owncloud/web pull request #10816
Opened 2024-04-23 06:38 UTC by pascalwengerter

## Related Issue
- Fixes #10814

2024-04-23 09:47 UTC, JammingBen requested changes
Modals now always show a scrollbar for me 😅 

<img width="473" alt="image" src="https://github.com/owncloud/web/assets/50302941/9ef51c30-e747-48d4-bc89-11f5d109b011">

Also please don't forget to target this to `stable-8.0`.

2024-04-23 10:12 UTC, kulmann commented on packages/design-system/src/components/OcModal/OcModal.vue
wouldn't it make more sense to make only the modal body scrollable?

2024-04-23 14:40 UTC, pascalwengerter commented on packages/design-system/src/components/OcModal/OcModal.vue
"It depends" 😉 assuming the title never exceeds one line I naively compute the "allowed" max height of the body. Or should I go for a more sophisticated solution?

2024-04-24 14:39 UTC, JammingBen reviewed
Still having some issues, the scrollbar is now showing for smaller modals as well:

<img width="469" alt="image" src="https://github.com/owncloud/web/assets/50302941/74c7e6c2-5f9c-4877-9925-e1d0b932bf4b">

2024-05-15 12:38 UTC, kulmann approved these changes
👍

2024-05-15 13:26 UTC, JammingBen approved these changes

2024-05-15 13:26 UTC, merged