feat: add extension point for application menu items
owncloud/web pull request #11258
Opened 2024-07-23 09:34 UTC by JammingBen

## Description
Adds an extension point for adding items in the top left application switcher menu.

`AppMenuItemExtension`'s can either link to an internal page (via `path`), an external page (via `url`) or have a button handler (via `handler`). Please refer to the docs for more information.

This deprecates the `applicationMenu` property of the appinfo object.

Also removes ancient menu logic from oC10 times, such as the user menu.

## Related Issue

- works towards https://github.com/owncloud/web/issues/7260

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

2024-07-23 12:53 UTC, JammingBen commented
This currently only supports remix icons. Do we need support for icon urls?

2024-07-23 12:58 UTC, kulmann commented on changelog/unreleased/enhancement-app-menu-item-extension-point
> +DEPRECATION NOTICE: This deprecates the `applicationMenu` property of the appinfo object.
I wanted to ask you to also add the deprecation to https://github.com/owncloud/web/issues/7338 but you already did that :D

2024-07-24 04:24 UTC, kulmann reviewed
When I do a production build there is a vue-router error when navigating into an embedded `wikipedia.com`. doesn't happen with vite 🤔  (tested together with a production build of https://github.com/owncloud/web-extensions/pull/13 in my ocis apps folder)

2024-07-24 06:27 UTC, JammingBen commented
> When I do a production build there is a vue-router error when navigating into an embedded `wikipedia.com`. doesn't happen with vite 🤔 (tested together with a production build of [owncloud/web-extensions#13](https://github.com/owncloud/web-extensions/pull/13) in my ocis apps folder)

Huh, there was an issue with the way I've added the router component. I don't get why this didn't pop up in dev mode... anyway, now it should work (although you need to edit your server's CSP rules to allow an external site being embedded via an iFrame).

2024-07-24 07:45 UTC, kulmann requested changes
Hmmm... did I overlook something or is an `isVisible` callback missing? There are apps, e.g. the `admin-settings` app, which are only visible to certain users.

2024-07-24 07:45 UTC, kulmann commented on docs/extension-system/extension-types/app-menu-items.md
> +A `path` will result in a `<a>` element that links to an internal page. That means the given path needs to exist within the application.
```suggestion
A `path` will result in an `<a>` element that links to an internal page via the vue router. That means the given path needs to exist within the application.
```

2024-07-24 07:45 UTC, kulmann commented on docs/extension-system/extension-types/app-menu-items.md
> +A `url` will result in a `<a>` element that links to an external page. External pages always open in a new tab or window.
```suggestion
A `url` will result in an `<a>` element that links to an external page. External pages always open in a new tab or window.
```

2024-07-24 07:45 UTC, kulmann commented on docs/extension-system/extension-types/app-menu-items.md
> +Since these properties are optional, the priority order is `handler` > `path` > `url`. At least one of them has to be provided when registering an extension.
```suggestion
At least one of these properties has to be provided when registering an extension. If you define more than one, the priority order is `handler` > `path` > `url`. 
```

2024-07-24 08:01 UTC, JammingBen commented
> Hmmm... did I overlook something or is an isVisible callback missing? There are apps, e.g. the admin-settings app, which are only visible to certain users.

Do we need it though? Since it will be the app's duty to register menu items, it can just not register an item if the user doesn't have permissions to see it.

2024-07-24 08:03 UTC, kulmann commented
> > Hmmm... did I overlook something or is an isVisible callback missing? There are apps, e.g. the admin-settings app, which are only visible to certain users.
> 
> Do we need it though? Since it will be the app's duty to register menu items, it can just not register an item if the user doesn't have permissions to see it.

Hm true...

2024-07-24 09:07 UTC, kulmann approved these changes

2024-07-24 09:57 UTC, merged