[WIP] [tests-only][full-ci]move login step after all API query is done
owncloud/web pull request #11592
Opened 2024-09-17 10:54 UTC by S-Panta

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests
- [ ] Documentation
- [ ] Maintenance (e.g. dependency updates or tooling)

## Open tasks:

- [ ] ...

2024-09-23 07:52 UTC, ScharfViktor reviewed
other is fine 👍

2024-09-23 07:52 UTC, ScharfViktor commented on tests/e2e/cucumber/features/file-action/rename.feature
> -    And "Alice" opens the "files" app
could you move it to line 42 to get 
```
And "Alice" logs in
And "Alice" navigates to the shared with others page
And "Alice" opens folder "folder"
```

2024-09-23 11:10 UTC, saw-jan requested changes

2024-09-23 11:10 UTC, saw-jan commented on tests/e2e/cucumber/steps/ui/public.ts
> +      password = '%public%' === password ? securePassword : password
this is more preferable
```suggestion
      password = password === '%public%' ? securePassword : password
```

2024-09-24 04:00 UTC, amrita-shrestha commented on tests/e2e/cucumber/features/file-action/rename.feature
> +
```suggestion
```

2024-09-24 05:02 UTC, saw-jan approved these changes
LGTM

2024-09-24 07:38 UTC, ScharfViktor approved these changes
👍

2024-09-24 07:39 UTC, merged