fix ocis-1043
owncloud/web pull request #4444
Opened 2020-12-09 17:03 UTC by fschade

fixes https://github.com/owncloud/ocis/issues/1043

2020-12-09 17:23 UTC, LukasHirt approved these changes
I guess cloning the whole `items` instead of one by one wouldn't make a real difference here with performance, right? Since I guess there won't ever be hundreds of nav items :shrug:

2020-12-10 17:58 UTC, fschade commented
> I guess cloning the whole `items` instead of one by one wouldn't make a real difference here with performance, right? Since I guess there won't ever be hundreds of nav items 🤷

yes its more costy to do it one by one (but not much it's a low level api). The problem if we do

```
const o = [1, 2, 3]
const n = [...o]
n[0] = 99
```

the result would be [99,2,3]

but if we do 
```
const o = [{foo: 1}]
const n = [...o]
n[0].foo = 99
```

we still mutate the original object in o

objects in arrays get refferenced and not deep copied.

2020-12-10 20:41 UTC, kulmann requested changes

2020-12-10 20:41 UTC, kulmann commented on src/Phoenix.vue
> +        <oc-spinner size="xxxlarge" :aria-label="$gettext('Loading')" class="uk-position-center" />
From my personal feeling the spinner is too big. I would choose `xlarge` size and border sizes in the css class `10px`.

2020-12-10 20:41 UTC, kulmann commented on src/store/user.js
> +      await init(this._vm.$client, token)
The `await` here should not be needed, as it's the last statement within the function.

2020-12-10 20:41 UTC, kulmann commented on src/store/navigation.js
> +      item => item.route.path === navItem.route.path
Thanks for spotting this ❤️

2020-12-11 12:21 UTC, kulmann approved these changes
👍

2020-12-11 12:22 UTC, merged