[Tests-Only] Add webui tests for various file operations by public in public share
owncloud/web pull request #4560
Opened 2020-12-28 03:12 UTC by HariBhandari07

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2020-12-28 11:09 UTC, dpakach requested changes

2020-12-28 11:09 UTC, dpakach commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +    },
It's better idea to move assertions away from page objects as we discussed a while back

2020-12-28 11:19 UTC, jasson99 requested changes

2020-12-28 11:19 UTC, jasson99 commented on tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
> +    And as "user1" folder "/simple-folder/simple-folder" should not exist
```suggestion
    And as "user1" folder "/simple-folder/simple-empty-folder" should not exist
```

2020-12-28 11:19 UTC, jasson99 commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +              : path + ' is expected not to be selected but is selected'
I think this always returns the second message. Is status expected to be equal with the result ever?

2020-12-29 02:54 UTC, HariBhandari07 commented on tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
> +        .useCss()
This is required to check the `role dropdown of public share` changes when a user selects various roles. This asserts that PR https://github.com/owncloud/web/pull/4504   is working as intended.

2020-12-29 10:08 UTC, dpakach reviewed
lgtm 👍🏽

2020-12-29 10:11 UTC, jasson99 reviewed
:+1:

2020-12-29 10:24 UTC, phil-davis approved these changes

2020-12-29 10:24 UTC, merged