[POC][Tests-Only] Add first visual regression tests
owncloud/web pull request #4574
Opened 2020-12-31 07:41 UTC by dpakach

## Description

Add first visual regression test for the header of files page.

## Related Issue

- Related https://github.com/owncloud/web/issues/4404

## Motivation and Context

Visual regression testing is a very useful to reduce visual regressions. our e2e tests use dom elements to run the tests but they do not check the UI visually. So even if the colour or tests of the elements are changed the tests will not catch those (more in https://github.com/owncloud/web/issues/4404#issuecomment-736506646). visual regression testing will help reduce these kinds of bugs

## How Has This Been Tested?

:robot:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2020-12-31 10:51 UTC, Talank commented on tests/acceptance/stepDefinitions/visualContext.js
> +  )
cool :1st_place_medal:

2021-01-05 07:35 UTC, ownclouders commented
</p></details>

</p></details>

2021-01-05 07:38 UTC, ownclouders commented
</p></details>

</p></details>

2021-01-05 09:32 UTC, ownclouders commented
</p></details>

2021-01-05 09:34 UTC, ownclouders commented
</p></details>

2021-01-05 10:40 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISVisual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12694/

<p>


![topBar.png](https://minio.owncloud.com/phoenix/screenshots/12694/topBar.png)

2021-01-05 10:42 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Visual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12694/

<p>


![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/12694/sideBar.png)

2021-01-05 11:13 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISVisual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12696/

<p>


![topBar.png](https://minio.owncloud.com/phoenix/screenshots/12696/ocis/topBar.png)
![topBar.png](https://minio.owncloud.com/phoenix/screenshots/12696/ocis/topBar.png)

</p></details>

2021-01-05 11:35 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Visual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12697/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/diff/12697/oc10/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/latest/12697/oc10/sideBar.png)

</p></details>

2021-01-05 11:38 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISVisual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12697/

<p>


Diff Image: </br>
![topBar.png](https://minio.owncloud.com/phoenix/screenshots/diff/12697/ocis/topBar.png)
Actual Image: </br>
![topBar.png](https://minio.owncloud.com/phoenix/screenshots/latest/12697/ocis/topBar.png)

</p></details>

2021-01-05 12:34 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISVisual</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/12703/

<p>


Diff Image: </br>
![topBar.png](https://minio.owncloud.com/phoenix/screenshots/12703/diff/ocis/topBar.png)
Actual Image: </br>
![topBar.png](https://minio.owncloud.com/phoenix/screenshots/12703/latest/ocis/topBar.png)
Comparing Against: </br>
![topBar.png](https://raw.githubusercontent.com/owncloud/web/visual-regression-testing/tests/vrt/baseline/ocis/topBar.png)

</p></details>

2021-01-07 08:47 UTC, LukasHirt commented
My original thought was that we'll add such visual checks into already existing steps instead of introducing custom scenarios for them. Not to have to write them down in such a way + save us having to spin up another pipeline for it. Also, this could then check in different states of UI without duplicating some steps e.g. check when files list is loaded, check when the sidebar is opened, check when a resource is shared and people accordion is opened... Does that make sense? I did the same approach with unit tests where I'm checking for snapshots of the code - https://github.com/owncloud/web/blob/85e53fc71c4dd32e2830de1349d6d1e1cd1a610a/tests/unit/specs/TopBar.spec.js#L32

2021-01-07 10:34 UTC, dpakach commented
@LukasHirt Yes, that approach will work but I see a few potential problems, 
1. Since we will have the checks within existing steps, which are called from many scenarios, we will be doing the same checks from many different places (we can probably solve this by combination having a config option and check the screenshots and cucumber tags).

2. Since we will have the visual regression testing mixed up with other scenarios, we will have a hard time keeping tabs on how much visual regression testing we have, Having them in a separate scenario will give us a proper idea of exactly how much visual regression tests we have.

2021-01-13 07:10 UTC, individual-it requested changes
code looks good to me, please document the usage (or create an issue to write docs) and squash commits

2021-01-15 05:27 UTC, individual-it requested changes
small typo only

2021-01-15 05:27 UTC, individual-it commented on docs/testing.md
> +When you run the accpetance tests normally, all the visual regression comparisions are skipped. To run the acceptance test suite with the Visual comparision enabled you need to set the env variable,
```suggestion
When you run the acceptance tests as usual, all the visual regression comparisons are skipped. To run the acceptance test suite with the visual comparison enabled you need to set the env variable, `VISUAL_TEST` to `true`
```

2021-01-15 06:30 UTC, individual-it approved these changes

2021-01-18 04:59 UTC, merged