[Tests-Only] Adds tests for sharing file after renaming it
owncloud/web pull request #4575
Opened 2020-12-31 10:12 UTC by SwikritiT

## Description
 Adds tests for sharing file after renaming it 

## Related Issue

- https://github.com/owncloud/web/issues/4192

## How Has This Been Tested?

- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-01-01 11:34 UTC, swoichha commented on tests/acceptance/features/webUISharingInternalUsersToRoot/shareWithUsers.feature
> +    Then file "newLorem.txt" should be listed on the webUI
IMO we can put these as Given steps.

2021-01-04 11:40 UTC, kiranparajuli589 reviewed
LGTM  :+1:

2021-01-06 11:26 UTC, dpakach reviewed
LGTM :+1:

2021-01-12 11:02 UTC, swoichha reviewed
LGTM

2021-01-12 12:32 UTC, individual-it requested changes
please solve the conflicts, rest looks good

2021-01-13 07:11 UTC, individual-it approved these changes

2021-01-13 07:11 UTC, merged