[tests-only] Add webui tests for markdown editor
owncloud/web pull request #4592
Opened 2021-01-08 07:38 UTC by saw-jan

## Description
Adds webui tests for markdown editor

## How Has This Been Tested?

- test environment: local

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [x] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-01-08 12:05 UTC, individual-it requested changes
After saving the file I would suggest to check the content via webdav API and not UI
we need a test that checks that the correct content is displayed on the UI, but checking that the content was correctly saved should happen by webdav, no need to re-open the file again

2021-01-08 12:05 UTC, individual-it commented on tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
> +    And the preview panel should have the content "updating the file with new content" in the WebUI
Then?

2021-01-08 12:05 UTC, individual-it commented on tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
> +    Then the file should have content "simple markdown file new content added" in the markdown editor webUI
```suggestion
    And the file should have content "simple markdown file new content added" in the markdown editor webUI
```

2021-01-08 12:05 UTC, individual-it commented on tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
> +    Then the file should not have content "updated content" in the markdown editor webUI
And
And

2021-01-13 07:15 UTC, individual-it requested changes

2021-01-13 07:15 UTC, individual-it commented on tests/acceptance/features/webUIMarkdownEditor/markdownFile.feature
> +    Then as "user1" the file "simple.md" should not have the content "updated content"
no need to check that, the next step will check the correct content and that makes sure the content is not any of the other infinite possibilities

2021-01-13 08:14 UTC, individual-it approved these changes

2021-01-14 03:16 UTC, phil-davis approved these changes

2021-01-14 03:16 UTC, merged