[Tests-Only] Strictly check for the image for media viewer preview
owncloud/web pull request #4662
Opened 2021-01-27 06:55 UTC by jasson99

## Description
This PR adjusts the preview image assertion such that the presence of the image is checked strictly.

## Motivation and Context
The preview of image is not visible but the tests were passing after checking the `preview-loaded` attribute's value and asserting it's true. So the step implementation is adjusted such that when the preview-loaded returns true, the presence of image is also checked.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-01-27 08:27 UTC, individual-it requested changes

2021-01-27 08:27 UTC, individual-it commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +        await this.useXpath().waitForElementVisible(imageSelector)
I think we should do that before retrieving the result

2021-01-27 09:30 UTC, individual-it requested changes
LGTM, please squash commits

2021-01-27 11:14 UTC, individual-it approved these changes

2021-01-28 03:24 UTC, phil-davis commented
@jasson99 please rebase and resolve conflicts

2021-01-28 03:33 UTC, phil-davis approved these changes

2021-01-28 04:05 UTC, phil-davis commented
@jasson99 https://drone.owncloud.com/owncloud/web/12940/5/20
```
unsh: Total unexpected failed scenarios throughout the test run:
webUIPreview/imageMediaViewer.feature:154
webUIPreview/imageMediaViewer.feature:136
```

2021-01-28 11:36 UTC, merged