[Tests-Only]Logic for create user and add to group for ocis user has been fixed
owncloud/web pull request #4818
Opened 2021-03-17 08:46 UTC by Talank

## Description
If the test is running in OCIS, then the user creation and adding user to the group was done using `ldap` which is no longer valid. So, this logic has been fixed.

## Related Issue
- Fixes <issue_link>

## How Has This Been Tested?
- locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-03-18 03:20 UTC, individual-it requested changes
tests fail for some reason, e.g. there are error 500 when accepting a share :-( please investigate

2021-03-18 08:11 UTC, Talank commented
Those tests with 500 errors are actually expected to fail, and the CI is failing because we have now more tests passing as group creation logic is fixed. https://drone.owncloud.com/owncloud/web/13573

2021-03-18 08:49 UTC, individual-it approved these changes
please update the commit id of web in the ocis repo

2021-03-22 04:16 UTC, dpakach reviewed
lgtm :+1:

2021-03-30 04:35 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13987/

<p>


![20210330-043226-057.png](https://minio.owncloud.com/phoenix/screenshots/13987/20210330-043226-057.png)
![20210330-043241-386.png](https://minio.owncloud.com/phoenix/screenshots/13987/20210330-043241-386.png)

</p></details>

2021-03-30 06:19 UTC, merged