[Tests-Only]Configure expected failures file for remaining suites and adjust line changes in expected failures
owncloud/web pull request #4851
Opened 2021-03-25 07:47 UTC by jasson99

## Description
This PR Configure expected failures file for iPhone & XGA resolution, and also adjusts the line changes in expected failures file for ocis.

## Related Issue
- https://github.com/owncloud/web/issues/4850

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-03-25 08:09 UTC, individual-it requested changes
why do the line numbers need to be adjusted?

2021-03-25 08:09 UTC, individual-it commented on .drone.star
> +			    'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md',
wrong indent

2021-03-25 08:31 UTC, jasson99 commented on .drone.star
> +			    'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/expected-failures-with-oc10-server-oauth2-login.md',
fixed

2021-03-25 08:52 UTC, individual-it approved these changes

2021-03-25 10:28 UTC, dpakach commented on .drone.star
> +			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md',
```suggestion
			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md',
```

2021-03-25 10:28 UTC, dpakach commented on .drone.star
> +			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md',
```suggestion
			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md',
```

2021-03-25 10:30 UTC, jasson99 commented on .drone.star
> +			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/tests/acceptance/expected-failures-XGA-with-oc10-server-oauth2-login.md',
fixed

2021-03-25 10:30 UTC, jasson99 commented on .drone.star
> +			        'EXPECTED_FAILURES_FILE': '/var/www/owncloud/web/tests/acceptance/tests/acceptance/expected-failures-Iphone-oc10-server-oauth2-login.md',
fixed

2021-03-26 03:34 UTC, jasson99 commented
These changes are already merged through cherry-pick of the commit

2021-03-26 03:34 UTC, closed without merging