[tests-only] Used skeleton files wisely on webUISharingInternalUsers feature
owncloud/web pull request #4875
Opened 2021-03-29 05:59 UTC by SwikritiT

## Description
refactor steps with appropriate skeleton files.
Following suites have been refactored:
- webUISharingInternalUsers

## Related Issue

- Part of owncloud/QA#659

## Motivation and Context

## How Has This Been Tested?

- :robot:

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-03-29 06:22 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13935/

<p>


![20210329-060626-689.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-060626-689.png)
![20210329-060659-430.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-060659-430.png)
![20210329-061241-248.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061241-248.png)
![20210329-061312-536.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061312-536.png)
![20210329-061343-870.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061343-870.png)
![20210329-061415-990.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061415-990.png)
![20210329-061558-965.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061558-965.png)
![20210329-061632-190.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061632-190.png)
![20210329-061722-536.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061722-536.png)
![20210329-061754-704.png](https://minio.owncloud.com/phoenix/screenshots/13935/20210329-061754-704.png)

</p></details>

2021-03-29 07:30 UTC, Talank reviewed
The changes LGTM. Also, update the expected failure files.

2021-03-29 09:22 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13954/

<p>


![20210329-090624-596.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-090624-596.png)
![20210329-090659-023.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-090659-023.png)
![20210329-091254-732.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091254-732.png)
![20210329-091326-560.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091326-560.png)
![20210329-091358-199.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091358-199.png)
![20210329-091430-854.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091430-854.png)
![20210329-091636-392.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091636-392.png)
![20210329-091709-072.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091709-072.png)
![20210329-091802-057.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091802-057.png)
![20210329-091836-002.png](https://minio.owncloud.com/phoenix/screenshots/13954/20210329-091836-002.png)

</p></details>

2021-03-29 10:12 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13958/

<p>


![20210329-095456-235.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-095456-235.png)
![20210329-095529-876.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-095529-876.png)
![20210329-100146-273.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100146-273.png)
![20210329-100220-064.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100220-064.png)
![20210329-100253-804.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100253-804.png)
![20210329-100326-885.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100326-885.png)
![20210329-100519-946.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100519-946.png)
![20210329-100555-675.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100555-675.png)
![20210329-100652-770.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100652-770.png)
![20210329-100747-380.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-100747-380.png)

</p></details>

2021-03-29 10:13 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13958/

<p>


![20210329-101014-329.png](https://minio.owncloud.com/phoenix/screenshots/13958/20210329-101014-329.png)

</p></details>

2021-03-30 04:03 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13983/

<p>


![20210330-035939-267.png](https://minio.owncloud.com/phoenix/screenshots/13983/20210330-035939-267.png)
![20210330-035956-073.png](https://minio.owncloud.com/phoenix/screenshots/13983/20210330-035956-073.png)

</p></details>

2021-03-30 07:50 UTC, kiranparajuli589 commented
lgtm 👍🏼

2021-03-30 07:54 UTC, kiranparajuli589 commented on tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md
> +-   [webUISharingInternalUsers/shareWithUsers.feature:136](https://github.com/owncloud/web/blob/master/tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature#L136)
this test is also failing on oauth2-log oc10server!

2021-04-01 06:50 UTC, individual-it requested changes
good work, just I noticed a small thing that was not part of your PR but could be easily improved

2021-04-01 06:50 UTC, individual-it commented on tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
> +    And user "Brian Murphy" should not be listed in the collaborators list on the webUI
good catch, can you also change that in line 312

2021-04-01 08:00 UTC, individual-it approved these changes

2021-04-01 11:02 UTC, merged