[Tests-Only] Split webUiFiles suite into smaller suites
owncloud/web pull request #4877
Opened 2021-03-29 07:55 UTC by saw-jan

## Description
move some of the webUIFiles feature files into a separate suite folder

## Related Issue
https://github.com/owncloud/web/issues/4876

## How Has This Been Tested?
- test environment:

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-03-29 08:32 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>FilesList</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13947/

<p>


![20210329-082923-543.png](https://minio.owncloud.com/phoenix/screenshots/13947/20210329-082923-543.png)
![20210329-083017-836.png](https://minio.owncloud.com/phoenix/screenshots/13947/20210329-083017-836.png)
![20210329-083052-589.png](https://minio.owncloud.com/phoenix/screenshots/13947/20210329-083052-589.png)
![20210329-083126-935.png](https://minio.owncloud.com/phoenix/screenshots/13947/20210329-083126-935.png)

</p></details>

2021-03-29 08:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13949/

<p>


![20210329-084114-913.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084114-913.png)
![20210329-084149-263.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084149-263.png)
![20210329-084818-438.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084818-438.png)
![20210329-084850-597.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084850-597.png)
![20210329-084923-159.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084923-159.png)
![20210329-084954-921.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-084954-921.png)
![20210329-085136-968.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-085136-968.png)
![20210329-085210-027.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-085210-027.png)
![20210329-085301-572.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-085301-572.png)
![20210329-085335-600.png](https://minio.owncloud.com/phoenix/screenshots/13949/20210329-085335-600.png)

</p></details>

2021-03-29 09:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13952/

<p>


![20210329-084911-356.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-084911-356.png)
![20210329-084944-077.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-084944-077.png)
![20210329-085543-304.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085543-304.png)
![20210329-085613-890.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085613-890.png)
![20210329-085644-536.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085644-536.png)
![20210329-085714-499.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085714-499.png)
![20210329-085847-063.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085847-063.png)
![20210329-085919-017.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-085919-017.png)
![20210329-090008-085.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-090008-085.png)
![20210329-090041-050.png](https://minio.owncloud.com/phoenix/screenshots/13952/20210329-090041-050.png)

</p></details>

2021-03-29 09:09 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13951/

<p>


![20210329-085105-776.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-085105-776.png)
![20210329-085202-829.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-085202-829.png)
![20210329-085857-097.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-085857-097.png)
![20210329-085937-229.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-085937-229.png)
![20210329-090012-701.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090012-701.png)
![20210329-090047-060.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090047-060.png)
![20210329-090245-053.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090245-053.png)
![20210329-090322-288.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090322-288.png)
![20210329-090421-709.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090421-709.png)
![20210329-090457-224.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-090457-224.png)

</p></details>

2021-03-29 09:20 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13951/

<p>


![20210329-091031-572.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-091031-572.png)
![20210329-091610-253.png](https://minio.owncloud.com/phoenix/screenshots/13951/20210329-091610-253.png)

</p></details>

2021-03-29 10:19 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13959/

<p>


![20210329-101606-240.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-101606-240.png)
![20210329-101619-813.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-101619-813.png)

</p></details>

2021-03-29 10:31 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13959/

<p>


![20210329-101446-200.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-101446-200.png)
![20210329-101517-676.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-101517-676.png)
![20210329-102051-830.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102051-830.png)
![20210329-102123-334.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102123-334.png)
![20210329-102155-119.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102155-119.png)
![20210329-102227-268.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102227-268.png)
![20210329-102410-245.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102410-245.png)
![20210329-102443-493.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102443-493.png)
![20210329-102557-261.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102557-261.png)
![20210329-102630-037.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-102630-037.png)

</p></details>

2021-03-29 10:42 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13959/

<p>


![20210329-101836-247.png](https://minio.owncloud.com/phoenix/screenshots/13959/20210329-101836-247.png)

</p></details>

2021-03-29 14:15 UTC, dpakach requested changes
Having too many small suites will also hurt CI. It will occupy more drone agents to run tests while other builds will be pending. Furthermore, as the number of pipelines increases, we will just be doing the same mundane builds/setup tasks multiple times.
So I suggest you should divide it into fewer parts. 2 should be fine IMO.

2021-03-30 07:40 UTC, kiranparajuli589 commented on .drone.star
> +				'OCISFiles1': [
```suggestion
				'webUIOCISFiles1': [
```

2021-03-30 10:54 UTC, dpakach commented on .drone.star
> +
remove extra line

2021-03-30 10:54 UTC, dpakach commented on .drone.star
> +
remove extra lines

2021-04-01 05:12 UTC, dpakach approved these changes
lgtm

2021-04-01 06:50 UTC, individual-it approved these changes

2021-04-01 07:55 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14137/

<p>


![20210401-075330-072.png](https://minio.owncloud.com/phoenix/screenshots/14137/20210401-075330-072.png)

</p></details>

2021-04-06 05:44 UTC, merged