Create shared by link page
owncloud/web pull request #4881
Opened 2021-03-29 14:54 UTC by LukasHirt

Split private and public shares

2021-03-29 15:24 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13977/

<p>


![20210329-150147-423.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-150147-423.png)
![20210329-150231-712.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-150231-712.png)
![20210329-151015-853.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151015-853.png)
![20210329-151048-915.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151048-915.png)
![20210329-152020-786.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152020-786.png)
![20210329-152055-424.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152055-424.png)

</p></details>

2021-03-29 15:30 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/13977/

<p>


![20210329-151048-151.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151048-151.png)
![20210329-151121-877.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151121-877.png)
![20210329-151513-669.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151513-669.png)
![20210329-151531-809.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-151531-809.png)
![20210329-152315-092.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152315-092.png)
![20210329-152347-861.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152347-861.png)
![20210329-152420-835.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152420-835.png)
![20210329-152453-575.png](https://minio.owncloud.com/phoenix/screenshots/13977/20210329-152453-575.png)

</p></details>

2021-03-30 08:31 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14009/

<p>


![20210330-082826-009.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-082826-009.png)
![20210330-082841-208.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-082841-208.png)

</p></details>

2021-03-30 08:38 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14009/

<p>


![20210330-082335-941.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-082335-941.png)
![20210330-082355-212.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-082355-212.png)
![20210330-083158-395.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-083158-395.png)
![20210330-083234-820.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-083234-820.png)
![20210330-083307-965.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-083307-965.png)
![20210330-083341-295.png](https://minio.owncloud.com/phoenix/screenshots/14009/20210330-083341-295.png)

</p></details>

2021-03-30 08:43 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14009/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14009/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14009/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 08:53 UTC, wkloucek commented
@LukasHirt please switch to `owncloudci/golang:1.16`

2021-03-30 08:54 UTC, LukasHirt commented
> please switch to owncloudci/golang:1.16

I'll do that, thanks! @wkloucek

2021-03-30 09:00 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14014/

<p>


![20210330-084714-216.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-084714-216.png)
![20210330-084731-752.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-084731-752.png)
![20210330-085440-249.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-085440-249.png)
![20210330-085513-991.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-085513-991.png)
![20210330-085546-971.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-085546-971.png)
![20210330-085619-604.png](https://minio.owncloud.com/phoenix/screenshots/14014/20210330-085619-604.png)

</p></details>

2021-03-30 09:14 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14016/

<p>


![20210330-090004-502.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090004-502.png)
![20210330-090021-577.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090021-577.png)
![20210330-090811-985.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090811-985.png)
![20210330-090846-815.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090846-815.png)
![20210330-090920-790.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090920-790.png)
![20210330-090955-072.png](https://minio.owncloud.com/phoenix/screenshots/14016/20210330-090955-072.png)

</p></details>

2021-03-30 09:20 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14018/

<p>


![20210330-090721-384.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-090721-384.png)
![20210330-090739-398.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-090739-398.png)
![20210330-091427-910.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-091427-910.png)
![20210330-091501-115.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-091501-115.png)
![20210330-091533-818.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-091533-818.png)
![20210330-091605-954.png](https://minio.owncloud.com/phoenix/screenshots/14018/20210330-091605-954.png)

</p></details>

2021-03-30 09:24 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14018/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14018/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14018/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 09:27 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14020/

<p>


![20210330-091838-063.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-091838-063.png)
![20210330-092400-625.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092400-625.png)
![20210330-092415-728.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092415-728.png)

</p></details>

2021-03-30 09:29 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14020/

<p>


![20210330-091650-258.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-091650-258.png)
![20210330-091708-512.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-091708-512.png)
![20210330-092325-172.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092325-172.png)
![20210330-092357-002.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092357-002.png)
![20210330-092428-827.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092428-827.png)
![20210330-092500-048.png](https://minio.owncloud.com/phoenix/screenshots/14020/20210330-092500-048.png)

</p></details>

2021-03-30 11:04 UTC, LukasHirt commented
Reverted back to `webhippie` as the `owncloudci` golang images are breaking the CI currently. Need to be taken care of in own PR

2021-03-30 11:28 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14034/

<p>


![20210330-111431-910.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-111431-910.png)
![20210330-111449-566.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-111449-566.png)
![20210330-112204-356.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-112204-356.png)
![20210330-112259-065.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-112259-065.png)
![20210330-112340-324.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-112340-324.png)
![20210330-112416-686.png](https://minio.owncloud.com/phoenix/screenshots/14034/20210330-112416-686.png)

</p></details>

2021-03-30 12:08 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14038/

<p>


![20210330-115217-853.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-115217-853.png)
![20210330-115236-810.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-115236-810.png)
![20210330-120019-277.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-120019-277.png)
![20210330-120053-139.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-120053-139.png)
![20210330-120146-763.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-120146-763.png)
![20210330-120220-734.png](https://minio.owncloud.com/phoenix/screenshots/14038/20210330-120220-734.png)

</p></details>

2021-03-30 12:12 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14038/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14038/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14038/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 12:59 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Files</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14041/

<p>


![20210330-124732-206.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-124732-206.png)
![20210330-124748-821.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-124748-821.png)
![20210330-125359-787.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-125359-787.png)
![20210330-125450-785.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-125450-785.png)
![20210330-125520-957.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-125520-957.png)
![20210330-125552-492.png](https://minio.owncloud.com/phoenix/screenshots/14041/20210330-125552-492.png)

</p></details>

2021-03-30 13:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14041/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14041/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14041/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 13:47 UTC, LukasHirt commented
Tests failing in the CI but not locally (will be updating this comment in case of new ones):

- [  ] webUISharingExternalToRoot/federationSharing.feature:250

2021-03-30 13:49 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14043/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14043/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14043/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 14:02 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14047/

<p>


![20210330-135949-014.png](https://minio.owncloud.com/phoenix/screenshots/14047/20210330-135949-014.png)

</p></details>

2021-03-30 14:13 UTC, kulmann requested changes

2021-03-30 14:13 UTC, kulmann commented on packages/web-app-files/src/views/SharedViaLink.vue
> +        id="files-shared-with-others-empty"
```suggestion
        id="files-shared-via-link-empty"
```

2021-03-30 14:13 UTC, kulmann commented on packages/web-app-files/src/views/SharedViaLink.vue
> +        id="files-shared-with-others-table"
```suggestion
        id="files-shared-via-link-table"
```

2021-03-30 14:29 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14047/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14047/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14047/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 14:31 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14052/

<p>


![20210330-142923-052.png](https://minio.owncloud.com/phoenix/screenshots/14052/20210330-142923-052.png)

</p></details>

2021-03-30 14:31 UTC, LukasHirt commented
@individual-it Could anybody from your team pls update the screenshot in oCIS for `webUIFiles/fileList.feature:40`? We currently have issues running acceptance tests for oCIS on mac so I cannot updated them there. I tried to copy the screenshot from oC10 but oCIS hasn't got Favorites item 🙈

2021-03-30 14:34 UTC, kulmann approved these changes
Looks good to me 👍  baseline image of the sidebar for ocis needs to be solved.

2021-03-30 14:38 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14049/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14049/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14049/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-30 14:58 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISFiles</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14052/

<p>


Diff Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14052/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://minio.owncloud.com/phoenix/screenshots/14052/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/split-shared-with-pages/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-03-31 03:19 UTC, individual-it commented
we are tracking random failures currently here https://github.com/owncloud/web/issues/4878
I've added  webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:92

 webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:92 was already on the list

and I could not find any drone run where webUISharingExternalToRoot/federationSharing.feature:250 failed

2021-03-31 05:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14071/

<p>


![20210331-050212-968.png](https://minio.owncloud.com/phoenix/screenshots/14071/20210331-050212-968.png)
![20210331-050228-775.png](https://minio.owncloud.com/phoenix/screenshots/14071/20210331-050228-775.png)

</p></details>

2021-03-31 06:34 UTC, individual-it commented
deletion has still a problem with locked files on oC10. Tests will be skipped in https://github.com/owncloud/web/pull/4897

see also
  https://github.com/owncloud/web/issues/4582
  https://github.com/owncloud/web/issues/4784

2021-03-31 09:10 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14089/

<p>


![20210331-090736-920.png](https://minio.owncloud.com/phoenix/screenshots/14089/20210331-090736-920.png)

</p></details>

2021-03-31 10:00 UTC, merged