[Tests-Only] refactor share expire tests to not use skeleton files
owncloud/web pull request #4921
Opened 2021-04-07 08:15 UTC by dpakach

## Description

Remove the use of skeleton files in tests for 
 webUISharingInternalUsersBlacklisted
 webUISharingInternalUsersExpire
 webUISharingInternalUsersExpireToRoot

## Related Issue

- Related https://github.com/owncloud/QA/issues/659

## Motivation and Context

To speed up ci

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-04-07 08:56 UTC, Talank requested changes
Use And for consecutive Givens

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```suggestion
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```suggestion
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```suggestion
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```suggestion
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```suggestion
    And user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
```

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
same here

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpire/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
and here

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpireToRoot/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
and here

2021-04-07 08:56 UTC, Talank commented on tests/acceptance/features/webUISharingInternalUsersExpireToRoot/shareWithUsersExpiringShares.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "lorem.txt"
and here

2021-04-07 09:45 UTC, dpakach commented
@Talank fixed everything, there was bug in code

2021-04-08 06:35 UTC, Talank approved these changes

2021-04-09 05:02 UTC, individual-it approved these changes

2021-04-09 05:02 UTC, merged