[Tests-Only] refactor share permission tests to not use skeleton files
owncloud/web pull request #4957
Opened 2021-04-12 12:39 UTC by dpakach

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-04-12 12:59 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPermissionsUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14553/

<p>


![20210412-125757-375.png](https://minio.owncloud.com/phoenix/screenshots/14553/20210412-125757-375.png)
![20210412-125855-486.png](https://minio.owncloud.com/phoenix/screenshots/14553/20210412-125855-486.png)

</p></details>

2021-04-13 08:44 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/14584/

<p>


![20210413-084309-614.png](https://minio.owncloud.com/phoenix/screenshots/14584/20210413-084309-614.png)

</p></details>

2021-04-16 10:19 UTC, swoichha requested changes

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingNotificationsToRoot/shareWithGroups.feature
> +    Given user "Carol" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```suggestion
    And user "Carol" has created folder "simple-folder"
    And user "Carol" has uploaded file "data.zip" to "data.zip"
    And user "Carol" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingNotificationsToRoot/shareWithUsers.feature
> +    Given user "Alice" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```suggestion
    And user "Alice" has created folder "simple-folder"
    And user "Alice" has created folder "simple-empty-folder"
    And user "Alice" has uploaded file "data.zip" to "data.zip"
    And user "Alice" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
> +      | file_target | /lorem.txt       |
Indentation can be fixed here.

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/shareFileWithMultipleUsers.feature
> +      | file_target | /lorem.txt       |
Indentation can be fixed here.

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
> +      | file_target | /simple-folder   |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/shareFolderWithMultipleUsers.feature
> +      | file_target | /simple-folder   |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
> +      | file_target | /lorem.txt       |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFileGroup.feature
> +      | file_target | /lorem.txt       |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
> +      | file_target | /simple-folder   |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionToRoot/sharePermissionsFoldersGroup.feature
> +      | file_target | /simple-folder   |
same as above

2021-04-16 10:19 UTC, swoichha commented on tests/acceptance/features/webUISharingPermissionsUsers/sharePermissionsUsers.feature
> +    Given user "Brian" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```suggestion
    And user "Brian" has created folder "simple-folder"
    And user "Brian" has created folder "simple-empty-folder"
    And user "Brian" has created folder "simple-folder/simple-empty-folder"
    And user "Brian" has uploaded file "data.zip" to "data.zip"
    And user "Brian" has uploaded file "lorem.txt" to "lorem.txt"
    And user "Brian" has uploaded file "lorem.txt" to "simple-folder/lorem.txt"
```

2021-04-16 11:28 UTC, swoichha approved these changes
LGTM

2021-04-16 11:42 UTC, individual-it approved these changes
please resolve conflicts

2021-04-16 12:20 UTC, merged