Enhanche a11y on app-switcher
owncloud/web pull request #4997
Opened 2021-04-22 09:46 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-04-22 09:50 UTC, JanAckermann commented
@pascalwengerter @kulmann we are not quite sure with the UI Kit events here, I think this should be moved in to the oc-drop component where we can pass callbacks for onClose and onOpen

@pascalwengerter There is also an issue, when opening the app switcher the first item gets focused but the style won't be applied, any idea?

2021-04-22 09:51 UTC, JanAckermann commented on packages/web-runtime/src/components/ApplicationsMenu.vue
> +      <oc-icon :uk-tooltip="applicationSwitcherLabel" name="apps" class="uk-flex" />
Moved uk-tooltip to the icon because it overwrites the aria expand of the button

2021-04-22 09:51 UTC, JanAckermann commented on packages/web-runtime/src/components/ApplicationsMenu.vue
> -    }
this never worked

2021-04-22 10:57 UTC, JammingBen commented
> @pascalwengerter There is also an issue, when opening the app switcher the first item gets focused but the style won't be applied, any idea?

A bit more context to that: Focus seem to work a little different depending on the element. You can notice that when clicking a button -> it will have a focus border. In contrast to clicking a link -> it wont have a focus border. When navigating via keyboard, each element has a focus border.

Now the elements in the application switcher are links. I think, because of this, the border on the first element wont show when opening the application switcher. It works with those elements being buttons. It also works when opening the switcher via keyboard. Just not on click.

2021-04-22 11:08 UTC, pascalwengerter requested changes

2021-04-22 11:08 UTC, pascalwengerter commented on packages/web-runtime/src/components/ApplicationsMenu.vue
> +        <ul v-for="(n, nid) in menuItems" :key="`apps-menu-${nid}`" class="uk-width-1-3 uk-list">
v-for needs to happen on the `<li>` level if I'm not mistaken? 🤔

2021-04-22 13:30 UTC, pascalwengerter reviewed
The code looks fine but I'm having troubles noticing anything different when running locally and checking for anything in the browser. Is it purely for screenreaders, does it only work in specific browsers or am I missing something? :)

2021-04-23 05:46 UTC, JanAckermann commented
> The code looks fine but I'm having troubles noticing anything different when running locally and checking for anything in the browser. Is it purely for screenreaders, does it only work in specific browsers or am I missing something? :)

Can you give some context according to your question?

2021-04-23 07:15 UTC, pascalwengerter commented
> > The code looks fine but I'm having troubles noticing anything different when running locally and checking for anything in the browser. Is it purely for screenreaders, does it only work in specific browsers or am I missing something? :)
> 
> Can you give some context according to your question?

Sure, sorry my comment was a bit obscure in retrospect. What part of a11y is improved by this PR? I didn't notice different behaviour when checking out the changes locally and looking at the UI + navigating with the keyboard (which I kinda assumed would've been improved by your changes, but I may be mistaken 😉 )

2021-04-23 07:16 UTC, pascalwengerter commented
Aside from that, if you're done here you could remove the `[WIP]` in the PR title and we could merge it?

2021-04-23 07:47 UTC, JanAckermann commented
@pascalwengerter to make it short:
Opening the App switcher menu will focus on the first link now, but unfortunately, the focus style won't be applied if you click on the app switcher button. But if you hit the app switcher button with tab and press enter, the style will be applied.
I have no clue why this is the case, and not sure if we can merge it in that state

2021-04-26 08:18 UTC, pascalwengerter approved these changes
LGTM, focus management in FF still weird, but we'll update this with the new layout soon too I guess

2021-04-26 08:53 UTC, merged