Fix z-index on the new file menu
owncloud/web pull request #5056
Opened 2021-04-30 11:29 UTC by JammingBen

## Description
Removed the z-index on the files-app-bar because it prevented the new file menu from having a higher z-index than the table headers. As a result the new file menu was being overlapped by them.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-04-30 11:34 UTC, pascalwengerter approved these changes
Finally 💪🏽 that was annoying!

2021-04-30 11:36 UTC, JanAckermann approved these changes

2021-04-30 12:02 UTC, pascalwengerter requested changes
Sorry, target branch needs to be `a11y-swarming`!

2021-04-30 12:29 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15243/

<p>


![20210430-122250-761.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122250-761.png)
![20210430-122431-578.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122431-578.png)
![20210430-122503-534.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122503-534.png)
![20210430-122535-365.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122535-365.png)
![20210430-122654-850.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122654-850.png)
![20210430-122816-607.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122816-607.png)
![20210430-122829-650.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122829-650.png)

</p></details>

2021-04-30 12:33 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15243/

<p>


![20210430-122252-890.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122252-890.png)
![20210430-122320-161.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122320-161.png)
![20210430-122356-830.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122356-830.png)
![20210430-122425-757.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122425-757.png)
![20210430-122712-791.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122712-791.png)
![20210430-122740-561.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122740-561.png)
![20210430-122808-843.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122808-843.png)
![20210430-122837-151.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122837-151.png)
![20210430-122946-252.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-122946-252.png)
![20210430-123015-453.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-123015-453.png)
![20210430-123051-708.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-123051-708.png)
![20210430-123119-571.png](https://cache.owncloud.com/owncloud/web/screenshots/15243/20210430-123119-571.png)

</p></details>

2021-04-30 13:08 UTC, JammingBen commented
Ahhh now other modals are hidden, need to work on that again.

2021-04-30 13:47 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15247/

<p>


![20210430-134027-573.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134027-573.png)
![20210430-134204-761.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134204-761.png)
![20210430-134236-510.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134236-510.png)
![20210430-134308-203.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134308-203.png)
![20210430-134430-503.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134430-503.png)
![20210430-134555-408.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134555-408.png)
![20210430-134608-728.png](https://cache.owncloud.com/owncloud/web/screenshots/15247/20210430-134608-728.png)

</p></details>

2021-05-03 14:07 UTC, pascalwengerter approved these changes
LGTM 😎

2021-05-04 13:09 UTC, kulmann approved these changes

2021-05-04 13:09 UTC, merged