[Tests-Only] run tests using middleware
owncloud/web pull request #5136
Opened 2021-05-21 11:21 UTC by dpakach

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-05-21 11:49 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15596/

<p>


### webUISharingNotifications-shareWithUsers-feature-21.png
 ![webUISharingNotifications-shareWithUsers-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotifications-shareWithUsers-feature-21.png) 

### webUISharingNotifications-shareWithUsers-feature-32.png
 ![webUISharingNotifications-shareWithUsers-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotifications-shareWithUsers-feature-32.png) 

### webUISharingNotifications-shareWithUsers-feature-40.png
 ![webUISharingNotifications-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotifications-shareWithUsers-feature-40.png) 

### webUISharingNotifications-shareWithUsers-feature-53.png
 ![webUISharingNotifications-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotifications-shareWithUsers-feature-53.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotificationsToRoot-shareWithUsers-feature-19.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotificationsToRoot-shareWithUsers-feature-31.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotificationsToRoot-shareWithUsers-feature-40.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingNotificationsToRoot-shareWithUsers-feature-53.png) 


</p></details>

2021-05-21 11:50 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFilesList</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15596/

<p>


### webUIFilesList-fileList-feature-15.png
 ![webUIFilesList-fileList-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-15.png) 

### webUIFilesList-fileList-feature-22.png
 ![webUIFilesList-fileList-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-22.png) 

### webUIFilesList-fileList-feature-28.png
 ![webUIFilesList-fileList-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-28.png) 

### webUIFilesList-fileList-feature-33.png
 ![webUIFilesList-fileList-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-33.png) 

### webUIFilesList-fileList-feature-41.png
 ![webUIFilesList-fileList-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-41.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-46.png) 

### webUIFilesList-fileList-feature-51.png
 ![webUIFilesList-fileList-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-51.png) 

### webUIFilesList-fileList-feature-60.png
 ![webUIFilesList-fileList-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-60.png) 

### webUIFilesList-fileList-feature-73.png
 ![webUIFilesList-fileList-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-fileList-feature-73.png) 

### webUIFilesList-sort-feature-31.png
 ![webUIFilesList-sort-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-sort-feature-31.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-sort-feature-51.png) 

### webUIFilesList-sort-feature-72.png
 ![webUIFilesList-sort-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesList-sort-feature-72.png) 


</p></details>

2021-05-21 11:51 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15596/

<p>


### webUIMoveFilesFolders-moveFiles-feature-20.png
 ![webUIMoveFilesFolders-moveFiles-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIMoveFilesFolders-moveFiles-feature-20.png) 

### webUIMoveFilesFolders-moveFiles-feature-51.png
 ![webUIMoveFilesFolders-moveFiles-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIMoveFilesFolders-moveFiles-feature-51.png) 

### webUIMoveFilesFolders-moveFolders-feature-20.png
 ![webUIMoveFilesFolders-moveFolders-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIMoveFilesFolders-moveFolders-feature-20.png) 

### webUIMoveFilesFolders-moveFolders-feature-41.png
 ![webUIMoveFilesFolders-moveFolders-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIMoveFilesFolders-moveFolders-feature-41.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingAutocompletion-shareAutocompletion-feature-32.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingAutocompletion-shareAutocompletion-feature-44.png) 

### webUISharingInternalUsers-shareWithUsers-feature-57.png
 ![webUISharingInternalUsers-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsers-shareWithUsers-feature-57.png) 

### webUISharingInternalUsers-shareWithUsers-feature-58.png
 ![webUISharingInternalUsers-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsers-shareWithUsers-feature-58.png) 

### webUISharingInternalUsers-shareWithUsers-feature-59.png
 ![webUISharingInternalUsers-shareWithUsers-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsers-shareWithUsers-feature-59.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-11.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-11.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingPublicBasic-publicLinkCreate-feature-11.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-28.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingPublicBasic-publicLinkCreate-feature-28.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png) 

### webUITrashbinDelete-trashbinDelete-feature-29.png
 ![webUITrashbinDelete-trashbinDelete-feature-29.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUITrashbinDelete-trashbinDelete-feature-29.png) 

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
 ![webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png) 

### webUITrashbinRestore-trashbinRestore-feature-14.png
 ![webUITrashbinRestore-trashbinRestore-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUITrashbinRestore-trashbinRestore-feature-14.png) 

### webUITrashbinRestore-trashbinRestore-feature-46.png
 ![webUITrashbinRestore-trashbinRestore-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUITrashbinRestore-trashbinRestore-feature-46.png) 

### webUIUpload-upload-feature-15.png
 ![webUIUpload-upload-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-15.png) 

### webUIUpload-upload-feature-22.png
 ![webUIUpload-upload-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-22.png) 

### webUIUpload-upload-feature-34.png
 ![webUIUpload-upload-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-34.png) 

### webUIUpload-upload-feature-48.png
 ![webUIUpload-upload-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-48.png) 

### webUIUpload-upload-feature-65.png
 ![webUIUpload-upload-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-65.png) 

### webUIUpload-upload-feature-89.png
 ![webUIUpload-upload-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-89.png) 

### webUIUpload-upload-feature-98.png
 ![webUIUpload-upload-feature-98.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-upload-feature-98.png) 

### webUIUpload-uploadEdgecases-feature-48.png
 ![webUIUpload-uploadEdgecases-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-uploadEdgecases-feature-48.png) 

### webUIUpload-uploadEdgecases-feature-49.png
 ![webUIUpload-uploadEdgecases-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-uploadEdgecases-feature-49.png) 

### webUIUpload-uploadEdgecases-feature-50.png
 ![webUIUpload-uploadEdgecases-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-uploadEdgecases-feature-50.png) 

### webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png
 ![webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png) 


</p></details>

2021-05-21 11:52 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15596/

<p>


### webUICreateFilesFolders-createFolderEdgeCases-feature-60.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUICreateFilesFolders-createFolderEdgeCases-feature-60.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-61.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUICreateFilesFolders-createFolderEdgeCases-feature-61.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-62.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUICreateFilesFolders-createFolderEdgeCases-feature-62.png) 

### webUICreateFilesFolders-createFolders-feature-12.png
 ![webUICreateFilesFolders-createFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUICreateFilesFolders-createFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-55.png
 ![webUIFavorites-unfavoriteFile-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFavorites-unfavoriteFile-feature-55.png) 

### webUIFilesCopy-copy-feature-10.png
 ![webUIFilesCopy-copy-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesCopy-copy-feature-10.png) 

### webUIFilesCopy-copy-feature-36.png
 ![webUIFilesCopy-copy-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesCopy-copy-feature-36.png) 

### webUIFilesSearch-search-feature-27.png
 ![webUIFilesSearch-search-feature-27.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIFilesSearch-search-feature-27.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-9.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-9.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIPrivateLinks-accessingPrivateLinks-feature-9.png) 

### webUIRenameFiles-renameFiles-feature-22.png
 ![webUIRenameFiles-renameFiles-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-22.png) 

### webUIRenameFiles-renameFiles-feature-23.png
 ![webUIRenameFiles-renameFiles-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-23.png) 

### webUIRenameFiles-renameFiles-feature-24.png
 ![webUIRenameFiles-renameFiles-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-24.png) 

### webUIRenameFiles-renameFiles-feature-25.png
 ![webUIRenameFiles-renameFiles-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-25.png) 

### webUIRenameFiles-renameFiles-feature-26.png
 ![webUIRenameFiles-renameFiles-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-26.png) 

### webUIRenameFiles-renameFiles-feature-43.png
 ![webUIRenameFiles-renameFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRenameFiles-renameFiles-feature-43.png) 

### webUIRestrictSharing-disableSharing-feature-16.png
 ![webUIRestrictSharing-disableSharing-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-disableSharing-feature-16.png) 

### webUIRestrictSharing-restrictReSharing-feature-23.png
 ![webUIRestrictSharing-restrictReSharing-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-restrictReSharing-feature-23.png) 

### webUIRestrictSharing-restrictReSharing-feature-42.png
 ![webUIRestrictSharing-restrictReSharing-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-restrictReSharing-feature-42.png) 

### webUIRestrictSharing-restrictSharing-feature-31.png
 ![webUIRestrictSharing-restrictSharing-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-restrictSharing-feature-31.png) 

### webUIRestrictSharing-restrictSharing-feature-40.png
 ![webUIRestrictSharing-restrictSharing-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-restrictSharing-feature-40.png) 

### webUIRestrictSharing-restrictSharing-feature-56.png
 ![webUIRestrictSharing-restrictSharing-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUIRestrictSharing-restrictSharing-feature-56.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingAcceptSharesToRoot-acceptShares-feature-50.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15596/webUISharingAcceptSharesToRoot-acceptShares-feature-72.png) 


</p></details>

2021-05-24 03:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15608/

<p>


### webUISharingNotifications-shareWithUsers-feature-21.png
 ![webUISharingNotifications-shareWithUsers-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotifications-shareWithUsers-feature-21.png) 

### webUISharingNotifications-shareWithUsers-feature-32.png
 ![webUISharingNotifications-shareWithUsers-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotifications-shareWithUsers-feature-32.png) 

### webUISharingNotifications-shareWithUsers-feature-40.png
 ![webUISharingNotifications-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotifications-shareWithUsers-feature-40.png) 

### webUISharingNotifications-shareWithUsers-feature-53.png
 ![webUISharingNotifications-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotifications-shareWithUsers-feature-53.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotificationsToRoot-shareWithUsers-feature-19.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotificationsToRoot-shareWithUsers-feature-31.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotificationsToRoot-shareWithUsers-feature-40.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingNotificationsToRoot-shareWithUsers-feature-53.png) 


</p></details>

2021-05-24 03:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFilesList</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15608/

<p>


### webUIFilesList-fileList-feature-15.png
 ![webUIFilesList-fileList-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-15.png) 

### webUIFilesList-fileList-feature-22.png
 ![webUIFilesList-fileList-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-22.png) 

### webUIFilesList-fileList-feature-28.png
 ![webUIFilesList-fileList-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-28.png) 

### webUIFilesList-fileList-feature-33.png
 ![webUIFilesList-fileList-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-33.png) 

### webUIFilesList-fileList-feature-41.png
 ![webUIFilesList-fileList-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-41.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-46.png) 

### webUIFilesList-fileList-feature-51.png
 ![webUIFilesList-fileList-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-51.png) 

### webUIFilesList-fileList-feature-60.png
 ![webUIFilesList-fileList-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-60.png) 

### webUIFilesList-fileList-feature-73.png
 ![webUIFilesList-fileList-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-fileList-feature-73.png) 

### webUIFilesList-sort-feature-31.png
 ![webUIFilesList-sort-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-sort-feature-31.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-sort-feature-51.png) 

### webUIFilesList-sort-feature-72.png
 ![webUIFilesList-sort-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesList-sort-feature-72.png) 


</p></details>

2021-05-24 03:17 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15608/

<p>


### webUICreateFilesFolders-createFolderEdgeCases-feature-60.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUICreateFilesFolders-createFolderEdgeCases-feature-60.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-61.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUICreateFilesFolders-createFolderEdgeCases-feature-61.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-62.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUICreateFilesFolders-createFolderEdgeCases-feature-62.png) 

### webUICreateFilesFolders-createFolders-feature-12.png
 ![webUICreateFilesFolders-createFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUICreateFilesFolders-createFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-55.png
 ![webUIFavorites-unfavoriteFile-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFavorites-unfavoriteFile-feature-55.png) 

### webUIFilesCopy-copy-feature-10.png
 ![webUIFilesCopy-copy-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesCopy-copy-feature-10.png) 

### webUIFilesCopy-copy-feature-36.png
 ![webUIFilesCopy-copy-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesCopy-copy-feature-36.png) 

### webUIFilesSearch-search-feature-27.png
 ![webUIFilesSearch-search-feature-27.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIFilesSearch-search-feature-27.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-9.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-9.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIPrivateLinks-accessingPrivateLinks-feature-9.png) 

### webUIRenameFiles-renameFiles-feature-22.png
 ![webUIRenameFiles-renameFiles-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-22.png) 

### webUIRenameFiles-renameFiles-feature-23.png
 ![webUIRenameFiles-renameFiles-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-23.png) 

### webUIRenameFiles-renameFiles-feature-24.png
 ![webUIRenameFiles-renameFiles-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-24.png) 

### webUIRenameFiles-renameFiles-feature-25.png
 ![webUIRenameFiles-renameFiles-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-25.png) 

### webUIRenameFiles-renameFiles-feature-26.png
 ![webUIRenameFiles-renameFiles-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-26.png) 

### webUIRenameFiles-renameFiles-feature-43.png
 ![webUIRenameFiles-renameFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRenameFiles-renameFiles-feature-43.png) 

### webUIRestrictSharing-disableSharing-feature-16.png
 ![webUIRestrictSharing-disableSharing-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-disableSharing-feature-16.png) 

### webUIRestrictSharing-restrictReSharing-feature-23.png
 ![webUIRestrictSharing-restrictReSharing-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-restrictReSharing-feature-23.png) 

### webUIRestrictSharing-restrictReSharing-feature-42.png
 ![webUIRestrictSharing-restrictReSharing-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-restrictReSharing-feature-42.png) 

### webUIRestrictSharing-restrictSharing-feature-31.png
 ![webUIRestrictSharing-restrictSharing-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-restrictSharing-feature-31.png) 

### webUIRestrictSharing-restrictSharing-feature-40.png
 ![webUIRestrictSharing-restrictSharing-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-restrictSharing-feature-40.png) 

### webUIRestrictSharing-restrictSharing-feature-56.png
 ![webUIRestrictSharing-restrictSharing-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIRestrictSharing-restrictSharing-feature-56.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingAcceptSharesToRoot-acceptShares-feature-50.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingAcceptSharesToRoot-acceptShares-feature-72.png) 


</p></details>

2021-05-24 03:19 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15608/

<p>


### webUIMoveFilesFolders-moveFiles-feature-20.png
 ![webUIMoveFilesFolders-moveFiles-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIMoveFilesFolders-moveFiles-feature-20.png) 

### webUIMoveFilesFolders-moveFiles-feature-51.png
 ![webUIMoveFilesFolders-moveFiles-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIMoveFilesFolders-moveFiles-feature-51.png) 

### webUIMoveFilesFolders-moveFolders-feature-20.png
 ![webUIMoveFilesFolders-moveFolders-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIMoveFilesFolders-moveFolders-feature-20.png) 

### webUIMoveFilesFolders-moveFolders-feature-41.png
 ![webUIMoveFilesFolders-moveFolders-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIMoveFilesFolders-moveFolders-feature-41.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingAutocompletion-shareAutocompletion-feature-32.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingAutocompletion-shareAutocompletion-feature-44.png) 

### webUISharingInternalUsers-shareWithUsers-feature-57.png
 ![webUISharingInternalUsers-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsers-shareWithUsers-feature-57.png) 

### webUISharingInternalUsers-shareWithUsers-feature-58.png
 ![webUISharingInternalUsers-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsers-shareWithUsers-feature-58.png) 

### webUISharingInternalUsers-shareWithUsers-feature-59.png
 ![webUISharingInternalUsers-shareWithUsers-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsers-shareWithUsers-feature-59.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-11.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-11.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingPublicBasic-publicLinkCreate-feature-11.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-28.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingPublicBasic-publicLinkCreate-feature-28.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png) 

### webUITrashbinDelete-trashbinDelete-feature-29.png
 ![webUITrashbinDelete-trashbinDelete-feature-29.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUITrashbinDelete-trashbinDelete-feature-29.png) 

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
 ![webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png) 

### webUITrashbinRestore-trashbinRestore-feature-14.png
 ![webUITrashbinRestore-trashbinRestore-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUITrashbinRestore-trashbinRestore-feature-14.png) 

### webUITrashbinRestore-trashbinRestore-feature-46.png
 ![webUITrashbinRestore-trashbinRestore-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUITrashbinRestore-trashbinRestore-feature-46.png) 

### webUIUpload-upload-feature-15.png
 ![webUIUpload-upload-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-15.png) 

### webUIUpload-upload-feature-22.png
 ![webUIUpload-upload-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-22.png) 

### webUIUpload-upload-feature-34.png
 ![webUIUpload-upload-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-34.png) 

### webUIUpload-upload-feature-48.png
 ![webUIUpload-upload-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-48.png) 

### webUIUpload-upload-feature-65.png
 ![webUIUpload-upload-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-65.png) 

### webUIUpload-upload-feature-89.png
 ![webUIUpload-upload-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-89.png) 

### webUIUpload-upload-feature-98.png
 ![webUIUpload-upload-feature-98.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-upload-feature-98.png) 

### webUIUpload-uploadEdgecases-feature-48.png
 ![webUIUpload-uploadEdgecases-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-uploadEdgecases-feature-48.png) 

### webUIUpload-uploadEdgecases-feature-49.png
 ![webUIUpload-uploadEdgecases-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-uploadEdgecases-feature-49.png) 

### webUIUpload-uploadEdgecases-feature-50.png
 ![webUIUpload-uploadEdgecases-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-uploadEdgecases-feature-50.png) 

### webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png
 ![webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15608/webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png) 


</p></details>

2021-05-24 03:35 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>oc10-integration-notifications</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15609/

<p>


### webUISharingNotifications-shareWithUsers-feature-21.png
 ![webUISharingNotifications-shareWithUsers-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotifications-shareWithUsers-feature-21.png) 

### webUISharingNotifications-shareWithUsers-feature-32.png
 ![webUISharingNotifications-shareWithUsers-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotifications-shareWithUsers-feature-32.png) 

### webUISharingNotifications-shareWithUsers-feature-40.png
 ![webUISharingNotifications-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotifications-shareWithUsers-feature-40.png) 

### webUISharingNotifications-shareWithUsers-feature-53.png
 ![webUISharingNotifications-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotifications-shareWithUsers-feature-53.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-19.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotificationsToRoot-shareWithUsers-feature-19.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-31.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotificationsToRoot-shareWithUsers-feature-31.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-40.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotificationsToRoot-shareWithUsers-feature-40.png) 

### webUISharingNotificationsToRoot-shareWithUsers-feature-53.png
 ![webUISharingNotificationsToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingNotificationsToRoot-shareWithUsers-feature-53.png) 


</p></details>

2021-05-24 03:36 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFilesList</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15609/

<p>


### webUIFilesList-fileList-feature-15.png
 ![webUIFilesList-fileList-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-15.png) 

### webUIFilesList-fileList-feature-22.png
 ![webUIFilesList-fileList-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-22.png) 

### webUIFilesList-fileList-feature-28.png
 ![webUIFilesList-fileList-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-28.png) 

### webUIFilesList-fileList-feature-33.png
 ![webUIFilesList-fileList-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-33.png) 

### webUIFilesList-fileList-feature-41.png
 ![webUIFilesList-fileList-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-41.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-46.png) 

### webUIFilesList-fileList-feature-51.png
 ![webUIFilesList-fileList-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-51.png) 

### webUIFilesList-fileList-feature-60.png
 ![webUIFilesList-fileList-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-60.png) 

### webUIFilesList-fileList-feature-73.png
 ![webUIFilesList-fileList-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-fileList-feature-73.png) 

### webUIFilesList-sort-feature-31.png
 ![webUIFilesList-sort-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-sort-feature-31.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-sort-feature-51.png) 

### webUIFilesList-sort-feature-72.png
 ![webUIFilesList-sort-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesList-sort-feature-72.png) 


</p></details>

2021-05-24 03:36 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15609/

<p>


### webUIMoveFilesFolders-moveFiles-feature-20.png
 ![webUIMoveFilesFolders-moveFiles-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIMoveFilesFolders-moveFiles-feature-20.png) 

### webUIMoveFilesFolders-moveFiles-feature-51.png
 ![webUIMoveFilesFolders-moveFiles-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIMoveFilesFolders-moveFiles-feature-51.png) 

### webUIMoveFilesFolders-moveFolders-feature-20.png
 ![webUIMoveFilesFolders-moveFolders-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIMoveFilesFolders-moveFolders-feature-20.png) 

### webUIMoveFilesFolders-moveFolders-feature-41.png
 ![webUIMoveFilesFolders-moveFolders-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIMoveFilesFolders-moveFolders-feature-41.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingAutocompletion-shareAutocompletion-feature-32.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingAutocompletion-shareAutocompletion-feature-44.png) 

### webUISharingInternalUsers-shareWithUsers-feature-57.png
 ![webUISharingInternalUsers-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsers-shareWithUsers-feature-57.png) 

### webUISharingInternalUsers-shareWithUsers-feature-58.png
 ![webUISharingInternalUsers-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsers-shareWithUsers-feature-58.png) 

### webUISharingInternalUsers-shareWithUsers-feature-59.png
 ![webUISharingInternalUsers-shareWithUsers-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsers-shareWithUsers-feature-59.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-11.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-11.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingPublicBasic-publicLinkCreate-feature-11.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-28.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingPublicBasic-publicLinkCreate-feature-28.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png) 

### webUITrashbinDelete-trashbinDelete-feature-29.png
 ![webUITrashbinDelete-trashbinDelete-feature-29.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUITrashbinDelete-trashbinDelete-feature-29.png) 

### webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png
 ![webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUITrashbinFilesFolders-trashbinFilesFolders-feature-23.png) 

### webUITrashbinRestore-trashbinRestore-feature-14.png
 ![webUITrashbinRestore-trashbinRestore-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUITrashbinRestore-trashbinRestore-feature-14.png) 

### webUITrashbinRestore-trashbinRestore-feature-46.png
 ![webUITrashbinRestore-trashbinRestore-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUITrashbinRestore-trashbinRestore-feature-46.png) 

### webUIUpload-upload-feature-15.png
 ![webUIUpload-upload-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-15.png) 

### webUIUpload-upload-feature-22.png
 ![webUIUpload-upload-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-22.png) 

### webUIUpload-upload-feature-34.png
 ![webUIUpload-upload-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-34.png) 

### webUIUpload-upload-feature-48.png
 ![webUIUpload-upload-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-48.png) 

### webUIUpload-upload-feature-65.png
 ![webUIUpload-upload-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-65.png) 

### webUIUpload-upload-feature-89.png
 ![webUIUpload-upload-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-89.png) 

### webUIUpload-upload-feature-98.png
 ![webUIUpload-upload-feature-98.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-upload-feature-98.png) 

### webUIUpload-uploadEdgecases-feature-48.png
 ![webUIUpload-uploadEdgecases-feature-48.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-uploadEdgecases-feature-48.png) 

### webUIUpload-uploadEdgecases-feature-49.png
 ![webUIUpload-uploadEdgecases-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-uploadEdgecases-feature-49.png) 

### webUIUpload-uploadEdgecases-feature-50.png
 ![webUIUpload-uploadEdgecases-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-uploadEdgecases-feature-50.png) 

### webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png
 ![webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIUpload-uploadFileGreaterThanQuotaSize-feature-12.png) 


</p></details>

2021-05-24 03:37 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15609/

<p>


### webUICreateFilesFolders-createFolderEdgeCases-feature-60.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUICreateFilesFolders-createFolderEdgeCases-feature-60.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-61.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUICreateFilesFolders-createFolderEdgeCases-feature-61.png) 

### webUICreateFilesFolders-createFolderEdgeCases-feature-62.png
 ![webUICreateFilesFolders-createFolderEdgeCases-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUICreateFilesFolders-createFolderEdgeCases-feature-62.png) 

### webUICreateFilesFolders-createFolders-feature-12.png
 ![webUICreateFilesFolders-createFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUICreateFilesFolders-createFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-55.png
 ![webUIFavorites-unfavoriteFile-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFavorites-unfavoriteFile-feature-55.png) 

### webUIFilesCopy-copy-feature-10.png
 ![webUIFilesCopy-copy-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesCopy-copy-feature-10.png) 

### webUIFilesCopy-copy-feature-36.png
 ![webUIFilesCopy-copy-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesCopy-copy-feature-36.png) 

### webUIFilesSearch-search-feature-27.png
 ![webUIFilesSearch-search-feature-27.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIFilesSearch-search-feature-27.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-9.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-9.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIPrivateLinks-accessingPrivateLinks-feature-9.png) 

### webUIRenameFiles-renameFiles-feature-22.png
 ![webUIRenameFiles-renameFiles-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-22.png) 

### webUIRenameFiles-renameFiles-feature-23.png
 ![webUIRenameFiles-renameFiles-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-23.png) 

### webUIRenameFiles-renameFiles-feature-24.png
 ![webUIRenameFiles-renameFiles-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-24.png) 

### webUIRenameFiles-renameFiles-feature-25.png
 ![webUIRenameFiles-renameFiles-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-25.png) 

### webUIRenameFiles-renameFiles-feature-26.png
 ![webUIRenameFiles-renameFiles-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-26.png) 

### webUIRenameFiles-renameFiles-feature-43.png
 ![webUIRenameFiles-renameFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRenameFiles-renameFiles-feature-43.png) 

### webUIRestrictSharing-disableSharing-feature-16.png
 ![webUIRestrictSharing-disableSharing-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-disableSharing-feature-16.png) 

### webUIRestrictSharing-restrictReSharing-feature-23.png
 ![webUIRestrictSharing-restrictReSharing-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-restrictReSharing-feature-23.png) 

### webUIRestrictSharing-restrictReSharing-feature-42.png
 ![webUIRestrictSharing-restrictReSharing-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-restrictReSharing-feature-42.png) 

### webUIRestrictSharing-restrictSharing-feature-31.png
 ![webUIRestrictSharing-restrictSharing-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-restrictSharing-feature-31.png) 

### webUIRestrictSharing-restrictSharing-feature-40.png
 ![webUIRestrictSharing-restrictSharing-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-restrictSharing-feature-40.png) 

### webUIRestrictSharing-restrictSharing-feature-56.png
 ![webUIRestrictSharing-restrictSharing-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUIRestrictSharing-restrictSharing-feature-56.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-50.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingAcceptSharesToRoot-acceptShares-feature-50.png) 

### webUISharingAcceptSharesToRoot-acceptShares-feature-72.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15609/webUISharingAcceptSharesToRoot-acceptShares-feature-72.png) 


</p></details>

2021-05-24 05:32 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFilesList</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15612/

<p>


### webUIFilesList-fileList-feature-15.png
 ![webUIFilesList-fileList-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-15.png) 

### webUIFilesList-fileList-feature-22.png
 ![webUIFilesList-fileList-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-22.png) 

### webUIFilesList-fileList-feature-28.png
 ![webUIFilesList-fileList-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-28.png) 

### webUIFilesList-fileList-feature-33.png
 ![webUIFilesList-fileList-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-33.png) 

### webUIFilesList-fileList-feature-41.png
 ![webUIFilesList-fileList-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-41.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-46.png) 

### webUIFilesList-fileList-feature-51.png
 ![webUIFilesList-fileList-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-51.png) 

### webUIFilesList-fileList-feature-60.png
 ![webUIFilesList-fileList-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-60.png) 

### webUIFilesList-fileList-feature-73.png
 ![webUIFilesList-fileList-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-fileList-feature-73.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-sort-feature-51.png) 

### webUIFilesList-sort-feature-72.png
 ![webUIFilesList-sort-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15612/webUIFilesList-sort-feature-72.png) 


</p></details>

2021-05-24 07:07 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15618/

<p>


### webUIMoveFilesFolders-moveFiles-feature-105.png
 ![webUIMoveFilesFolders-moveFiles-feature-105.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-105.png) 

### webUIMoveFilesFolders-moveFiles-feature-115.png
 ![webUIMoveFilesFolders-moveFiles-feature-115.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-115.png) 

### webUIMoveFilesFolders-moveFiles-feature-12.png
 ![webUIMoveFilesFolders-moveFiles-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-12.png) 

### webUIMoveFilesFolders-moveFiles-feature-140.png
 ![webUIMoveFilesFolders-moveFiles-feature-140.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-140.png) 

### webUIMoveFilesFolders-moveFiles-feature-20.png
 ![webUIMoveFilesFolders-moveFiles-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-20.png) 

### webUIMoveFilesFolders-moveFiles-feature-43.png
 ![webUIMoveFilesFolders-moveFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-43.png) 

### webUIMoveFilesFolders-moveFiles-feature-51.png
 ![webUIMoveFilesFolders-moveFiles-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-51.png) 

### webUIMoveFilesFolders-moveFiles-feature-79.png
 ![webUIMoveFilesFolders-moveFiles-feature-79.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-79.png) 

### webUIMoveFilesFolders-moveFiles-feature-81.png
 ![webUIMoveFilesFolders-moveFiles-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-81.png) 

### webUIMoveFilesFolders-moveFiles-feature-82.png
 ![webUIMoveFilesFolders-moveFiles-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-82.png) 

### webUIMoveFilesFolders-moveFiles-feature-85.png
 ![webUIMoveFilesFolders-moveFiles-feature-85.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-85.png) 

### webUIMoveFilesFolders-moveFiles-feature-97.png
 ![webUIMoveFilesFolders-moveFiles-feature-97.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFiles-feature-97.png) 

### webUIMoveFilesFolders-moveFolders-feature-12.png
 ![webUIMoveFilesFolders-moveFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-12.png) 

### webUIMoveFilesFolders-moveFolders-feature-20.png
 ![webUIMoveFilesFolders-moveFolders-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-20.png) 

### webUIMoveFilesFolders-moveFolders-feature-33.png
 ![webUIMoveFilesFolders-moveFolders-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-33.png) 

### webUIMoveFilesFolders-moveFolders-feature-41.png
 ![webUIMoveFilesFolders-moveFolders-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-41.png) 

### webUIMoveFilesFolders-moveFolders-feature-66.png
 ![webUIMoveFilesFolders-moveFolders-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-66.png) 

### webUIMoveFilesFolders-moveFolders-feature-68.png
 ![webUIMoveFilesFolders-moveFolders-feature-68.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-68.png) 

### webUIMoveFilesFolders-moveFolders-feature-69.png
 ![webUIMoveFilesFolders-moveFolders-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-69.png) 

### webUIMoveFilesFolders-moveFolders-feature-72.png
 ![webUIMoveFilesFolders-moveFolders-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-72.png) 

### webUIMoveFilesFolders-moveFolders-feature-81.png
 ![webUIMoveFilesFolders-moveFolders-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-81.png) 

### webUIMoveFilesFolders-moveFolders-feature-88.png
 ![webUIMoveFilesFolders-moveFolders-feature-88.png](https://cache.owncloud.com/owncloud/web/screenshots/15618/webUIMoveFilesFolders-moveFolders-feature-88.png) 


</p></details>

2021-05-26 09:52 UTC, kiranparajuli589 commented
lgtm 👍🏼

2021-05-26 11:28 UTC, individual-it reviewed
Looks good, some comments:

- should we use `in the server` or `on the server` as in the desktop client?  CC @phil-davis 
- documentation about starting selenium needs to be refactored, because now selenium will be started from the docker-compose file
- need to be tested on Mac, maybe by @LukasHirt ?

2021-05-26 11:29 UTC, LukasHirt commented
> need to be tested on Mac, maybe by @LukasHirt ?

I could try it tomorrow if that's enough

2021-05-27 04:12 UTC, phil-davis commented on docs/testing.md
> +  Or you can run the test middleware directy using docker you can use the following command. Make sure to set the env variables accordingly.
```suggestion
  Or you can run the test middleware directly. You can use the following docker command. Make sure to set the env variables accordingly.
```

2021-05-27 04:13 UTC, phil-davis commented
> should we use `in the server` or `on the server` as in the desktop client?

Either word works OK. If we used `on the server` elsewhere, then we should use it here to be consistent.

2021-05-27 04:51 UTC, dpakach commented on .drone.star
> +        "image": "dpakach/owncloud-test-middleware",
Yes, this one is just for the time being so that we can test it

2021-05-28 10:34 UTC, LukasHirt commented
@dpakach For MacOS we need to have published ports for the selenium and middleware containers. Currently, if I run the docker-compose I have no way of reaching either of them.

2021-05-31 07:16 UTC, dpakach commented
@LukasHirt I have updated the instructions so I think it should work for macOS. Can you try again?

If it still fails can you try once by removing these lines
https://github.com/owncloud/web/pull/5136/files#diff-929940edb8bb2e8a57c6a2637b9529812dc851c6b4f1aff6f1cf8ef367c00f1eR6
https://github.com/owncloud/web/pull/5136/files#diff-929940edb8bb2e8a57c6a2637b9529812dc851c6b4f1aff6f1cf8ef367c00f1eR17

2021-05-31 08:27 UTC, LukasHirt commented
@dpakach facing two issues now:

- having the `network_mode: 'host'` in the docker compose fails on Mac because it doesn't support using that mode and port publishing at the same time 🙈 
- removing the network mode and getting the containers to run and then running tests results in `FetchError: request to http://host.docker.internal:3000/init failed, reason: connect ECONNREFUSED 127.0.0.1:3000`. Same error also for `/cleanup`

2021-06-08 15:02 UTC, LukasHirt commented
@dpakach Tried now with `MIDDLEWARE_HOST` set to `http://localhost:3000` and still am getting error. This time a different one though.

![Screenshot 2021-06-08 at 17 01 06](https://user-images.githubusercontent.com/25989331/121209546-345d6280-c87b-11eb-8b7b-c5d632fe6554.png)

2021-06-09 03:13 UTC, dpakach commented
@LukasHirt can you check the logs for the middleware if there is any hint why it's failing.
you can check that with `docker-compose logs middleware`

2021-06-09 07:36 UTC, LukasHirt commented
> can you check the logs for the middleware and see if there is any hint why it's failing.
you can check that with docker-compose logs middleware

@dpakach Nothing to see there. Only two messages about the middleware being started but nothing else.

2021-07-01 15:34 UTC, butonic commented
@dpakach @LukasHirt @saw-jan what are the next steps?

2021-07-01 16:52 UTC, LukasHirt commented
IMHO if it works on linux it would still be possible to run tests without it on other platforms I would say let's move forward and take care of other platforms in separate PRs.

2021-08-25 13:03 UTC, kulmann commented
Is this still relevant / being worked on?

2021-09-02 08:05 UTC, pascalwengerter commented
> Is this still relevant / being worked on?

@dpakach any feedback? :)

2021-09-02 12:06 UTC, dpakach commented
> > Is this still relevant / being worked on?
> 
> @dpakach any feedback? :)

@pascalwengerter sorry I missed the message. since we have the new docker setup for running the tests, I'm trying to plug the middleware into that setup and with that it will probably work on mac systems as well. I'll try to work this out in coming days. 👍🏼

2021-09-07 05:45 UTC, ownclouders commented
Results for <strong>oCISFilesList</strong> https://drone.owncloud.com/owncloud/web/18904/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-09-22 11:48 UTC, ownclouders commented
Results for <strong>oCISFilesList</strong> https://drone.owncloud.com/owncloud/web/19180/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-10-21 10:23 UTC, dpakach commented
> the concept looks good for me. Do we want to delete all the steps out of web in this PR or in a separate PR?

That will be a big PR so should be done in small parts IMO. But first we need to verify this works in mac.

2021-11-15 16:31 UTC, ScharfViktor commented
> > the concept looks good for me. Do we want to delete all the steps out of web in this PR or in a separate PR?
> 
> That will be a big PR so should be done in small parts IMO. But first we need to verify this works in mac.

@dpakach I can check how it works on mac. Please do a rebase

2021-11-17 03:53 UTC, dpakach commented
@ScharfViktor thanks a lot. I have rebased it please have a look.

2021-11-17 15:14 UTC, ScharfViktor commented
### run tests in ocis
docker with macOC Big Sure 11.4 

`docker-compose up ocis selenium vnc middleware-ocis`
`yarn test:acceptance:ocis features/webUIFilesList/fileList.feature`
test run was successful, the test data was created successfully with the middleware 
log middleware-ocis: 
<img width="1033" alt="Screen Shot 2021-11-17 at 3 41 42 PM" src="https://user-images.githubusercontent.com/84779829/142223346-86614fd2-94b9-413b-90c0-921f3685dd20.png">

### run tests in oc10
docker with macOC Big Sure 11.4 
`docker-compose up oc10 selenium vnc middleware-oc10`
`yarn test:acceptance:oc10 features/webUIFilesList/fileList.feature`
the test data was created successfully with the middleware, but test was failed:
`✖ And user "Alice" has logged in using the webUI # stepDefinitions/loginContext.js:70
       Timed out while waiting for element <button[type=submit]> `
![image](https://user-images.githubusercontent.com/84779829/142227200-8706ace8-3f4f-410c-9976-5be577872b70.png)
log middleware-oc10: 
![image](https://user-images.githubusercontent.com/84779829/142227363-c38a70d4-d935-416b-80d0-b0e54ade968e.png)

2021-11-19 04:00 UTC, dpakach commented
@ScharfViktor thanks a lot for checking this. Before running the tests you should also need to build and bundle web with 
`yarn build:w` before you start the docker setup.
But since it worked on ocis it should also work with oc10.

2021-11-19 06:03 UTC, phil-davis commented on .drone.star
> +        "image": "dpakach/owncloud-test-middleware",
what do we do about this now?
"copy" into owncloud-ci?

2021-11-22 04:57 UTC, individual-it requested changes
the middleware docker should be on owncloud-ci, the rest looks good

2021-11-23 14:20 UTC, pascalwengerter commented on docker-compose.yml
> +      MIDDLEWARE_PORT: 3000
Can we use different ports here so we can start both the ocis-middleware and the oc10-middleware at the same time? :)

2021-11-29 11:01 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/20516/17/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

2021-12-02 08:37 UTC, individual-it approved these changes

2021-12-02 08:51 UTC, merged