[Tests-Only]Adjust steps that try to edit public link shares
owncloud/web pull request #5137
Opened 2021-05-21 12:03 UTC by jasson99

## Description
This PR adjusts steps that try to edit public link shares.

## Related Issue
- https://github.com/owncloud/web/issues/4933

## How Has This Been Tested?
- CI

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-05-24 05:26 UTC, dpakach reviewed
lgtm 👍🏼

2021-05-24 07:51 UTC, individual-it requested changes

2021-05-24 07:51 UTC, individual-it commented on tests/acceptance/stepDefinitions/publicLinkContext.js
> +    await editPublicLink(linkName, resource, dataTable)
if this is a `tries` step it should fail if it does not catch any exception

2021-05-24 10:31 UTC, saw-jan commented on tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
> +const { client } = require('nightwatch-api')
is it needed?

2021-05-24 12:03 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUIMoveFilesFolders-moveFiles-feature-43.png
 ![webUIMoveFilesFolders-moveFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMoveFilesFolders-moveFiles-feature-43.png) 

### webUIMoveFilesFolders-moveFiles-feature-97.png
 ![webUIMoveFilesFolders-moveFiles-feature-97.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMoveFilesFolders-moveFiles-feature-97.png) 

### webUIMoveFilesFolders-moveFolders-feature-33.png
 ![webUIMoveFilesFolders-moveFolders-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMoveFilesFolders-moveFolders-feature-33.png) 

### webUIMoveFilesFolders-moveFolders-feature-72.png
 ![webUIMoveFilesFolders-moveFolders-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMoveFilesFolders-moveFolders-feature-72.png) 

### webUIMoveFilesFolders-moveFolders-feature-81.png
 ![webUIMoveFilesFolders-moveFolders-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMoveFilesFolders-moveFolders-feature-81.png) 


</p></details>

2021-05-24 12:03 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsEdgeCases</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-107.png
 ![webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-107.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-107.png) 

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-50.png
 ![webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-50.png) 

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-68.png
 ![webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-68.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-68.png) 

### webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-86.png
 ![webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-86.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsEdgeCases-shareWithGroupsEdgeCases-feature-86.png) 


</p></details>

2021-05-24 12:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFolderPermissionMultipleUsers</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png) 


</p></details>

2021-05-24 12:07 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-104.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-104.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-104.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-114.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-114.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-114.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-22.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-22.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-42.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-42.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-58.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-58.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-74.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-74.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-89.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-89.png) 


</p></details>

2021-05-24 12:10 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublicBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingPublicBasic-publicLinkEdit-feature-131.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-131.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-30.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-30.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-31.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-31.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-32.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-32.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-33.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-33.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-56.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-56.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-57.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-57.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-58.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-58.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-59.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicBasic-publicLinkEdit-feature-59.png) 


</p></details>

2021-05-24 12:11 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>MarkdownEditor</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUIMarkdownEditor-markdownFile-feature-12.png
 ![webUIMarkdownEditor-markdownFile-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-12.png) 

### webUIMarkdownEditor-markdownFile-feature-19.png
 ![webUIMarkdownEditor-markdownFile-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-19.png) 

### webUIMarkdownEditor-markdownFile-feature-26.png
 ![webUIMarkdownEditor-markdownFile-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-26.png) 

### webUIMarkdownEditor-markdownFile-feature-33.png
 ![webUIMarkdownEditor-markdownFile-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-33.png) 

### webUIMarkdownEditor-markdownFile-feature-39.png
 ![webUIMarkdownEditor-markdownFile-feature-39.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-39.png) 

### webUIMarkdownEditor-markdownFile-feature-44.png
 ![webUIMarkdownEditor-markdownFile-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-44.png) 

### webUIMarkdownEditor-markdownFile-feature-49.png
 ![webUIMarkdownEditor-markdownFile-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-49.png) 

### webUIMarkdownEditor-markdownFile-feature-62.png
 ![webUIMarkdownEditor-markdownFile-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-62.png) 

### webUIMarkdownEditor-markdownFile-feature-63.png
 ![webUIMarkdownEditor-markdownFile-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-63.png) 

### webUIMarkdownEditor-markdownFile-feature-71.png
 ![webUIMarkdownEditor-markdownFile-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-71.png) 

### webUIMarkdownEditor-markdownFile-feature-72.png
 ![webUIMarkdownEditor-markdownFile-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-72.png) 

### webUIMarkdownEditor-markdownFile-feature-73.png
 ![webUIMarkdownEditor-markdownFile-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-73.png) 

### webUIMarkdownEditor-markdownFile-feature-74.png
 ![webUIMarkdownEditor-markdownFile-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-74.png) 

### webUIMarkdownEditor-markdownFile-feature-75.png
 ![webUIMarkdownEditor-markdownFile-feature-75.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIMarkdownEditor-markdownFile-feature-75.png) 


</p></details>

2021-05-24 12:13 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Favorites</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUIFavorites-favoritesFile-feature-110.png
 ![webUIFavorites-favoritesFile-feature-110.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-110.png) 

### webUIFavorites-favoritesFile-feature-131.png
 ![webUIFavorites-favoritesFile-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-131.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-favoritesFile-feature-30.png
 ![webUIFavorites-favoritesFile-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-30.png) 

### webUIFavorites-favoritesFile-feature-46.png
 ![webUIFavorites-favoritesFile-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-46.png) 

### webUIFavorites-favoritesFile-feature-58.png
 ![webUIFavorites-favoritesFile-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-58.png) 

### webUIFavorites-favoritesFile-feature-65.png
 ![webUIFavorites-favoritesFile-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-65.png) 

### webUIFavorites-favoritesFile-feature-74.png
 ![webUIFavorites-favoritesFile-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-74.png) 

### webUIFavorites-favoritesFile-feature-80.png
 ![webUIFavorites-favoritesFile-feature-80.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-80.png) 

### webUIFavorites-favoritesFile-feature-85.png
 ![webUIFavorites-favoritesFile-feature-85.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-favoritesFile-feature-85.png) 

### webUIFavorites-unfavoriteFile-feature-104.png
 ![webUIFavorites-unfavoriteFile-feature-104.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-104.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-34.png
 ![webUIFavorites-unfavoriteFile-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-34.png) 

### webUIFavorites-unfavoriteFile-feature-55.png
 ![webUIFavorites-unfavoriteFile-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-55.png) 

### webUIFavorites-unfavoriteFile-feature-72.png
 ![webUIFavorites-unfavoriteFile-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-72.png) 

### webUIFavorites-unfavoriteFile-feature-89.png
 ![webUIFavorites-unfavoriteFile-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUIFavorites-unfavoriteFile-feature-89.png) 


</p></details>

2021-05-24 12:14 UTC, individual-it approved these changes

2021-05-24 12:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png) 


</p></details>

2021-05-24 12:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-100.png
 ![webUISharingInternalGroups-shareWithGroups-feature-100.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-100.png) 

### webUISharingInternalGroups-shareWithGroups-feature-182.png
 ![webUISharingInternalGroups-shareWithGroups-feature-182.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-182.png) 

### webUISharingInternalGroups-shareWithGroups-feature-19.png
 ![webUISharingInternalGroups-shareWithGroups-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-19.png) 

### webUISharingInternalGroups-shareWithGroups-feature-196.png
 ![webUISharingInternalGroups-shareWithGroups-feature-196.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-196.png) 

### webUISharingInternalGroups-shareWithGroups-feature-216.png
 ![webUISharingInternalGroups-shareWithGroups-feature-216.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-216.png) 

### webUISharingInternalGroups-shareWithGroups-feature-228.png
 ![webUISharingInternalGroups-shareWithGroups-feature-228.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-228.png) 

### webUISharingInternalGroups-shareWithGroups-feature-245.png
 ![webUISharingInternalGroups-shareWithGroups-feature-245.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-245.png) 

### webUISharingInternalGroups-shareWithGroups-feature-260.png
 ![webUISharingInternalGroups-shareWithGroups-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-260.png) 

### webUISharingInternalGroups-shareWithGroups-feature-271.png
 ![webUISharingInternalGroups-shareWithGroups-feature-271.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-271.png) 

### webUISharingInternalGroups-shareWithGroups-feature-293.png
 ![webUISharingInternalGroups-shareWithGroups-feature-293.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-293.png) 

### webUISharingInternalGroups-shareWithGroups-feature-324.png
 ![webUISharingInternalGroups-shareWithGroups-feature-324.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-324.png) 

### webUISharingInternalGroups-shareWithGroups-feature-325.png
 ![webUISharingInternalGroups-shareWithGroups-feature-325.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-325.png) 

### webUISharingInternalGroups-shareWithGroups-feature-349.png
 ![webUISharingInternalGroups-shareWithGroups-feature-349.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-349.png) 

### webUISharingInternalGroups-shareWithGroups-feature-350.png
 ![webUISharingInternalGroups-shareWithGroups-feature-350.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-350.png) 

### webUISharingInternalGroups-shareWithGroups-feature-72.png
 ![webUISharingInternalGroups-shareWithGroups-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-72.png) 

### webUISharingInternalGroups-shareWithGroups-feature-73.png
 ![webUISharingInternalGroups-shareWithGroups-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-73.png) 

### webUISharingInternalGroups-shareWithGroups-feature-74.png
 ![webUISharingInternalGroups-shareWithGroups-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingInternalGroups-shareWithGroups-feature-74.png) 


</p></details>

2021-05-24 12:21 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublicManagement</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15623/

<p>


### webUISharingPublicManagement-publicLinkIndicator-feature-110.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-110.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-110.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-12.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-12.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-27.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-27.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-27.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-37.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-37.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-37.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-47.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-47.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-47.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-64.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-64.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-81.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-81.png) 

### webUISharingPublicManagement-publicLinkIndicator-feature-98.png
 ![webUISharingPublicManagement-publicLinkIndicator-feature-98.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-publicLinkIndicator-feature-98.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-102.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-102.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-102.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-12.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-12.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-120.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-120.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-120.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-131.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-131.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-146.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-146.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-146.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-164.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-164.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-164.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-171.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-171.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-171.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-19.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-19.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-201.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-201.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-201.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-25.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-25.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-64.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-64.png) 

### webUISharingPublicManagement-shareByPublicLink-feature-90.png
 ![webUISharingPublicManagement-shareByPublicLink-feature-90.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-shareByPublicLink-feature-90.png) 

### webUISharingPublicManagement-sharingPublicSession-feature-10.png
 ![webUISharingPublicManagement-sharingPublicSession-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-sharingPublicSession-feature-10.png) 

### webUISharingPublicManagement-sharingPublicSession-feature-20.png
 ![webUISharingPublicManagement-sharingPublicSession-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-sharingPublicSession-feature-20.png) 

### webUISharingPublicManagement-sharingPublicSession-feature-31.png
 ![webUISharingPublicManagement-sharingPublicSession-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-sharingPublicSession-feature-31.png) 

### webUISharingPublicManagement-sharingPublicSession-feature-41.png
 ![webUISharingPublicManagement-sharingPublicSession-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-sharingPublicSession-feature-41.png) 

### webUISharingPublicManagement-sharingPublicSession-feature-54.png
 ![webUISharingPublicManagement-sharingPublicSession-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15623/webUISharingPublicManagement-sharingPublicSession-feature-54.png) 


</p></details>

2021-05-25 02:44 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15631/

<p>


### webUIMoveFilesFolders-moveFiles-feature-43.png
 ![webUIMoveFilesFolders-moveFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUIMoveFilesFolders-moveFiles-feature-43.png) 

### webUIMoveFilesFolders-moveFiles-feature-97.png
 ![webUIMoveFilesFolders-moveFiles-feature-97.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUIMoveFilesFolders-moveFiles-feature-97.png) 

### webUIMoveFilesFolders-moveFolders-feature-33.png
 ![webUIMoveFilesFolders-moveFolders-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUIMoveFilesFolders-moveFolders-feature-33.png) 

### webUIMoveFilesFolders-moveFolders-feature-72.png
 ![webUIMoveFilesFolders-moveFolders-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUIMoveFilesFolders-moveFolders-feature-72.png) 

### webUIMoveFilesFolders-moveFolders-feature-81.png
 ![webUIMoveFilesFolders-moveFolders-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUIMoveFilesFolders-moveFolders-feature-81.png) 


</p></details>

2021-05-25 02:48 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublicBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15631/

<p>


### webUISharingPublicBasic-publicLinkEdit-feature-131.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-131.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-30.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-30.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-31.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-31.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-32.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-32.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-33.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-33.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-56.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-56.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-57.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-57.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-58.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-58.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-59.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15631/webUISharingPublicBasic-publicLinkEdit-feature-59.png) 


</p></details>

2021-05-25 03:11 UTC, individual-it approved these changes

2021-05-25 06:06 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingPublicBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15634/

<p>


### webUISharingPublicBasic-publicLinkEdit-feature-131.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-131.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-30.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-30.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-31.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-31.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-32.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-32.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-33.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-33.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-56.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-56.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-57.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-57.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-58.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-58.png) 

### webUISharingPublicBasic-publicLinkEdit-feature-59.png
 ![webUISharingPublicBasic-publicLinkEdit-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15634/webUISharingPublicBasic-publicLinkEdit-feature-59.png) 


</p></details>

2021-05-25 07:41 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFilePermissionsGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15638/

<p>


### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png) 


</p></details>

2021-05-25 07:43 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>TrashbinRestore</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15638/

<p>


### webUITrashbinRestore-trashbinRestore-feature-138.png
 ![webUITrashbinRestore-trashbinRestore-feature-138.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-138.png) 

### webUITrashbinRestore-trashbinRestore-feature-14.png
 ![webUITrashbinRestore-trashbinRestore-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-14.png) 

### webUITrashbinRestore-trashbinRestore-feature-181.png
 ![webUITrashbinRestore-trashbinRestore-feature-181.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-181.png) 

### webUITrashbinRestore-trashbinRestore-feature-222.png
 ![webUITrashbinRestore-trashbinRestore-feature-222.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-222.png) 

### webUITrashbinRestore-trashbinRestore-feature-241.png
 ![webUITrashbinRestore-trashbinRestore-feature-241.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-241.png) 

### webUITrashbinRestore-trashbinRestore-feature-260.png
 ![webUITrashbinRestore-trashbinRestore-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-260.png) 

### webUITrashbinRestore-trashbinRestore-feature-30.png
 ![webUITrashbinRestore-trashbinRestore-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-30.png) 

### webUITrashbinRestore-trashbinRestore-feature-46.png
 ![webUITrashbinRestore-trashbinRestore-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-46.png) 

### webUITrashbinRestore-trashbinRestore-feature-84.png
 ![webUITrashbinRestore-trashbinRestore-feature-84.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUITrashbinRestore-trashbinRestore-feature-84.png) 


</p></details>

2021-05-25 07:45 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>RestrictSharing</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15638/

<p>


### webUIRestrictSharing-disableSharing-feature-16.png
 ![webUIRestrictSharing-disableSharing-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-disableSharing-feature-16.png) 

### webUIRestrictSharing-disableSharing-feature-22.png
 ![webUIRestrictSharing-disableSharing-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-disableSharing-feature-22.png) 

### webUIRestrictSharing-disableSharing-feature-32.png
 ![webUIRestrictSharing-disableSharing-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-disableSharing-feature-32.png) 

### webUIRestrictSharing-disableSharing-feature-49.png
 ![webUIRestrictSharing-disableSharing-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-disableSharing-feature-49.png) 

### webUIRestrictSharing-restrictReSharing-feature-23.png
 ![webUIRestrictSharing-restrictReSharing-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictReSharing-feature-23.png) 

### webUIRestrictSharing-restrictReSharing-feature-42.png
 ![webUIRestrictSharing-restrictReSharing-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictReSharing-feature-42.png) 

### webUIRestrictSharing-restrictSharing-feature-31.png
 ![webUIRestrictSharing-restrictSharing-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictSharing-feature-31.png) 

### webUIRestrictSharing-restrictSharing-feature-40.png
 ![webUIRestrictSharing-restrictSharing-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictSharing-feature-40.png) 

### webUIRestrictSharing-restrictSharing-feature-49.png
 ![webUIRestrictSharing-restrictSharing-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictSharing-feature-49.png) 

### webUIRestrictSharing-restrictSharing-feature-56.png
 ![webUIRestrictSharing-restrictSharing-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIRestrictSharing-restrictSharing-feature-56.png) 


</p></details>

2021-05-25 07:53 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15638/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png) 


</p></details>

2021-05-25 08:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15638/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
 ![webUIFilesDetails-fileDetails-feature-116.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-116.png) 

### webUIFilesDetails-fileDetails-feature-134.png
 ![webUIFilesDetails-fileDetails-feature-134.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-134.png) 

### webUIFilesDetails-fileDetails-feature-138.png
 ![webUIFilesDetails-fileDetails-feature-138.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-138.png) 

### webUIFilesDetails-fileDetails-feature-14.png
 ![webUIFilesDetails-fileDetails-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-14.png) 

### webUIFilesDetails-fileDetails-feature-161.png
 ![webUIFilesDetails-fileDetails-feature-161.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-161.png) 

### webUIFilesDetails-fileDetails-feature-170.png
 ![webUIFilesDetails-fileDetails-feature-170.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-170.png) 

### webUIFilesDetails-fileDetails-feature-25.png
 ![webUIFilesDetails-fileDetails-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-25.png) 

### webUIFilesDetails-fileDetails-feature-38.png
 ![webUIFilesDetails-fileDetails-feature-38.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-38.png) 

### webUIFilesDetails-fileDetails-feature-51.png
 ![webUIFilesDetails-fileDetails-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-51.png) 

### webUIFilesDetails-fileDetails-feature-82.png
 ![webUIFilesDetails-fileDetails-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-82.png) 

### webUIFilesDetails-fileDetails-feature-99.png
 ![webUIFilesDetails-fileDetails-feature-99.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesDetails-fileDetails-feature-99.png) 

### webUIFilesList-fileList-feature-15.png
 ![webUIFilesList-fileList-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-15.png) 

### webUIFilesList-fileList-feature-22.png
 ![webUIFilesList-fileList-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-22.png) 

### webUIFilesList-fileList-feature-28.png
 ![webUIFilesList-fileList-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-28.png) 

### webUIFilesList-fileList-feature-33.png
 ![webUIFilesList-fileList-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-33.png) 

### webUIFilesList-fileList-feature-41.png
 ![webUIFilesList-fileList-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-41.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-46.png) 

### webUIFilesList-fileList-feature-51.png
 ![webUIFilesList-fileList-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-51.png) 

### webUIFilesList-fileList-feature-60.png
 ![webUIFilesList-fileList-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-60.png) 

### webUIFilesList-fileList-feature-73.png
 ![webUIFilesList-fileList-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-fileList-feature-73.png) 

### webUIFilesList-sort-feature-31.png
 ![webUIFilesList-sort-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-sort-feature-31.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-sort-feature-51.png) 

### webUIFilesList-sort-feature-72.png
 ![webUIFilesList-sort-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesList-sort-feature-72.png) 

### webUIFilesSearch-search-feature-103.png
 ![webUIFilesSearch-search-feature-103.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-103.png) 

### webUIFilesSearch-search-feature-113.png
 ![webUIFilesSearch-search-feature-113.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-113.png) 

### webUIFilesSearch-search-feature-122.png
 ![webUIFilesSearch-search-feature-122.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-122.png) 

### webUIFilesSearch-search-feature-153.png
 ![webUIFilesSearch-search-feature-153.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-153.png) 

### webUIFilesSearch-search-feature-165.png
 ![webUIFilesSearch-search-feature-165.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-165.png) 

### webUIFilesSearch-search-feature-175.png
 ![webUIFilesSearch-search-feature-175.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-175.png) 

### webUIFilesSearch-search-feature-184.png
 ![webUIFilesSearch-search-feature-184.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-184.png) 

### webUIFilesSearch-search-feature-27.png
 ![webUIFilesSearch-search-feature-27.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-27.png) 

### webUIFilesSearch-search-feature-38.png
 ![webUIFilesSearch-search-feature-38.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-38.png) 

### webUIFilesSearch-search-feature-50.png
 ![webUIFilesSearch-search-feature-50.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-50.png) 

### webUIFilesSearch-search-feature-95.png
 ![webUIFilesSearch-search-feature-95.png](https://cache.owncloud.com/owncloud/web/screenshots/15638/webUIFilesSearch-search-feature-95.png) 


</p></details>

2021-05-25 08:23 UTC, jasson99 commented on tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
> +const { client } = require('nightwatch-api')
yes

2021-05-25 08:40 UTC, jasson99 commented on tests/acceptance/pageObjects/FilesPageElement/publicLinksDialog.js
> +const { client } = require('nightwatch-api')
no more now

2021-05-25 09:37 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRootBlacklisted</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png) 


</p></details>

2021-05-25 09:37 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFilePermissionsGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png) 


</p></details>

2021-05-25 09:39 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersBlacklisted</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png) 


</p></details>

2021-05-25 09:40 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-100.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-100.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-100.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-121.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-121.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-121.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-139.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-139.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-139.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-155.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-155.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-155.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-165.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-165.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-165.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-80.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-80.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-80.png) 


</p></details>

2021-05-25 09:41 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRootSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-108.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-108.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-108.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-15.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-15.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-35.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-35.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-69.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-69.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-84.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-84.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-84.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-98.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-98.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-98.png) 


</p></details>

2021-05-25 09:44 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>MarkdownEditor</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUIMarkdownEditor-markdownFile-feature-12.png
 ![webUIMarkdownEditor-markdownFile-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-12.png) 

### webUIMarkdownEditor-markdownFile-feature-19.png
 ![webUIMarkdownEditor-markdownFile-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-19.png) 

### webUIMarkdownEditor-markdownFile-feature-26.png
 ![webUIMarkdownEditor-markdownFile-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-26.png) 

### webUIMarkdownEditor-markdownFile-feature-33.png
 ![webUIMarkdownEditor-markdownFile-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-33.png) 

### webUIMarkdownEditor-markdownFile-feature-39.png
 ![webUIMarkdownEditor-markdownFile-feature-39.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-39.png) 

### webUIMarkdownEditor-markdownFile-feature-44.png
 ![webUIMarkdownEditor-markdownFile-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-44.png) 

### webUIMarkdownEditor-markdownFile-feature-49.png
 ![webUIMarkdownEditor-markdownFile-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-49.png) 

### webUIMarkdownEditor-markdownFile-feature-62.png
 ![webUIMarkdownEditor-markdownFile-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-62.png) 

### webUIMarkdownEditor-markdownFile-feature-63.png
 ![webUIMarkdownEditor-markdownFile-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-63.png) 

### webUIMarkdownEditor-markdownFile-feature-71.png
 ![webUIMarkdownEditor-markdownFile-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-71.png) 

### webUIMarkdownEditor-markdownFile-feature-72.png
 ![webUIMarkdownEditor-markdownFile-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-72.png) 

### webUIMarkdownEditor-markdownFile-feature-73.png
 ![webUIMarkdownEditor-markdownFile-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-73.png) 

### webUIMarkdownEditor-markdownFile-feature-74.png
 ![webUIMarkdownEditor-markdownFile-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-74.png) 

### webUIMarkdownEditor-markdownFile-feature-75.png
 ![webUIMarkdownEditor-markdownFile-feature-75.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIMarkdownEditor-markdownFile-feature-75.png) 


</p></details>

2021-05-25 09:44 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIDelete</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUIDeleteFilesFolders-deleteFilesFolders-feature-111.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-111.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-111.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-12.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-122.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-122.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-122.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-159.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-159.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-159.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-180.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-180.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-180.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-235.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-235.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-235.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-249.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-249.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-249.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-272.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-272.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-272.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-295.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-295.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-295.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-308.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-308.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-308.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-53.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-53.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-54.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-54.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-55.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-55.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-56.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-56.png) 

### webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png
 ![webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIDeleteFilesFolders-deleteFilesFolders-feature-59.png) 


</p></details>

2021-05-25 09:49 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroups</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalGroups-shareWithGroups-feature-100.png
 ![webUISharingInternalGroups-shareWithGroups-feature-100.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-100.png) 

### webUISharingInternalGroups-shareWithGroups-feature-182.png
 ![webUISharingInternalGroups-shareWithGroups-feature-182.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-182.png) 

### webUISharingInternalGroups-shareWithGroups-feature-19.png
 ![webUISharingInternalGroups-shareWithGroups-feature-19.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-19.png) 

### webUISharingInternalGroups-shareWithGroups-feature-196.png
 ![webUISharingInternalGroups-shareWithGroups-feature-196.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-196.png) 

### webUISharingInternalGroups-shareWithGroups-feature-216.png
 ![webUISharingInternalGroups-shareWithGroups-feature-216.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-216.png) 

### webUISharingInternalGroups-shareWithGroups-feature-228.png
 ![webUISharingInternalGroups-shareWithGroups-feature-228.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-228.png) 

### webUISharingInternalGroups-shareWithGroups-feature-245.png
 ![webUISharingInternalGroups-shareWithGroups-feature-245.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-245.png) 

### webUISharingInternalGroups-shareWithGroups-feature-260.png
 ![webUISharingInternalGroups-shareWithGroups-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-260.png) 

### webUISharingInternalGroups-shareWithGroups-feature-271.png
 ![webUISharingInternalGroups-shareWithGroups-feature-271.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-271.png) 

### webUISharingInternalGroups-shareWithGroups-feature-293.png
 ![webUISharingInternalGroups-shareWithGroups-feature-293.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-293.png) 

### webUISharingInternalGroups-shareWithGroups-feature-324.png
 ![webUISharingInternalGroups-shareWithGroups-feature-324.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-324.png) 

### webUISharingInternalGroups-shareWithGroups-feature-325.png
 ![webUISharingInternalGroups-shareWithGroups-feature-325.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-325.png) 

### webUISharingInternalGroups-shareWithGroups-feature-349.png
 ![webUISharingInternalGroups-shareWithGroups-feature-349.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-349.png) 

### webUISharingInternalGroups-shareWithGroups-feature-350.png
 ![webUISharingInternalGroups-shareWithGroups-feature-350.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-350.png) 

### webUISharingInternalGroups-shareWithGroups-feature-72.png
 ![webUISharingInternalGroups-shareWithGroups-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-72.png) 

### webUISharingInternalGroups-shareWithGroups-feature-73.png
 ![webUISharingInternalGroups-shareWithGroups-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-73.png) 

### webUISharingInternalGroups-shareWithGroups-feature-74.png
 ![webUISharingInternalGroups-shareWithGroups-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroups-shareWithGroups-feature-74.png) 


</p></details>

2021-05-25 09:50 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-119.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-260.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-267.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-57.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png) 


</p></details>

2021-05-25 09:51 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsRoot</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-128.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-167.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-179.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-197.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-209.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-21.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-222.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-234.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-245.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-265.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-293.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-294.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-315.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-316.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-69.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-70.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-71.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-74.png) 

### webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png
 ![webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalGroupsToRoot-shareWithGroups-feature-95.png) 


</p></details>

2021-05-25 09:51 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersExpire</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-104.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-105.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-108.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-134.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-16.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-16.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-179.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-179.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-179.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-180.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-180.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-180.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-207.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-207.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-207.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-208.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-208.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-208.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-211.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-228.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-228.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-228.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-24.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-24.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-240.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-240.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-240.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-34.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-54.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-54.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-84.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-84.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-84.png) 

### webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-85.png
 ![webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-85.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingInternalUsersExpire-shareWithUsersExpiringShares-feature-85.png) 


</p></details>

2021-05-25 09:54 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingAutocompletion</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-115.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-115.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-115.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-128.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-128.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-128.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-141.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-141.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-141.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-154.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-154.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-154.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-168.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-168.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-168.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-32.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-32.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-44.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-56.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-56.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-66.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-66.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-76.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-76.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletion-feature-76.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-36.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-36.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-37.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-37.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-37.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-38.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-38.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-38.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-39.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-39.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-39.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-55.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-55.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-56.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-56.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-57.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-57.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-73.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-73.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-74.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-74.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-75.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-75.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-75.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-76.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-76.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUISharingAutocompletion-shareAutocompletionSpecialChars-feature-76.png) 


</p></details>

2021-05-25 09:59 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIResharing</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUIResharing1-reshareUsers-feature-107.png
 ![webUIResharing1-reshareUsers-feature-107.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-107.png) 

### webUIResharing1-reshareUsers-feature-115.png
 ![webUIResharing1-reshareUsers-feature-115.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-115.png) 

### webUIResharing1-reshareUsers-feature-124.png
 ![webUIResharing1-reshareUsers-feature-124.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-124.png) 

### webUIResharing1-reshareUsers-feature-134.png
 ![webUIResharing1-reshareUsers-feature-134.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-134.png) 

### webUIResharing1-reshareUsers-feature-145.png
 ![webUIResharing1-reshareUsers-feature-145.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-145.png) 

### webUIResharing1-reshareUsers-feature-166.png
 ![webUIResharing1-reshareUsers-feature-166.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-166.png) 

### webUIResharing1-reshareUsers-feature-18.png
 ![webUIResharing1-reshareUsers-feature-18.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-18.png) 

### webUIResharing1-reshareUsers-feature-187.png
 ![webUIResharing1-reshareUsers-feature-187.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-187.png) 

### webUIResharing1-reshareUsers-feature-198.png
 ![webUIResharing1-reshareUsers-feature-198.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-198.png) 

### webUIResharing1-reshareUsers-feature-214.png
 ![webUIResharing1-reshareUsers-feature-214.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-214.png) 

### webUIResharing1-reshareUsers-feature-230.png
 ![webUIResharing1-reshareUsers-feature-230.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-230.png) 

### webUIResharing1-reshareUsers-feature-248.png
 ![webUIResharing1-reshareUsers-feature-248.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-248.png) 

### webUIResharing1-reshareUsers-feature-260.png
 ![webUIResharing1-reshareUsers-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-260.png) 

### webUIResharing1-reshareUsers-feature-74.png
 ![webUIResharing1-reshareUsers-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing1-reshareUsers-feature-74.png) 

### webUIResharing2-reshareUsers-feature-130.png
 ![webUIResharing2-reshareUsers-feature-130.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-130.png) 

### webUIResharing2-reshareUsers-feature-131.png
 ![webUIResharing2-reshareUsers-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-131.png) 

### webUIResharing2-reshareUsers-feature-132.png
 ![webUIResharing2-reshareUsers-feature-132.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-132.png) 

### webUIResharing2-reshareUsers-feature-133.png
 ![webUIResharing2-reshareUsers-feature-133.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-133.png) 

### webUIResharing2-reshareUsers-feature-134.png
 ![webUIResharing2-reshareUsers-feature-134.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-134.png) 

### webUIResharing2-reshareUsers-feature-18.png
 ![webUIResharing2-reshareUsers-feature-18.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-18.png) 

### webUIResharing2-reshareUsers-feature-29.png
 ![webUIResharing2-reshareUsers-feature-29.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-29.png) 

### webUIResharing2-reshareUsers-feature-41.png
 ![webUIResharing2-reshareUsers-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-41.png) 

### webUIResharing2-reshareUsers-feature-69.png
 ![webUIResharing2-reshareUsers-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-69.png) 

### webUIResharing2-reshareUsers-feature-70.png
 ![webUIResharing2-reshareUsers-feature-70.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-70.png) 

### webUIResharing2-reshareUsers-feature-71.png
 ![webUIResharing2-reshareUsers-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-71.png) 

### webUIResharing2-reshareUsers-feature-72.png
 ![webUIResharing2-reshareUsers-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-72.png) 

### webUIResharing2-reshareUsers-feature-73.png
 ![webUIResharing2-reshareUsers-feature-73.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIResharing2-reshareUsers-feature-73.png) 


</p></details>

2021-05-25 10:08 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUIAccount-accountInformation-feature-10.png
 ![webUIAccount-accountInformation-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIAccount-accountInformation-feature-10.png) 

### webUIAccount-accountInformation-feature-20.png
 ![webUIAccount-accountInformation-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIAccount-accountInformation-feature-20.png) 

### webUIAccount-accountInformation-feature-34.png
 ![webUIAccount-accountInformation-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIAccount-accountInformation-feature-34.png) 

### webUIAccount-userProfile-feature-10.png
 ![webUIAccount-userProfile-feature-10.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIAccount-userProfile-feature-10.png) 

### webUIAccount-userProfile-feature-17.png
 ![webUIAccount-userProfile-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIAccount-userProfile-feature-17.png) 

### webUILogin-adminBlocksUser-feature-20.png
 ![webUILogin-adminBlocksUser-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-adminBlocksUser-feature-20.png) 

### webUILogin-oauthLogin-feature-14.png
 ![webUILogin-oauthLogin-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-14.png) 

### webUILogin-oauthLogin-feature-22.png
 ![webUILogin-oauthLogin-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-22.png) 

### webUILogin-oauthLogin-feature-29.png
 ![webUILogin-oauthLogin-feature-29.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-29.png) 

### webUILogin-oauthLogin-feature-35.png
 ![webUILogin-oauthLogin-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-35.png) 

### webUILogin-oauthLogin-feature-41.png
 ![webUILogin-oauthLogin-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-41.png) 

### webUILogin-oauthLogin-feature-49.png
 ![webUILogin-oauthLogin-feature-49.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUILogin-oauthLogin-feature-49.png) 

### webUIPreview-imageMediaViewer-feature-104.png
 ![webUIPreview-imageMediaViewer-feature-104.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-104.png) 

### webUIPreview-imageMediaViewer-feature-112.png
 ![webUIPreview-imageMediaViewer-feature-112.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-112.png) 

### webUIPreview-imageMediaViewer-feature-121.png
 ![webUIPreview-imageMediaViewer-feature-121.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-121.png) 

### webUIPreview-imageMediaViewer-feature-13.png
 ![webUIPreview-imageMediaViewer-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-13.png) 

### webUIPreview-imageMediaViewer-feature-131.png
 ![webUIPreview-imageMediaViewer-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-131.png) 

### webUIPreview-imageMediaViewer-feature-14.png
 ![webUIPreview-imageMediaViewer-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-14.png) 

### webUIPreview-imageMediaViewer-feature-140.png
 ![webUIPreview-imageMediaViewer-feature-140.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-140.png) 

### webUIPreview-imageMediaViewer-feature-149.png
 ![webUIPreview-imageMediaViewer-feature-149.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-149.png) 

### webUIPreview-imageMediaViewer-feature-15.png
 ![webUIPreview-imageMediaViewer-feature-15.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-15.png) 

### webUIPreview-imageMediaViewer-feature-158.png
 ![webUIPreview-imageMediaViewer-feature-158.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-158.png) 

### webUIPreview-imageMediaViewer-feature-17.png
 ![webUIPreview-imageMediaViewer-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-17.png) 

### webUIPreview-imageMediaViewer-feature-176.png
 ![webUIPreview-imageMediaViewer-feature-176.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-176.png) 

### webUIPreview-imageMediaViewer-feature-177.png
 ![webUIPreview-imageMediaViewer-feature-177.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-177.png) 

### webUIPreview-imageMediaViewer-feature-178.png
 ![webUIPreview-imageMediaViewer-feature-178.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-178.png) 

### webUIPreview-imageMediaViewer-feature-24.png
 ![webUIPreview-imageMediaViewer-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-24.png) 

### webUIPreview-imageMediaViewer-feature-34.png
 ![webUIPreview-imageMediaViewer-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-34.png) 

### webUIPreview-imageMediaViewer-feature-55.png
 ![webUIPreview-imageMediaViewer-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-55.png) 

### webUIPreview-imageMediaViewer-feature-56.png
 ![webUIPreview-imageMediaViewer-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-56.png) 

### webUIPreview-imageMediaViewer-feature-59.png
 ![webUIPreview-imageMediaViewer-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-59.png) 

### webUIPreview-imageMediaViewer-feature-67.png
 ![webUIPreview-imageMediaViewer-feature-67.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-67.png) 

### webUIPreview-imageMediaViewer-feature-76.png
 ![webUIPreview-imageMediaViewer-feature-76.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-76.png) 

### webUIPreview-imageMediaViewer-feature-83.png
 ![webUIPreview-imageMediaViewer-feature-83.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-83.png) 

### webUIPreview-imageMediaViewer-feature-90.png
 ![webUIPreview-imageMediaViewer-feature-90.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-90.png) 

### webUIPreview-imageMediaViewer-feature-97.png
 ![webUIPreview-imageMediaViewer-feature-97.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPreview-imageMediaViewer-feature-97.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-25.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIPrivateLinks-accessingPrivateLinks-feature-25.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-34.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-34.png](https://cache.owncloud. [...]

2021-05-25 10:14 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIRename</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/15646/

<p>


### webUIRenameFiles-renameFiles-feature-117.png
 ![webUIRenameFiles-renameFiles-feature-117.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-117.png) 

### webUIRenameFiles-renameFiles-feature-118.png
 ![webUIRenameFiles-renameFiles-feature-118.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-118.png) 

### webUIRenameFiles-renameFiles-feature-119.png
 ![webUIRenameFiles-renameFiles-feature-119.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-119.png) 

### webUIRenameFiles-renameFiles-feature-138.png
 ![webUIRenameFiles-renameFiles-feature-138.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-138.png) 

### webUIRenameFiles-renameFiles-feature-139.png
 ![webUIRenameFiles-renameFiles-feature-139.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-139.png) 

### webUIRenameFiles-renameFiles-feature-143.png
 ![webUIRenameFiles-renameFiles-feature-143.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-143.png) 

### webUIRenameFiles-renameFiles-feature-151.png
 ![webUIRenameFiles-renameFiles-feature-151.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-151.png) 

### webUIRenameFiles-renameFiles-feature-157.png
 ![webUIRenameFiles-renameFiles-feature-157.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-157.png) 

### webUIRenameFiles-renameFiles-feature-163.png
 ![webUIRenameFiles-renameFiles-feature-163.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-163.png) 

### webUIRenameFiles-renameFiles-feature-169.png
 ![webUIRenameFiles-renameFiles-feature-169.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-169.png) 

### webUIRenameFiles-renameFiles-feature-176.png
 ![webUIRenameFiles-renameFiles-feature-176.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-176.png) 

### webUIRenameFiles-renameFiles-feature-186.png
 ![webUIRenameFiles-renameFiles-feature-186.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-186.png) 

### webUIRenameFiles-renameFiles-feature-202.png
 ![webUIRenameFiles-renameFiles-feature-202.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-202.png) 

### webUIRenameFiles-renameFiles-feature-22.png
 ![webUIRenameFiles-renameFiles-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-22.png) 

### webUIRenameFiles-renameFiles-feature-227.png
 ![webUIRenameFiles-renameFiles-feature-227.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-227.png) 

### webUIRenameFiles-renameFiles-feature-23.png
 ![webUIRenameFiles-renameFiles-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-23.png) 

### webUIRenameFiles-renameFiles-feature-24.png
 ![webUIRenameFiles-renameFiles-feature-24.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-24.png) 

### webUIRenameFiles-renameFiles-feature-249.png
 ![webUIRenameFiles-renameFiles-feature-249.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-249.png) 

### webUIRenameFiles-renameFiles-feature-25.png
 ![webUIRenameFiles-renameFiles-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-25.png) 

### webUIRenameFiles-renameFiles-feature-26.png
 ![webUIRenameFiles-renameFiles-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-26.png) 

### webUIRenameFiles-renameFiles-feature-260.png
 ![webUIRenameFiles-renameFiles-feature-260.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-260.png) 

### webUIRenameFiles-renameFiles-feature-38.png
 ![webUIRenameFiles-renameFiles-feature-38.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-38.png) 

### webUIRenameFiles-renameFiles-feature-39.png
 ![webUIRenameFiles-renameFiles-feature-39.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-39.png) 

### webUIRenameFiles-renameFiles-feature-40.png
 ![webUIRenameFiles-renameFiles-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-40.png) 

### webUIRenameFiles-renameFiles-feature-43.png
 ![webUIRenameFiles-renameFiles-feature-43.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-43.png) 

### webUIRenameFiles-renameFiles-feature-62.png
 ![webUIRenameFiles-renameFiles-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-62.png) 

### webUIRenameFiles-renameFiles-feature-77.png
 ![webUIRenameFiles-renameFiles-feature-77.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-77.png) 

### webUIRenameFiles-renameFiles-feature-90.png
 ![webUIRenameFiles-renameFiles-feature-90.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFiles-feature-90.png) 

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-21.png
 ![webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-21.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-21.png) 

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-22.png
 ![webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-22.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-22.png) 

### webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-36.png
 ![webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFiles-renameFilesInsideProblematicFolderName-feature-36.png) 

### webUIRenameFolders-renameFolders-feature-107.png
 ![webUIRenameFolders-renameFolders-feature-107.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-107.png) 

### webUIRenameFolders-renameFolders-feature-108.png
 ![webUIRenameFolders-renameFolders-feature-108.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-108.png) 

### webUIRenameFolders-renameFolders-feature-109.png
 ![webUIRenameFolders-renameFolders-feature-109.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-109.png) 

### webUIRenameFolders-renameFolders-feature-122.png
 ![webUIRenameFolders-renameFolders-feature-122.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-122.png) 

### webUIRenameFolders-renameFolders-feature-127.png
 ![webUIRenameFolders-renameFolders-feature-127.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-127.png) 

### webUIRenameFolders-renameFolders-feature-132.png
 ![webUIRenameFolders-renameFolders-feature-132.png](https://cache.owncloud.com/owncloud/web/screenshots/15646/webUIRenameFolders-renameFolders-feature-132.png) 
 [...]

2021-05-25 10:43 UTC, individual-it reviewed
LGTM

2021-05-25 10:47 UTC, jasson99 commented
@LukasHirt @kulmann Can you please review and approve this if this can be merged??

2021-05-25 11:34 UTC, LukasHirt approved these changes
Good to go IMHO 👍

2021-05-25 12:06 UTC, merged