Focus breadcrumb on route change
owncloud/web pull request #5166
Opened 2021-05-28 10:40 UTC by pascalwengerter

## Description
Focus current active breadcrumb on route change and announce contents of current folder to screenreader

2021-05-28 12:39 UTC, kulmann requested changes
Found one issue that I didn't think about before. This now steals the focus away from the nav directly after clicking in the left sidebar. As far as I understand this behaviour is only supposed to happen upon navigating within the file list or through the breadcrumbs.

2021-05-28 13:14 UTC, pascalwengerter commented
> Found one issue that I didn't think about before. This now steals the focus away from the nav directly after clicking in the left sidebar. As far as I understand this behaviour is only supposed to happen upon navigating within the file list or through the breadcrumbs.

Tried preventing it with what we discussed, checking if we're staying within the same route and only setting the focus on the last breadcrumb item if that's the case

2021-05-31 15:50 UTC, kulmann requested changes

2021-05-31 15:50 UTC, kulmann commented on packages/web-app-files/src/mixins/accessibleBreadcrumb.js
> +          : this.$gettext('This folder has no content')
```suggestion
          : this.$gettext('This folder has no content.')
```

2021-05-31 15:50 UTC, kulmann commented on packages/web-app-files/src/mixins/accessibleBreadcrumb.js
> +        'containing %{filesCount} files and %{folderCount} folders',
Don't make the distinction between files and folders. Just use `items` and with correct pluralization. `This folder contains %{ itemCount } item.` for singular form and `This folder contains %{ itemCount } items.` plural form.

2021-05-31 22:16 UTC, kulmann approved these changes
LGTM 🚀

2021-05-31 22:16 UTC, merged