feat: add pagination
owncloud/web pull request #5224
Opened 2021-06-09 13:40 UTC by LukasHirt

2021-06-14 13:41 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIOCISFiles2</strong> failed. The build is cancelled...</summary>

2021-06-14 13:59 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISSharingInternalUsers2</strong> failed. The build is cancelled...</summary>

2021-06-15 09:35 UTC, LukasHirt commented
Something for separate PR - merge unit and integration tests coverage to get the real coverage result

2021-06-15 09:38 UTC, ownclouders commented
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16258/

<p>


Diff Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/diff/oc10/sideBar.png)
Actual Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/latest/oc10/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/feat/pagination/tests/vrt/baseline/oc10/sideBar.png)

</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16258/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
 ![webUIFilesDetails-fileDetails-feature-116.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/webUIFilesDetails-fileDetails-feature-116.png) 

### webUIFilesDetails-fileDetails-feature-66.png
 ![webUIFilesDetails-fileDetails-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/webUIFilesDetails-fileDetails-feature-66.png) 

### webUIFilesDetails-fileDetails-feature-82.png
 ![webUIFilesDetails-fileDetails-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/webUIFilesDetails-fileDetails-feature-82.png) 

### webUIFilesDetails-fileDetails-feature-99.png
 ![webUIFilesDetails-fileDetails-feature-99.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/webUIFilesDetails-fileDetails-feature-99.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/16258/webUIFilesList-fileList-feature-46.png) 


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. The build is cancelled...</summary>

2021-06-15 09:41 UTC, ownclouders commented
<details><summary>:boom: Visual regression tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16261/

<p>


Diff Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/diff/oc10/sideBar.png)
Actual Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/latest/oc10/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/feat/pagination/tests/vrt/baseline/oc10/sideBar.png)

</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16261/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
 ![webUIFilesDetails-fileDetails-feature-116.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/webUIFilesDetails-fileDetails-feature-116.png) 

### webUIFilesDetails-fileDetails-feature-66.png
 ![webUIFilesDetails-fileDetails-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/webUIFilesDetails-fileDetails-feature-66.png) 

### webUIFilesDetails-fileDetails-feature-82.png
 ![webUIFilesDetails-fileDetails-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/webUIFilesDetails-fileDetails-feature-82.png) 

### webUIFilesDetails-fileDetails-feature-99.png
 ![webUIFilesDetails-fileDetails-feature-99.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/webUIFilesDetails-fileDetails-feature-99.png) 

### webUIFilesList-fileList-feature-46.png
 ![webUIFilesList-fileList-feature-46.png](https://cache.owncloud.com/owncloud/web/screenshots/16261/webUIFilesList-fileList-feature-46.png) 


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. The build is cancelled...</summary>

2021-06-15 10:02 UTC, pascalwengerter reviewed
Works like a charm, I'm wondering if we want to go with the left- and right-alignment of the pagination and files/folder count sections?

I'd vote in favor of having them centered for a more organized look. Also, when no pagination is shown it looks off having the file/folder count aligned to the right with vast emptiness left & center

![Screenshot 2021-06-15 at 10 52 19](https://user-images.githubusercontent.com/16822008/122034028-04591680-cdc9-11eb-9dbd-4123f12e7b72.png)

2021-06-15 11:05 UTC, pascalwengerter commented
> Works like a charm, I'm wondering if we want to go with the left- and right-alignment of the pagination and files/folder count sections?
> 
> I'd vote in favor of having them centered for a more organized look. Also, when no pagination is shown it looks off having the file/folder count aligned to the right with vast emptiness left & center
> 
> ![Screenshot 2021-06-15 at 10 52 19](https://user-images.githubusercontent.com/16822008/122034028-04591680-cdc9-11eb-9dbd-4123f12e7b72.png)

Also, from an a11y standpoint we should also maybe give context on whether the displayed file/folder count&size is defined by the current page or all files in the accommodating folder?

2021-06-16 13:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFilePermission</strong> failed. The build is cancelled...</summary>

2021-06-16 13:16 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCIS-Trashbin-Upload-Move-Journey</strong> failed. The build is cancelled...</summary>

2021-06-16 13:44 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16376/

<p>


### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16376/webUIFiles-breadcrumb-feature-20.png) 


</p></details>
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. The build is cancelled...</summary>

2021-06-16 15:59 UTC, ownclouders commented
<details><summary>:boom: Visual regression tests <strong>webUIOCISFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16380/

<p>


Diff Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16380/diff/ocis/sideBar.png)
Actual Image: </br>
![sideBar.png](https://cache.owncloud.com/owncloud/web/screenshots/16380/latest/ocis/sideBar.png)
Comparing Against: </br>
![sideBar.png](https://raw.githubusercontent.com/owncloud/web/feat/pagination/tests/vrt/baseline/ocis/sideBar.png)

</p></details>

2021-06-16 16:03 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16380/

<p>


### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16380/webUIFiles-breadcrumb-feature-20.png) 


</p></details>

2021-06-16 20:24 UTC, kulmann requested changes

2021-06-16 20:24 UTC, kulmann commented on tests/helpers/toKebabCase.js
> +export default function(string) {
Could be replace with `kebabCase` from [lodash](https://lodash.com/docs/4.17.15#kebabCase)

2021-06-16 21:05 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16384/

<p>


### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16384/webUIFiles-breadcrumb-feature-20.png) 


</p></details>

2021-06-16 21:26 UTC, kulmann commented on packages/web-app-files/src/components/FilesListFooterInfo.vue
> +      TODO: merge all strings here to one interpollated translation
Thinking about it, the relevant information here is not about pagination, but about the current folder in general. The fact that it's paginated is IMO not relevant for the info text. If we want to show how many items are currently displayed, that's something for extending the pagination even more.

2021-06-16 21:50 UTC, kulmann commented on packages/web-app-files/src/components/FilesListFooterInfo.vue
> +      TODO: merge all strings here to one interpollated translation
Changed it to this, what do you think?

<img width="357" alt="Screenshot 2021-06-16 at 23 49 29" src="https://user-images.githubusercontent.com/3532843/122298956-aaa63880-cefd-11eb-8640-631f6b6ee350.png">

2021-06-16 21:51 UTC, kulmann commented on packages/web-app-files/src/components/FilesListFooterInfo.vue
> +      TODO: merge all strings here to one interpollated translation
Feel free to revert the commit and do something else

2021-06-16 22:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16388/

<p>


### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-unfavoriteFile-feature-13.png) 


</p></details>

2021-06-16 22:57 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16388/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
 ![webUIFilesDetails-fileDetails-feature-116.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesDetails-fileDetails-feature-116.png) 

### webUIFilesDetails-fileDetails-feature-66.png
 ![webUIFilesDetails-fileDetails-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesDetails-fileDetails-feature-66.png) 

### webUIFilesDetails-fileDetails-feature-82.png
 ![webUIFilesDetails-fileDetails-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesDetails-fileDetails-feature-82.png) 

### webUIFilesDetails-fileDetails-feature-99.png
 ![webUIFilesDetails-fileDetails-feature-99.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesDetails-fileDetails-feature-99.png) 

### webUIFilesList-sort-feature-31.png
 ![webUIFilesList-sort-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesList-sort-feature-31.png) 

### webUIFilesList-sort-feature-51.png
 ![webUIFilesList-sort-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFilesList-sort-feature-51.png) 


</p></details>

2021-06-16 23:08 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16388/

<p>


### webUIFavorites-favoritesFile-feature-131.png
 ![webUIFavorites-favoritesFile-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-131.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-favoritesFile-feature-30.png
 ![webUIFavorites-favoritesFile-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-30.png) 

### webUIFavorites-favoritesFile-feature-65.png
 ![webUIFavorites-favoritesFile-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-65.png) 

### webUIFavorites-favoritesFile-feature-74.png
 ![webUIFavorites-favoritesFile-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-favoritesFile-feature-74.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-34.png
 ![webUIFavorites-unfavoriteFile-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFavorites-unfavoriteFile-feature-34.png) 

### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16388/webUIFiles-breadcrumb-feature-20.png) 


</p></details>

2021-06-17 09:33 UTC, kulmann commented on packages/web-app-files/src/store/getters.js
> +  paginationLength: state => Math.ceil(state.files.length / state.filesPageLimit),
Renamed to `pages`. Please revert if you don't agree

2021-06-17 09:34 UTC, kulmann commented on tests/helpers/toKebabCase.js
> +export default function(string) {
Needs a decision first if we want to go with lodash / lodash-es / whatever. Keep it like it is for now.

2021-06-17 10:04 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16421/

<p>


### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-unfavoriteFile-feature-13.png) 


</p></details>

2021-06-17 10:17 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16421/

<p>


### webUIFavorites-favoritesFile-feature-131.png
 ![webUIFavorites-favoritesFile-feature-131.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-131.png) 

### webUIFavorites-favoritesFile-feature-14.png
 ![webUIFavorites-favoritesFile-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-14.png) 

### webUIFavorites-favoritesFile-feature-30.png
 ![webUIFavorites-favoritesFile-feature-30.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-30.png) 

### webUIFavorites-favoritesFile-feature-65.png
 ![webUIFavorites-favoritesFile-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-65.png) 

### webUIFavorites-favoritesFile-feature-74.png
 ![webUIFavorites-favoritesFile-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-favoritesFile-feature-74.png) 

### webUIFavorites-unfavoriteFile-feature-13.png
 ![webUIFavorites-unfavoriteFile-feature-13.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-unfavoriteFile-feature-13.png) 

### webUIFavorites-unfavoriteFile-feature-34.png
 ![webUIFavorites-unfavoriteFile-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFavorites-unfavoriteFile-feature-34.png) 

### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIFiles-breadcrumb-feature-20.png) 

### webUIMarkdownEditor-markdownFile-feature-26.png
 ![webUIMarkdownEditor-markdownFile-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/16421/webUIMarkdownEditor-markdownFile-feature-26.png) 


</p></details>

2021-06-17 12:45 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16443/

<p>


### webUIFiles-breadcrumb-feature-20.png
 ![webUIFiles-breadcrumb-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16443/webUIFiles-breadcrumb-feature-20.png) 


</p></details>

2021-06-17 13:07 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16448/

<p>


### webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png
 ![webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png](https://cache.owncloud.com/owncloud/web/screenshots/16448/webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png](https://cache.owncloud.com/owncloud/web/screenshots/16448/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png) 


</p></details>

2021-06-17 13:12 UTC, kulmann approved these changes
Awesome progress with the integration tests! Very cool pagination. LGTM 🥳 🚀 😍

2021-06-17 13:23 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalGroupsSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png
 ![webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalGroupsSharingIndicator-shareWithGroups-feature-136.png) 

### webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png
 ![webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalGroupsToRootSharingIndicator-shareWithGroups-feature-124.png) 


</p></details>

2021-06-17 13:25 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersBlacklisted</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-26.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-44.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-62.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-80.png) 

### webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png
 ![webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersBlacklisted-shareWithUsers-feature-92.png) 


</p></details>

2021-06-17 13:26 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersSharingIndicator</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-17.png) 

### webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png
 ![webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersSharingIndicator-shareWithUsers-feature-58.png) 

### webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png
 ![webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootSharingIndicator-shareWithUsers-feature-118.png) 


</p></details>

2021-06-17 13:28 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUISharingBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingAcceptSharesToRoot-acceptShares-feature-31.png
 ![webUISharingAcceptSharesToRoot-acceptShares-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingAcceptSharesToRoot-acceptShares-feature-31.png) 


</p></details>

2021-06-17 13:31 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>Move-Upload</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUIUpload-upload-feature-89.png
 ![webUIUpload-upload-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIUpload-upload-feature-89.png) 


</p></details>

2021-06-17 13:32 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFilePermission</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-60.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-60.png) 

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-61.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-61.png) 

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-62.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-62.png) 

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-63.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-63.png) 

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-64.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-64.png) 

### webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-65.png
 ![webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionMultipleUsers-shareFileWithMultipleUsers-feature-65.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-61.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-62.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-63.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-64.png) 

### webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png
 ![webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFilePermissionsGroups-sharePermissionsGroup-feature-65.png) 


</p></details>

2021-06-17 13:33 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFolderAdvancedPermissionMU</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-60.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-60.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-60.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-61.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-61.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-62.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-62.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-63.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-63.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-64.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-64.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-65.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-65.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-66.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-66.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-67.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-67.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-67.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-68.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-68.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-68.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-69.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-69.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-70.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-70.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-70.png) 

### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-71.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions-feature-71.png) 


</p></details>

2021-06-17 13:33 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFolderPermissions</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-61.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-62.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-63.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-64.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-65.png) 

### webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png
 ![webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionMultipleUsers-shareFolderWithMultipleUsers-feature-66.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-61.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-61.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-62.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-62.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-63.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-63.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-64.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-64.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-65.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-65.png) 

### webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-66.png
 ![webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderPermissionsGroups-sharePermissionsGroup-feature-66.png) 


</p></details>

2021-06-17 13:33 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingFolderAdvPermissionsGrp</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-61.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-61.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-61.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-62.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-62.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-62.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-63.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-63.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-63.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-64.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-64.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-64.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-65.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-65.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-65.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-66.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-66.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-67.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-67.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-67.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-68.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-68.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-68.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-69.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-69.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-70.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-70.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-70.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-71.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-71.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-71.png) 

### webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-72.png
 ![webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-72.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingFolderAdvancedPermissionsGroups-shareAdvancePermissionsGroup-feature-72.png) 


</p></details>

2021-06-17 13:35 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-9.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-9.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPrivateLinks-accessingPrivateLinks-feature-9.png) 

### webUIRestrictSharing-disableSharing-feature-16.png
 ![webUIRestrictSharing-disableSharing-feature-16.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-disableSharing-feature-16.png) 

### webUIRestrictSharing-restrictReSharing-feature-23.png
 ![webUIRestrictSharing-restrictReSharing-feature-23.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-restrictReSharing-feature-23.png) 

### webUIRestrictSharing-restrictReSharing-feature-42.png
 ![webUIRestrictSharing-restrictReSharing-feature-42.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-restrictReSharing-feature-42.png) 

### webUIRestrictSharing-restrictSharing-feature-31.png
 ![webUIRestrictSharing-restrictSharing-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-restrictSharing-feature-31.png) 

### webUIRestrictSharing-restrictSharing-feature-40.png
 ![webUIRestrictSharing-restrictSharing-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-restrictSharing-feature-40.png) 

### webUIRestrictSharing-restrictSharing-feature-56.png
 ![webUIRestrictSharing-restrictSharing-feature-56.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIRestrictSharing-restrictSharing-feature-56.png) 


</p></details>

2021-06-17 13:36 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIFiles2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUIFilesDetails-fileDetails-feature-116.png
 ![webUIFilesDetails-fileDetails-feature-116.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-116.png) 

### webUIFilesDetails-fileDetails-feature-14.png
 ![webUIFilesDetails-fileDetails-feature-14.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-14.png) 

### webUIFilesDetails-fileDetails-feature-163.png
 ![webUIFilesDetails-fileDetails-feature-163.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-163.png) 

### webUIFilesDetails-fileDetails-feature-172.png
 ![webUIFilesDetails-fileDetails-feature-172.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-172.png) 

### webUIFilesDetails-fileDetails-feature-25.png
 ![webUIFilesDetails-fileDetails-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-25.png) 

### webUIFilesDetails-fileDetails-feature-38.png
 ![webUIFilesDetails-fileDetails-feature-38.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-38.png) 

### webUIFilesDetails-fileDetails-feature-51.png
 ![webUIFilesDetails-fileDetails-feature-51.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-51.png) 

### webUIFilesDetails-fileDetails-feature-66.png
 ![webUIFilesDetails-fileDetails-feature-66.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-66.png) 

### webUIFilesDetails-fileDetails-feature-82.png
 ![webUIFilesDetails-fileDetails-feature-82.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-82.png) 

### webUIFilesDetails-fileDetails-feature-99.png
 ![webUIFilesDetails-fileDetails-feature-99.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIFilesDetails-fileDetails-feature-99.png) 


</p></details>

2021-06-17 13:37 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>IntegrationApp2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingAutocompletion-shareAutocompletion-feature-32.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingAutocompletion-shareAutocompletion-feature-32.png) 

### webUISharingAutocompletion-shareAutocompletion-feature-44.png
 ![webUISharingAutocompletion-shareAutocompletion-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingAutocompletion-shareAutocompletion-feature-44.png) 

### webUISharingInternalUsers-shareWithUsers-feature-57.png
 ![webUISharingInternalUsers-shareWithUsers-feature-57.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsers-shareWithUsers-feature-57.png) 

### webUISharingInternalUsers-shareWithUsers-feature-58.png
 ![webUISharingInternalUsers-shareWithUsers-feature-58.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsers-shareWithUsers-feature-58.png) 

### webUISharingInternalUsers-shareWithUsers-feature-59.png
 ![webUISharingInternalUsers-shareWithUsers-feature-59.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsers-shareWithUsers-feature-59.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-11.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-11.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingPublicBasic-publicLinkCreate-feature-11.png) 

### webUISharingPublicBasic-publicLinkCreate-feature-28.png
 ![webUISharingPublicBasic-publicLinkCreate-feature-28.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingPublicBasic-publicLinkCreate-feature-28.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-33.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-34.png) 

### webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png
 ![webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingPublicDifferentRoles-shareByPublicLinkDifferentRoles-feature-35.png) 

### webUIUpload-upload-feature-89.png
 ![webUIUpload-upload-feature-89.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIUpload-upload-feature-89.png) 


</p></details>

2021-06-17 13:39 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>webUIBasic</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUILogin-adminBlocksUser-feature-20.png
 ![webUILogin-adminBlocksUser-feature-20.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUILogin-adminBlocksUser-feature-20.png) 

### webUIPreview-imageMediaViewer-feature-140.png
 ![webUIPreview-imageMediaViewer-feature-140.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPreview-imageMediaViewer-feature-140.png) 

### webUIPreview-imageMediaViewer-feature-158.png
 ![webUIPreview-imageMediaViewer-feature-158.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPreview-imageMediaViewer-feature-158.png) 

### webUIPreview-imageMediaViewer-feature-83.png
 ![webUIPreview-imageMediaViewer-feature-83.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPreview-imageMediaViewer-feature-83.png) 

### webUIPreview-imageMediaViewer-feature-90.png
 ![webUIPreview-imageMediaViewer-feature-90.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPreview-imageMediaViewer-feature-90.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-17.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-17.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPrivateLinks-accessingPrivateLinks-feature-17.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-25.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPrivateLinks-accessingPrivateLinks-feature-25.png) 

### webUIPrivateLinks-accessingPrivateLinks-feature-9.png
 ![webUIPrivateLinks-accessingPrivateLinks-feature-9.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUIPrivateLinks-accessingPrivateLinks-feature-9.png) 


</p></details>

2021-06-17 13:43 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-100.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-100.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-100.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-109.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-31.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-31.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-31.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-32.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-32.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-32.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-33.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-33.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-33.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-34.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-34.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-34.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-37.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-37.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-37.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-44.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-44.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-44.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-54.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-74.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-74.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-75.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-75.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-75.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-78.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-78.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-78.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-86.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-86.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-86.png) 

### webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-93.png
 ![webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-93.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootCollaborator-shareWithUsers-feature-93.png) 

### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-11.png
 ![webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-11.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-11.png) 

### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-25.png
 ![webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-25.png) 

### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-40.png
 ![webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-40.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-40.png) 

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-88.png
 ![webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-88.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-88.png) 

### webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-96.png
 ![webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-96.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootShareWithPage-shareWithUsers-feature-96.png) 


</p></details>

2021-06-17 13:43 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot1</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16452/

<p>


### webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-103.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-129.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-142.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-161.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-183.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-197.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-212.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-255.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-256.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-257.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-275.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-52.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-53.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-54.png) 

### webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png
 ![webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRoot-shareWithUsers-feature-74.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-25.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-41.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-55.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-69.png) 

### webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png
 ![webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png](https://cache.owncloud.com/owncloud/web/screenshots/16452/webUISharingInternalUsersToRootBlacklisted-shareWithUsers-feature-81.png) 


</p></details>

2021-06-17 14:41 UTC, merged