fix: do not call vuex create store multiple times
owncloud/web pull request #5254
Opened 2021-06-11 11:53 UTC by LukasHirt

We've moved the create Vuex store logic into the index file of Web runtime to prevent initialising the store multiple times.

2021-06-11 12:11 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16180/

<p>


### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/16180/webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png) 


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. The build is cancelled...</summary>

2021-06-11 12:22 UTC, pascalwengerter requested changes
Unit tests fail in CI and PR number in changelog is off, otherwise a great catch IMO! 💪🏽

2021-06-11 12:22 UTC, pascalwengerter commented on changelog/unreleased/bugfix-remove-vuex-circular-init
> +https://github.com/owncloud/web/pull/5253
Needs to be 5254 🥴

2021-06-11 13:51 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>OCISSharingInternalUsers1</strong> failed. The build is cancelled...</summary>

2021-06-11 13:51 UTC, ownclouders commented
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. Please find the screenshots inside ...</summary>

https://drone.owncloud.com/owncloud/web/16184/

<p>


### webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png
 ![webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png](https://cache.owncloud.com/owncloud/web/screenshots/16184/webUISharingInternalUsersToRootPreviews-shareWithUsers-feature-54.png) 


</p></details>
<details><summary>:boom: Acceptance tests <strong>SharingInternalUsersRoot2</strong> failed. The build is cancelled...</summary>

2021-06-14 21:51 UTC, kulmann approved these changes
👍

2021-06-14 21:53 UTC, pascalwengerter approved these changes
LGTM 💓

2021-06-14 22:01 UTC, merged