[DRAFT] add option to define how many share recipients should be shown
owncloud/web pull request #5506
Opened 2021-07-11 18:02 UTC by fschade

## Description
the oc-select or share recipients only had only shown 200 users even if the backend has way more. This introduces a option to decide in configuration how many items should be there.

## Related Issue
- Fixes #5499

## Motivation and Context
let the user decide how many users should be shown in the recipients dropdown

## How Has This Been Tested?
- unit tests
- local oc10 installation with openLDAP and 1k users

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:
- [X] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] add changelog

2021-07-11 18:07 UTC, fschade commented
@pascalwengerter, we should discuss tomorrow if this is fine for now. In the future we should make use of the page and introduce a pagination there

2021-07-26 12:39 UTC, pascalwengerter commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/NewCollaborator.vue
> +      console.log(this.$store)
```suggestion
```

2021-07-27 13:59 UTC, kulmann requested changes
Please add docs for this new option in the `options` section of the `getting started` guide https://owncloud.dev/clients/web/getting-started/#options

2021-07-27 14:04 UTC, pascalwengerter commented
> Please add docs for this new option in the `options` section of the `getting started` guide https://owncloud.dev/clients/web/getting-started/#options

Good point, will take care

2021-07-27 20:31 UTC, kulmann approved these changes
LGTM 👍

2021-07-27 20:31 UTC, merged