[unit-tests] Added unit tests for NoContentMessage component
owncloud/web pull request #5517
Opened 2021-07-13 04:26 UTC by kiranparajuli589

## Description
- Unit tests added for `NoContentMessage` component

## Related Issue
- Part of #5234 

## Motivation and Context
- component testing

## How Has This Been Tested?
- 🤖 
- 👨🏼‍🎨 

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-07-14 07:51 UTC, saw-jan reviewed
LGTM

2021-07-14 11:25 UTC, individual-it requested changes

2021-07-14 11:25 UTC, individual-it commented on packages/web-app-files/tests/unit/components/FilesList/NoContentMessage.spec.js
> +  function getWrapper(props = {}, slots = {}) {
`props` is not used in any call

2021-07-15 04:32 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/FilesList/NoContentMessage.spec.js
> +  function getWrapper(props = {}, slots = {}) {
fixed.

2021-07-15 07:46 UTC, individual-it approved these changes

2021-07-15 07:46 UTC, merged