Sizeinfo unit test
owncloud/web pull request #5522
Opened 2021-07-14 06:00 UTC by saw-jan

## Description
Adds unit  tests for `SizeInfo` component

## Related Issue
- Part of #5234

## Motivation and Context
- increase unit tests coverage

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-07-14 06:05 UTC, saw-jan commented on packages/web-app-files/src/components/AppBar/SelectedResources/SizeInfo.vue
> +      key="multiple-select-info-with-size"
this section shows number of selected along with size so I think the key should be `multiple-select-info-with-size`

2021-07-14 06:06 UTC, saw-jan commented on packages/web-app-files/src/components/AppBar/SelectedResources/SizeInfo.vue
> +      key="multiple-select-info"
this section only shows number of selected so I think the key should be `multiple-select-info`

2021-07-14 06:22 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17377/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154

2021-07-14 07:19 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17390/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-07-14 08:11 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17395/39/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-14 08:22 UTC, kiranparajuli589 reviewed
Lgtm

2021-07-14 09:02 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/17396/11/1
The following scenarios passed on retry:
- webUIFavorites/unfavoriteFile.feature:34

2021-07-16 06:13 UTC, individual-it requested changes
@LukasHirt @kulmann can you have a look if the code-changes are OK

2021-07-16 06:13 UTC, individual-it commented on packages/web-app-files/tests/unit/components/AppBar/SelectedResources/SizeInfo.spec.js
> +    .mockImplementation(size => (isNaN(size) ? '?' : size + ' B'))
I don't feel good about having extra logic in the mock. Can we have different mocks for different cases? That would make the tests easier to read and have less risk that the logic in the tests break

2021-07-16 07:36 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17480/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-07-16 08:13 UTC, individual-it reviewed
tests look good!

2021-07-16 09:39 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17487/24/1
The following scenarios passed on retry:
- webUISharingInternalUsersShareWithPage/shareWithUsers.feature:91

2021-07-16 10:51 UTC, LukasHirt approved these changes
Code changes LGTM

2021-07-16 10:59 UTC, individual-it approved these changes

2021-07-16 11:14 UTC, merged