[unit-tests] add unit tests for QuickActions component
owncloud/web pull request #5526
Opened 2021-07-15 05:17 UTC by kiranparajuli589

WIP

2021-07-16 08:31 UTC, saw-jan commented on packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
> +const { shallowMount, mount } = require('@vue/test-utils')
```suggestion
import { createLocalVue, shallowMount, mount } from '@vue/test-utils'
import DesignSystem from 'owncloud-design-system'
const localVue = createLocalVue()
localVue.use(DesignSystem)
```

2021-07-16 11:06 UTC, individual-it requested changes

2021-07-16 11:06 UTC, individual-it commented on packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
> +    it('should display all displayed provided action buttons', () => {
```suggestion
    it('should display all action buttons where "displayed" is set to "true"', () => {
```

2021-07-16 11:06 UTC, individual-it commented on packages/web-app-files/tests/unit/components/FilesList/QuickActions.spec.js
> +    it('should not display any non displayed provided action buttons', () => {
```suggestion
    it('should not display any button where "displayed" is set to "false"', () => {
```

2021-07-20 05:59 UTC, individual-it approved these changes

2021-07-20 05:59 UTC, merged