[unit-tests] Added unit test for collaborator role definition helper
owncloud/web pull request #5544
Opened 2021-07-19 10:22 UTC by kiranparajuli589

## Description
Added unit tetsts for `collaboratorRoleDefinition` helper 

## Related Issue
- part of #5236 

## Motivation and Context
- unit tests coverage

## How Has This Been Tested?

- 💇🏼‍♂️ 
- 🤖 

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-07-20 10:50 UTC, saw-jan reviewed
LGTM

2021-07-23 05:36 UTC, individual-it requested changes
only some changes in the test-names to make the easier to read

2021-07-23 05:36 UTC, individual-it commented on packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js
> +  describe('when allow share permission set to true', () => {
```suggestion
  describe('when "allow share permission" is set to true', () => {
```

2021-07-23 05:36 UTC, individual-it commented on packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js
> +    it('viewer and editor should have share permission', () => {
```suggestion
    it('should have share permissions for viewer and editor', () => {
```

2021-07-23 05:36 UTC, individual-it commented on packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js
> +  describe('when allow share permission set to false', () => {
```suggestion
  describe('when "allow share permission" is set to false', () => {
```

2021-07-23 05:36 UTC, individual-it commented on packages/web-app-files/tests/unit/helpers/collaboratorRolesDefinition.spec.js
> +    it('viewer and editor should not have share permission', () => {
```suggestion
    it('should not have share permissions for viewer and editor', () => {
```

2021-07-23 05:45 UTC, individual-it approved these changes

2021-07-23 09:18 UTC, merged