upload or create into folder Shares
owncloud/web pull request #5566
Opened 2021-07-25 22:14 UTC by ScharfViktor

A test is written that demonstrates the error. The test will work when the bug is fixed

Description here https://github.com/owncloud/ocis/issues/2322

2021-07-25 22:41 UTC, ownclouders commented
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/17643/46/1
The following scenarios passed on retry:
- webUILogin/openidLogin.feature:29

2021-07-25 22:45 UTC, ownclouders commented
Results for <strong>oC10MoveUpload</strong> https://drone.owncloud.com/owncloud/web/17643/13/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-25 22:58 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/17645/38/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

2021-07-25 23:25 UTC, ownclouders commented
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/17645/64/1
<details><summary>:boom: The acceptance tests failed. Please find the screenshots inside ...</summary>

<p>


### webUIFilesCopy-copy-feature-36.png
 ![webUIFilesCopy-copy-feature-36.png](https://cache.owncloud.com/owncloud/web/screenshots/17645/webUIFilesCopy-copy-feature-36.png) 


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-26 06:35 UTC, phil-davis reviewed
Tests are good. This is interesting behavior and good to have tests for the current oC10 behavior. We need everybody to discuss in the issue what the behavior should be.

2021-07-26 06:35 UTC, phil-davis commented on tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
> +    Given user "Brian" has created file "lorem.txt"
```suggestion
    Given user "Brian" has been created with default attributes and without skeleton files
    And user "Brian" has created file "lorem.txt"
```

We don't need user Brian in all the scenarios of this feature. If Brian is created in the Background section then it wastes CI time on each of the other scenarios.

2021-07-26 06:35 UTC, phil-davis commented on tests/acceptance/features/webUICreateFilesFolders/createFolders.feature
> +    And user "Brian" has been created with default attributes and without skeleton files
This can be removed from here. It is only needed in one scenario, so it the step can go just in that scenario.

2021-07-26 06:59 UTC, phil-davis approved these changes

2021-07-26 07:00 UTC, phil-davis commented
@ScharfViktor there is now a conflict with the other PR  that was just merged. You need to rebase and sort that out.

2021-07-26 07:07 UTC, phil-davis approved these changes

2021-07-27 07:39 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17695/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-07-27 07:46 UTC, ownclouders commented
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/17695/51/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:19

2021-07-27 08:12 UTC, phil-davis commented
> The test will work when the bug is fixed

The behavior might be a feature, and not need to be fixed.

2021-07-27 08:22 UTC, ownclouders commented
Results for <strong>oC10SharingPublicManagement</strong> https://drone.owncloud.com/owncloud/web/17697/33/1
The following scenarios passed on retry:
- webUISharingPublicManagement/publicLinkIndicator.feature:27

2021-07-27 08:26 UTC, phil-davis commented on tests/acceptance/features/webUIUpload/uploadIntoShares.feature
> +    When the user has opened folder "Shares"
```suggestion
    When the user opens folder "Shares" 
```

We try to write the `When` "action" step(s) in the present tense.

2021-07-29 10:32 UTC, ownclouders commented
Results for <strong>oCISSharingInternalUsers1</strong> https://drone.owncloud.com/owncloud/web/17783/54/1
The following scenarios passed on retry:
- webUISharingInternalUsers/shareWithUsers.feature:108

2021-07-29 11:19 UTC, phil-davis reviewed
The tests look good. Just a few suggestions for words in the scenario descriptions.

When you get `.drone.star` sorted out, we will see if the scenarios pass in CI.

2021-07-29 11:19 UTC, phil-davis commented on .drone.star
> +    "webUIOperationsWithFolderShares",
There are more places to add this suite name - search for `webUIMoveFilesFolders` - there are groups of pipelines that run with oC10 and with OCIS, and with different typical phone-sized screen resolutions.

2021-07-29 11:19 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  This suite of tests describes different behavior in osis and os ownCloud10 with respect to
```suggestion
  This suite of tests describes different behavior in oCIS and ownCloud10 with respect to 
```

2021-07-29 11:19 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: the Shares folder exists after accept first shared file
```suggestion
  Scenario: the Shares folder exists after accepting the first shared file
```

2021-07-29 11:19 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to upload of a file or a folder into a folder Shares with all permissions in ocis
```suggestion
  Scenario: try to upload a file or a folder into a folder Shares with all permissions in oCIS
```

2021-07-29 11:19 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to upload of a file or a folder into a folder Shares with read permissions in ocis
```suggestion
  Scenario: try to upload a file or a folder into a folder Shares with read permissions in oCIS
```

2021-07-29 11:19 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to move of a file or a folder into a folder Shares in oc10
```suggestion
  Scenario: move a file or a folder into a folder Shares in oc10 
```

2021-07-29 20:23 UTC, ownclouders commented
Results for <strong>oCISSharingPermissions2</strong> https://drone.owncloud.com/owncloud/web/17802/57/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-29 20:24 UTC, ownclouders commented
Results for <strong>oCISResharing1</strong> https://drone.owncloud.com/owncloud/web/17802/59/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-29 20:37 UTC, ownclouders commented
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17803/49/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-30 06:04 UTC, ownclouders commented
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/17823/49/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-30 08:48 UTC, ownclouders commented
Results for <strong>oCISSharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/17839/61/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-30 08:49 UTC, ownclouders commented
Results for <strong>oCISSharingPermissions2</strong> https://drone.owncloud.com/owncloud/web/17839/57/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-30 10:08 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/17842/27/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-07-30 10:23 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/17842/39/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

2021-07-30 10:24 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/17842/38/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-07-30 19:15 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsers</strong> https://drone.owncloud.com/owncloud/web/17857/24/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:35 UTC, phil-davis reviewed
This looks good. I will adjust a couple of small English changes, rebase, and it can be merged when CI passes.

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/expected-failures-with-ocis-server-ocis-storage.md
> +### [user cannot upload new folder/file into folder Shares](https://github.com/owncloud/ocis/issues/2322)
https://github.com/owncloud/ocis/issues/2322 https://github.com/cs3org/reva/pull/1939 should have fixed this?

And I think that code is in oCIS now. But maybe some web code needs to also be adjusted to get these passing.

Anyway, we had better rebase this PR to make sure that we get an up-to-date CI result before merging.

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: the Shares folder exists accepting the first shared file
```suggestion
  Scenario: the Shares folder exists after accepting the first shared file
```

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to upload of a file or a folder into a folder Shares with all permissions in oCIS
```suggestion
  Scenario: try to upload a file or a folder into a folder Shares with all permissions in oCIS
```

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to upload of a file or a folder into a folder Shares with read permissions in oCIS
```suggestion
  Scenario: try to upload a file or a folder into a folder Shares with read permissions in oCIS 
```

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: create of new folder into a folder Shares in oc10
```suggestion
  Scenario: create a new folder into a folder Shares in oc10
```

2021-08-10 06:35 UTC, phil-davis commented on tests/acceptance/features/webUIOperationsWithFolderShares/accessToSharesFolder.feature
> +  Scenario: try to move of a file or a folder into a folder Shares in oCIS
```suggestion
  Scenario: try to move a file or a folder into a folder Shares in oCIS
```

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18121/11/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/18121/44/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10Basic</strong> https://drone.owncloud.com/owncloud/web/18121/6/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10Locks</strong> https://drone.owncloud.com/owncloud/web/18121/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISBasic</strong> https://drone.owncloud.com/owncloud/web/18121/46/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10SharingFolderAdvancedPermissionMU</strong> https://drone.owncloud.com/owncloud/web/18121/18/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISSharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/18121/61/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/18121/62/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISRename</strong> https://drone.owncloud.com/owncloud/web/18121/48/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/18121/52/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/18121/39/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISSharingPermissions1</strong> https://drone.owncloud.com/owncloud/web/18121/56/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10IntegrationNotifications</strong> https://drone.owncloud.com/owncloud/web/18121/63/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10Trashbin</strong> https://drone.owncloud.com/owncloud/web/18121/35/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/18121/45/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10SharingFilePermission</strong> https://drone.owncloud.com/owncloud/web/18121/17/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18121/27/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/18121/51/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10Files2</strong> https://drone.owncloud.com/owncloud/web/18121/12/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oC10CreateDelete</strong> https://drone.owncloud.com/owncloud/web/18121/8/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:43 UTC, ownclouders commented
Results for <strong>oCISFavorites</strong> https://drone.owncloud.com/owncloud/web/18121/50/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 06:45 UTC, phil-davis approved these changes

2021-08-10 07:21 UTC, ownclouders commented
Results for <strong>oC10Basic</strong> https://drone.owncloud.com/owncloud/web/18124/7/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-10 07:32 UTC, phil-davis commented
I added `full-ci`  to the PR title, rebased and pushed again so we get a complete set of results. There were some unexpected failures.

2021-08-10 07:55 UTC, ownclouders commented
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18126/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsToRootSharingIndicator/shareWithGroups.feature:104
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

2021-08-10 08:54 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/18130/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

2021-08-10 08:59 UTC, ownclouders commented
Results for <strong>oC10Locks</strong> https://drone.owncloud.com/owncloud/web/18130/8/1
The following scenarios passed on retry:
- webUIWebdavLockProtection/move.feature:123

2021-08-10 09:39 UTC, phil-davis commented
I suggest that we rebase this after https://github.com/owncloud/web/pull/5652 is merged - that PR will provide a known-good green CI to the latest oCIS 1.10.0

2021-08-12 10:52 UTC, ownclouders commented
Results for <strong>oC10XGAPortrait2</strong> https://drone.owncloud.com/owncloud/web/18230/43/1
The following scenarios passed on retry:
- webUIMoveFilesFolders/moveFiles.feature:51

2021-08-13 07:41 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18271/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

2021-08-16 10:02 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18309/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154

2021-08-16 10:20 UTC, ownclouders commented
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/18309/52/1
The following scenarios passed on retry:
- webUICreateFilesFolders/createFolderEdgeCases.feature:19

2021-08-16 12:53 UTC, phil-davis commented
The linked drone build https://drone.owncloud.com/owncloud/web/18313/1/1 shows that it was cancelled after 5 seconds.
I have no idea why that happened.
I will restart it.

2021-08-16 13:41 UTC, ownclouders commented
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/18321/45/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

2021-08-16 13:47 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/18321/40/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

2021-08-16 14:35 UTC, phil-davis commented
The usual 0C10Basic pipeline that passes in CI has:
```
$ cucumber-js --retry 1 --require-module @babel/register --require-module @babel/polyfill --require tests/acceptance/setup.js --require tests/acceptance/stepDefinitions --format node_modules/cucumber-pretty tests/acceptance/features/webUIAccount tests/acceptance/features/webUILogin tests/acceptance/features/webUIPreview tests/acceptance/features/webUIPrivateLinks -t 'not @skip and not @skipOnOC10 and not @openIdLogin'
```

That has `not @openIdLogin` in the filter tags. Those tests are skipped when running against oC10.

But https://drone.owncloud.com/owncloud/web/18321/7/14 has only `not @skipOnOC10 and not @notToImplementOnOC10` in the filter tags. So those OpenId test scenarios were being run.

I added a commit to fix that.

2021-08-16 15:19 UTC, phil-davis requested changes

2021-08-16 15:19 UTC, phil-davis commented on nodesource_setup.sh
> +# Discussion, issues and change requests at:
Why is this file committed?
I will delete it...

2021-08-16 17:09 UTC, phil-davis approved these changes

2021-08-16 17:11 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18335/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-08-16 17:20 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18335/12/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-16 19:27 UTC, merged