[tests-only][unit-tests] App bar unit test
owncloud/web pull request #5603
Opened 2021-08-02 10:34 UTC by saw-jan

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-08-04 03:54 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
> +      it('should show size info', () => {
you've tested that new but is not visible when items are not selected. can the counterpart go inside this describe?

2021-08-05 05:57 UTC, kiranparajuli589 reviewed
lgtm 👍🏼

2021-08-06 04:25 UTC, individual-it requested changes
do we need other tests for when one item is selected vs. multiple selected items?

2021-08-06 04:25 UTC, individual-it commented on packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
> +    describe('when items are not selected', () => {
```suggestion
    describe('when no items are selected', () => {
```

2021-08-06 04:25 UTC, individual-it commented on packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
> +    describe('when items are not selected', () => {
```suggestion
    describe('when no items are selected', () => {
```

2021-08-06 04:25 UTC, individual-it commented on packages/web-app-files/tests/unit/components/AppBar/AppBar.spec.js
> +      describe('when items are not selected', () => {
```suggestion
      describe('when no items are selected', () => {
```

2021-08-09 05:22 UTC, individual-it approved these changes

2021-08-09 05:23 UTC, merged