[unit-tests-only] add unit tests for edit collaborator components
owncloud/web pull request #5662
Opened 2021-08-12 05:45 UTC by dpakach

## Description

[unit-tests-only] add unit tests for edit collaborator components

## Related Issue

- Related https://github.com/owncloud/web/issues/5234

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-08-12 07:24 UTC, ownclouders commented
Results for <strong>oC10XGAPortrait1</strong> https://drone.owncloud.com/owncloud/web/18207/42/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

2021-08-12 07:30 UTC, ownclouders commented
Results for <strong>oC10SharingInternalGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/18207/23/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-12 09:00 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +    canShare: () => true
imo `type` is the only required attribute here, can you review this and use only required

2021-08-13 10:33 UTC, dpakach commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +        expirationDate,
No it expects javascript Date object here

2021-08-13 10:37 UTC, dpakach commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(spinner.exists()).toBe(false)
why?
checking `toBeFalsy()` will also pass when the result is 0. if it returns anything other than false, I think we can assume its broken.

2021-08-13 12:09 UTC, ownclouders commented
Results for <strong>oC10SharingInternalGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/18287/23/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-16 11:57 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(spinner.exists()).toBe(false)
.exists() function only returns boolean.

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +      // FIXME: timezone offset is manually added in thecode
```suggestion
      // FIXME: timezone offset is manually added in the code
```
fixme??

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +    displayname: displayNames[name] // FIXME: some values use different property name for display name
these are not used in the code anywhere, seem redundant.

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +  }
owner seems unused after this. please remove if not needed.

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +  return storeOpts
```suggestion
  return {
    state: {
      user: userObj(user)
    },
    modules: {
      Files: {
        namespaced: true,
        getters: {
          highlightedFile: () => {
            return { type: 'file' }
          }
        }
      }
    },
    getters: {
      isOcis: () => false,
      user: () => userObj(user),
      capabilities: () => {
        return {
          files_sharing: shareCapabilities
        }
      }
    }
  }
```

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(spinner.exists()).toBe(false)
these all tests can use a same wrapper at top with spies predefined. no need to define separate wrapper for every test

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +  const storeOpts = {
you can return the object directly. this variable name seems odd to me

2021-08-16 12:30 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +}
used in multiple files. can it be DRY?

2021-09-02 11:10 UTC, pascalwengerter requested changes
@dpakach please rebase, address reviews and refactor, would be glad to merge this one soon 🧗🏽‍♂️

2021-09-03 09:15 UTC, dpakach commented
@pascalwengerter I have addressed the reviews can you review.

2021-09-03 09:43 UTC, ownclouders commented
Results for <strong>oC10SharingInternalGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/18825/23/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/CollaboratorsEditOptions.spec.js
> +      expect(roleLabel.text()).toBe('Role')
use snapshot tests to assert text
```suggestion
      expect(roleLabel).toMatchSnapshot()
```

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(errorMsg.text()).toBe('some error')
use snapshot

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(editHint.text()).toBe('Editing share with User One')
use snapshot

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(cancelButton.text()).toBe('Cancel')
use snapshot

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +      expect(saveButton.text()).toBe('Save')
use snapshot

2021-09-10 04:37 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditCollaborator.spec.js
> +    it('save button should work', async () => {
little vague...please be more descriptive here

2021-11-17 06:39 UTC, kiranparajuli589 reviewed
lgtm

2021-11-29 04:29 UTC, individual-it commented
blocked waiting for review @kulmann @pascalwengerter

2021-12-02 15:37 UTC, pascalwengerter commented
Closed in favor of #6076, sorry for being unresponsive so long. The sidebar sharing components are receiving a major overhaul in #6039, I'll see what I can re-use from your work here - thanks!

2021-12-02 15:37 UTC, closed without merging