[unit-tests-only] Add unit tests for Avatar component
owncloud/web pull request #5718
Opened 2021-08-23 10:00 UTC by saw-jan

## Description
Adds unit  tests for `Avatar` component

## Related Issue
- Part of #5234

## Motivation and Context
- increase unit tests coverage

## How Has This Been Tested?
- test environment: local & CI

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-08-23 11:52 UTC, kiranparajuli589 commented on packages/web-runtime/tests/unit/components/Avatar.spec.js
> +import Avatar from '../../../src/components/Avatar.vue'
```suggestion
import Avatar from '@files/src/components/Avatar.vue'
```

2021-08-23 11:52 UTC, kiranparajuli589 commented on packages/web-runtime/tests/unit/components/Avatar.spec.js
> +  describe('when loading is true', () => {
```suggestion
  describe('when loading is set as true', () => {
```

2021-08-25 06:29 UTC, kiranparajuli589 reviewed
lgtm 👍🏼

2021-08-25 10:42 UTC, pascalwengerter requested changes
Looks good so far but I'd expect it to test some more functionaity 🤓

2021-08-25 10:42 UTC, pascalwengerter commented on packages/web-runtime/tests/unit/components/Avatar.spec.js
> +      expect(avatar.props().src).toEqual('')
Please also test the case where `src` is set and check that the `setUser` method is being called ;)

2021-08-25 10:42 UTC, pascalwengerter commented on packages/web-runtime/tests/unit/components/Avatar.spec.js
> +            profile_picture: true
Please check the `Avatar component` and have a test for `profile_picture` being both set to true and to false (and checking it causes the desired behavior)!

2021-08-25 10:43 UTC, pascalwengerter commented on packages/web-runtime/tests/unit/components/Avatar.spec.js
> +            profile_picture: true
Edit: Could also happen in an integration test I suppose. For the unit test it should be enough to spy & check that the `setUser` method is successfully being called on mounted

2021-09-09 08:16 UTC, pascalwengerter approved these changes
LGTM

2021-09-09 08:16 UTC, merged