[WIP] Display share-info details in right sidebar
owncloud/web pull request #5730
Opened 2021-08-24 13:03 UTC by paulcod3

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-08-25 13:21 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18597/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-08-25 13:31 UTC, ownclouders commented
Results for <strong>oC10iPhone2</strong> https://drone.owncloud.com/owncloud/web/18597/46/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:14

2021-08-25 13:35 UTC, paulcod3 commented
@kulmann @pascalwengerter would be nice if someone could tell me if the implementation is right so far before I write unittest just in case something is terribly wrong.

2021-08-25 13:54 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18598/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-08-25 14:01 UTC, kulmann requested changes

2021-08-25 14:01 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
> +      const date = new Date(this.sharedTime * 1000)
Please use `luxon` for `date-to-human-readable`-conversions.

2021-08-25 14:05 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/18598/40/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

2021-08-25 14:07 UTC, ownclouders commented
Results for <strong>oC10XGAPortrait2</strong> https://drone.owncloud.com/owncloud/web/18598/43/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:14

2021-08-25 14:07 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/18598/39/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:363

2021-08-25 15:19 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/18602/40/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:356

2021-08-26 08:46 UTC, pascalwengerter submitted a review, later dismissed
Code looks good so far already, minor improvement ideas

2021-09-07 09:09 UTC, paulcod3 commented on packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
> +    sharesTreeLoading(current) {
We will be refactoring the share trees load function to be awaitable in the future.

2021-09-07 09:13 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
> +    sharesTreeLoading(current) {
Agreed in a call to keep it like it is and refactor it once we have the shares tree in a good state.

2021-09-07 14:05 UTC, kulmann approved these changes
LGTM 👍

2021-09-07 15:18 UTC, kulmann approved these changes
LGTM 👍

2021-09-07 17:08 UTC, ownclouders commented
Results for <strong>oC10SharingInternalGroupsSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/18940/24/1
The following scenarios passed on retry:
- webUISharingInternalGroupsSharingIndicator/shareWithGroups.feature:114

2021-09-08 06:56 UTC, merged