[unit-tests-only] Add todo unit tests for PrivateLink view
owncloud/web pull request #5750
Opened 2021-08-30 10:02 UTC by saw-jan

## Description
Added `todo` unit tests for `PrivateLink` view

## Related Issue
- part fo https://github.com/owncloud/web/issues/5237

## Motivation and Context

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-08-30 10:25 UTC, pascalwengerter reviewed
Looks good, please go ahead 🙌🏽

2021-08-30 10:41 UTC, saw-jan commented
@pascalwengerter should I wait for this PR to be merged or add tests in this PR.
As we have discussed in an earlier meeting, we merge this PR and write actual tests in another PR

2021-08-30 11:15 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/views/PrivateLink.spec.js
> +  it.todo('should call "getPathForFileId" on mount')
```suggestion
  it.todo('should call "getPathForFileId" when the component is mounted')
```

2021-08-30 11:15 UTC, pascalwengerter requested changes
Please put the top 4 todos into their own "when the page has loaded successfully" `describe` block but otherwise good to go!

2021-08-30 13:02 UTC, kulmann requested changes

2021-08-30 13:02 UTC, kulmann commented on packages/web-app-files/tests/unit/views/PrivateLink.spec.js
> +  describe('when "loading" is set as true', () => {
I think 
```suggestion
  describe('when the page is still loading', () => {
```
would be a better description for the group

2021-08-30 13:02 UTC, kulmann commented on packages/web-app-files/tests/unit/views/PrivateLink.spec.js
> +  describe('when there is error', () => {
```suggestion
  describe('when there was an error', () => {
```

2021-08-31 07:31 UTC, kulmann requested changes

2021-08-31 07:31 UTC, kulmann commented on packages/web-app-files/tests/unit/views/PrivateLink.spec.js
> +    it.todo('should call "getPathForFileId" method')
I'm struggling with this description. I'd like to aim for a `test driven` development approach in the future. For that we'd have to write unit tests as black box tests. A test description about whether or not a certain function was called would be not allowed in such a case. Instead you'd have to describe behaviour of the component (`should resolve the provided file id to a path from the backend`).

2021-08-31 07:53 UTC, kulmann approved these changes
Awesome 👍

2021-08-31 08:34 UTC, pascalwengerter approved these changes
LGTM, please go ahead!

2021-08-31 08:36 UTC, merged