[unit-tests-only] Add todo unit tests for SharedViaLink view
owncloud/web pull request #5751
Opened 2021-08-30 10:36 UTC by saw-jan

## Description
Added `todo` unit tests for `SharedViaLink` view

## Related Issue
- part fo https://github.com/owncloud/web/issues/5237

## Motivation and Context

## How Has This Been Tested?
- test environment: local

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2021-08-30 11:14 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +      it.todo('should call "rowMounted" method when the table row is mounted')
isn't this method is called when some event like you mentioned in above step is fired? rather saying `when the table row is mounted` you can be more detailed with the event name

2021-08-31 04:13 UTC, kiranparajuli589 commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +      it.todo('should call "rowMounted" method method on "rowMounted" event')
```suggestion
      it.todo('should call "rowMounted" method on "rowMounted" event')
```

2021-08-31 05:36 UTC, kiranparajuli589 reviewed
looks good 👍🏼

2021-08-31 07:50 UTC, kulmann requested changes

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +  describe('when loading is set as true', () => {
```suggestion
  describe('when the view is still loading', () => {
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +  describe('when loading is set as false', () => {
```suggestion
  describe('when the view is not loading anymore', () => {
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +    describe('when the length of activeFiles is zero', () => {
```suggestion
    describe('when there are no files to be displayed', () => {
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +    describe('when the length of activeFiles is one or more', () => {
```suggestion
    describe('when there are one or more files to be displayed', () => {
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +      it.todo('should call "$_mountSideBar_showDefaultPanel" method on "showDetails" event')
```suggestion
      it.todo('should trigger showing the sidebar when a "showDetails" event gets emitted')
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +      it.todo('should call "$_fileActions_triggerDefaultAction" method on "fileClick" event')
```suggestion
      it.todo('should trigger the default action when a "fileClick" event gets emitted')
```

2021-08-31 07:50 UTC, kulmann commented on packages/web-app-files/tests/unit/views/SharedViaLink.spec.js
> +      it.todo('should call "rowMounted" method on "rowMounted" event')
```suggestion
      it.todo('should lazily load previews when a "rowMounted" event gets emitted')
```

2021-08-31 08:13 UTC, kulmann approved these changes
LGTM 👍

2021-08-31 10:23 UTC, merged