[WIP] Introduce Skeleton-Application, Runtime hooks and demystify runtime boot logic
owncloud/web pull request #5752
Opened 2021-08-30 15:42 UTC by fschade

The main reason for this pr was to provide a skeleton application which showcases how [applications can inject file-handlers](https://github.com/owncloud/web/pull/5712).

The challenge here was that in some cases the application needed to obtain those information from an api which can take time to process. It was not possible to wait for applications and the runtime did proceed even if the application hasn't finished loading what ever it needed (e.g. promises).

To tackle that case it was necessary to introduce such a logic (hooks). The runtime now understand 3 types of hooks.

**register hook**
this hook gets fired once the application is requested and got loaded by the runtime, it is not safe to call other applications from here because it's not guaranteed that all other applications have finished their registration process.

**prepare hook**
all other applications are registered, this is a good place to call other applications or provide needed third party application data

**mounted hook**
this gets called after the main ui from the runtime got announced to the browser, from here every action will happen AFTER the ui is in place.

we took the opportunity while working on the runtime to refactor and demystify the whole runtime boot logic and rewrite it from the ground up in typescript.

the main reasons for doing this:

- we decided to go with typescript
- it was a long javascript file and hard to understand
- the dependencies where mixed with the application logic
- it will help with the vue 3 migration
- it was hard up to nearly impossible to test

the application boot logic is now class-based and introduces a 'NextApplication' style, it takes care that all current applications still work by doing an automatic conversion between current and next. The next style applications can't be used at the moment, we first need to decide how the public interface could look like.

It also introduces a runtime **API** which only exposes (by DI) allowed functionality to the requested applications.

This can change in the future and for now we only have to decide how the public application runtime API should look like, everything else can be changed later without breaking existing applications.

This is a prerequisite (or fix) for:
- application don't load in order anymore #2891
- vue 3 migration #5269
- let extensions register more flexible file open actions #5135
- remove loadConfig on extensions #3726 
- capabilities seem to be loaded too late sometimes #3771 (needs api tweak)
- allow to include custom js/html when running ocis web #4735 
- app provider #5712
- allow extensions to inject views in files app #5460
- a new runtime
- doing a backend switch at runtime
- request async information in the boot process of a application 
- boot logic testability

this is wip and the skeleton app needs more attention and functionality

2021-08-30 16:08 UTC, ownclouders commented
Results for <strong>oCISSharingPermissions2</strong> https://drone.owncloud.com/owncloud/web/18712/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-08-30 17:09 UTC, ownclouders commented
Results for <strong>oCISSharingPermissions2</strong> https://drone.owncloud.com/owncloud/web/18713/58/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-09-01 12:49 UTC, pascalwengerter reviewed
Looks pretty awesome! Not sure how we should proceed here (before you're going on holidays next week), maybe it makes sense to pull the runtime/boot-refactoring out of this PR in a separate one already, so the cognitive load of this one shrinks plus I think it also helps with the Vue3 upgrade

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/defaults/vue.js
> +  // optional pluginOptions
This comment can be removed as far as I'm concerned

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/container/api.ts
> + * exposed runtime api, this wraps all available api actions in a closure and provide application
```suggestion
 * exposed runtime api, this wraps all available api actions in a closure and provides application
```

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/container/api.ts
> + * each application get it's own provisioned api!
```suggestion
 * each application gets its own provisioned api!
```

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/container/application/index.ts
> +    /** add valuable sniffer to detect nex applications, then implement next application factory */
```suggestion
    /** add valuable sniffer to detect next applications, then implement next application factory */
```

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/container/store.ts
> + * main propose of this is to keep a reference to all announced applications.
```suggestion
 * main purpose of this is to keep a reference to all announced applications.
```

2021-09-01 12:49 UTC, pascalwengerter commented on packages/web-runtime/src/services/api.ts
> +    console.log('#############################################################################')
Not sure if this is part of the demo (and will get deleted) or if we should be logging here (and then maybe only in `dev` mode?)

2021-09-03 11:14 UTC, ownclouders commented
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/18834/45/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:59

2021-09-03 14:07 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/18837/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:36

2021-09-03 17:56 UTC, fschade commented on packages/web-runtime/src/container/api.ts
> +      throw new ApiError("route can't be blank", applicationRoute)
in the current version of the "application-manifest" we force to use routes. Int he class based which isn't exported right now the user has to call that api it's wown. So if he calls it without providing routes... it errors, if he skip it all ist fine.

2021-09-03 17:57 UTC, fschade commented on packages/web-runtime/src/container/api.ts
> +    route.path = `/${encodeURI(applicationId)}${route.path}`
good catch, definitely

2021-09-09 13:06 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +    route.path = `/${encodeURI(applicationId)}${route.path}`
We could only have double slashes if we'd allow leading or trailing slashes in application ids. I'd just forbid that application ids can consist of slahes. ;-) what do you think @LukasHirt ?

2021-09-09 20:11 UTC, LukasHirt commented on packages/web-runtime/src/container/api.ts
> +    route.path = `/${encodeURI(applicationId)}${route.path}`
How'd we enforce it? Documentation?

2021-09-09 20:15 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +    route.path = `/${encodeURI(applicationId)}${route.path}`
Exactly, that's what I thought. 😁 I'd like to have good documentation for the extension system soonish. A small hint that application ids need to be alphanumeric should be sufficient IMO.

2021-09-15 13:29 UTC, kulmann requested changes
Found one important thing: configuring an application in the config.json which is not reachable causes the full runtime to stop with a config error page. Extension loading should fail silently (with console error logging, but not by crashing the whole platform). Some other remarks in the comments.

2021-09-15 13:29 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +  navigationItems: ClassicApplicationScript['navItems']
Why not 
```suggestion
  navigationItems: ApplicationNavigationItem[]
```
? 🤔

2021-09-15 13:29 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +  navigationItems: ClassicApplicationScript['navItems']
Or in other words: you already introduced types, why not use them here? Instead you're creating a dependency to the `ClassicApplicationScript` which should not be needed in the (more) generic runtime API.

2021-09-15 13:29 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +  appTranslations: ClassicApplicationScript['translations']
Same here, why reference the `ClassicApplicationScript`? Would be nicer to introduce a dedicated translation type in `types.ts` and then reuse it here.

2021-09-15 13:29 UTC, kulmann commented on packages/web-runtime/src/container/api.ts
> +  quickActions: ClassicApplicationScript['quickActions']
Same here, why reference the `ClassicApplicationScript`?

2021-09-15 14:10 UTC, kulmann commented on packages/web-runtime/src/container/types.ts
> +export interface ApplicationQuickActions {
Hm ok, for compatibility reasons. I'll introduce a singular `ApplicationQuickAction` interface and use that for the values in the `ApplicationQuickActions` interface. Good enough for now.

2021-09-16 08:11 UTC, kulmann approved these changes
Took the liberty of fixing some minor things in this PR. Failing hard with the whole system on one application not being able to load is a no-go - but since the next release is 2 weeks ahead we'll have enough time to fix that in a different PR. Fine to merge this now! Thanks for all the urgently needed cleanup! ❤️

2021-09-16 08:25 UTC, ownclouders commented
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/19075/52/1
The following scenarios passed on retry:
- webUIFiles/download.feature:11

2021-09-16 09:56 UTC, ownclouders commented
Results for <strong>oC10SharingInternalUsersSharingIndicator</strong> https://drone.owncloud.com/owncloud/web/19079/28/1
The following scenarios passed on retry:
- webUISharingInternalUsersSharingIndicator/shareWithUsers.feature:154
- webUISharingInternalUsersToRootSharingIndicator/shareWithUsers.feature:98

2021-09-16 10:12 UTC, ownclouders commented
Results for <strong>oC10Files1</strong> https://drone.owncloud.com/owncloud/web/19079/12/1
The following scenarios passed on retry:
- webUIFilesActionMenu/versions.feature:15

2021-09-16 10:30 UTC, merged