[WIP] playwright for ci
owncloud/web pull request #5856
Opened 2021-09-30 10:28 UTC by fschade

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-09-30 12:27 UTC, pascalwengerter commented
Seems like you only commented out the "run acceptance tests" step in each pipeline, all the dependency installs etc get done nonetheless

2021-11-16 15:56 UTC, pascalwengerter requested changes
Placeholder feedback as a reminder we need to bring back unit tests before merging this one 🤡

2021-11-17 11:48 UTC, ownclouders commented
Results for <strong>oCISRename</strong> https://drone.owncloud.com/owncloud/web/20349/53/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-11-17 11:56 UTC, pascalwengerter commented
CI failure could've been flakyness or differences in drone config, rebased on current master and restarted

2021-11-17 12:36 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/20350/43/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:106

2021-11-17 12:46 UTC, merged