Use default app from app provider and early returns in fileActions
owncloud/web pull request #5970
Opened 2021-11-02 11:37 UTC by kulmann

## Description
Switch to early returns when evaluating the default action for a file. Also use the app provider without `app` param so that the app provider can decide on its own which app to use.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/5962

## Motivation and Context
Improve default action handling for files.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] changelog item
- [ ] fix app provider default 👀

2021-11-02 11:39 UTC, kulmann commented
At the moment the POST to e.g. `https://ocis.owncloud.test/app/open?file_id=MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjFkZTU3Yzg1LWY0NDItNDhjZS1iZWE4LTQzMjZkZmNjOGNjYw==` (= without app name) fails with a http 500 with message `error searching for app provider` - do you know details @wkloucek before I start to dig deeper?

2021-11-02 13:48 UTC, wkloucek commented
> At the moment the POST to e.g. `https://ocis.owncloud.test/app/open?file_id=MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3OjFkZTU3Yzg1LWY0NDItNDhjZS1iZWE4LTQzMjZkZmNjOGNjYw==` (= without app name) fails with a http 500 with message `error searching for app provider` - do you know details @wkloucek before I start to dig deeper?

Thanks for raising this. I had a look at the code and there is a bug regarding the default app handling.

Besides that we also have a conceptual issue regarding default apps. The backend has cases where there is no default app, but how do clients like Web know? Currently they just get an error.

2021-11-03 08:40 UTC, kulmann commented
> Besides that we also have a conceptual issue regarding default apps. The backend has cases where there is no default app, but how do clients like Web know? Currently they just get an error.

Hmm... actually, now thinking about this, I don't want to call the `open` endpoint without app name anymore. We currently have three kinds of file handlers in this order:
1: apps which are directly add to the web config (e.g. mediaviewer)
2: apps from the app provider
3: system actions (e.g. download or open in new tab, which we do for PDF files)

If there is no default in (2) we should continue in the list and pick a system action as default. There is one in any case (download).

2021-11-03 08:49 UTC, kulmann commented
This also means that we need the info about the default app from the app provider @wkloucek

2021-11-03 10:14 UTC, wkloucek commented
> This also means that we need the info about the default app from the app provider @wkloucek

https://github.com/cs3org/reva/pull/2230 implements that

2021-11-10 11:40 UTC, wkloucek commented
@kulmann https://github.com/owncloud/ocis/pull/2726 will bring https://github.com/cs3org/reva/pull/2230 into oCIS to unblock this PR.

2021-11-11 15:40 UTC, ownclouders commented
Results for <strong>oC10SharingPublicExpireAndRoles</strong> https://drone.owncloud.com/owncloud/web/20251/37/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-11-12 09:40 UTC, kulmann commented
Not blocked anymore thanks for @wkloucek :heart:

2021-11-15 10:58 UTC, pascalwengerter requested changes
First test with the wopi example revealed an `TypeError: action.handler is not a function` when clicking on an **.odt** file. Investigating further

2021-11-15 11:05 UTC, pascalwengerter commented
> First test with the wopi example revealed an `TypeError: action.handler is not a function` when clicking on an **.odt** file. Investigating further

Also, opening external apps via context menu fails with `Error fetching app information` and statuscode 500

2021-11-15 16:07 UTC, kulmann commented
> > First test with the wopi example revealed an `TypeError: action.handler is not a function` when clicking on an **.odt** file. Investigating further
> 
> Also, opening external apps via context menu fails with `Error fetching app information` and statuscode 500

Thanks, fixed it!

2021-11-15 16:26 UTC, pascalwengerter approved these changes
Works like a charm now 🧮

2021-11-16 08:12 UTC, merged