Draft: Sort before pagination
owncloud/web pull request #6136
Opened 2021-12-12 17:53 UTC by dschmidt

## Description
As reported in https://github.com/owncloud/web/issues/5687 sorting is broken for us as soon as we paginate.
The problem is that we paginate in our views and let `OcTable` do the sorting on the current page, which hardly makes any sense. Instead we need to sort first and paginate the sorted data afterwards.

I've extracted sorting from `OcTable` / `SortMixin` and moved it into a new composable.

This approach is great for testing the sorting logic and it also makes it super easy to wire up the sorting mode to the url (🥳 ), but I'm still not completely happy with the code ...

The sorting logic and the `OcTable` basically operate on the same configuration structure now, but the sorting logic lives outside the `ResourceTable` so we cannot pass the fields config from there into the sort composable. Building the whole config outside the `ResourceTable` isn't super straightforward either because the non-searching relevant properties of the fields depend on translation and possibly other data of the `ResourceTable` instance.

For now I've introduced and exported a `determineSortFields` function in the `ResourceTable` file ... which works, but it feels horribly wrong.

This is a PoC, let's discuss it tomorrow or so :) 

## Related Issue
- Fixes #5687 

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

https://user-images.githubusercontent.com/448487/145723655-94df5cc5-96ed-4c35-9f7e-7ffcbb177448.mp4

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2021-12-12 18:27 UTC, kulmann commented
Only read the description of your Pr so far, but one thing is important: IMO we need to move sorting out of the table entirely. We'll have a grid view soon. And we don't want to reimplement sorting for the grid view a second time but instead just reuse it. Let's discuss the rest tomorrow 👍🏻

2021-12-13 11:15 UTC, kulmann commented on packages/web-app-files/src/components/FilesList/ResourceTable.vue
> +    // FIXME: asc or desc
Reminder to fix the `FIXME`.

2021-12-13 11:15 UTC, kulmann commented on packages/web-app-files/src/composables/useSort/index.ts
> +  sortable?: MaybeRef<boolean>
`sortable` can also be a callback which is intended to transform a value into a sortable value.

2021-12-13 11:23 UTC, kulmann requested changes
breaks on empty folders 😁 probably because it can't read sortable fields from the "first item" for an empty folder

2021-12-19 19:16 UTC, dschmidt commented
> breaks on empty folders grin probably because it can't read sortable fields from the "first item" for an empty folder

I've added a HACK/workaround for this, that I don't quite understand ... maybe someone else can look into why that seems to be neccessary (and only in the case of `[]` as value).

The changes to the Personal page need to be ported to a bunch of other views supporting pagination.

If someone wants to take over this PR, as usual I'm fine with squashing commits etc :)

2021-12-20 16:34 UTC, kulmann commented
assigned myself, will take over this PR. Thanks for the work so far! 😍

2021-12-21 11:17 UTC, pascalwengerter reviewed
Great stuff in general, testing locally and seeing some console errors on the Shared with me page (related to dates IIRC), investigating..

2021-12-21 11:23 UTC, pascalwengerter commented
Found more problems related to sorting by date on the "Shared with Others" page, too

2021-12-21 11:46 UTC, kulmann commented
Share date, yeah... can confirm :-(

2021-12-21 19:10 UTC, kulmann commented
Sorting by share date, sort breaking on empty tables in SharedWithMe page and different sorting query params for the two different tables on the SharesWithMe page have been solved now. PR is ready for final review.

2021-12-22 09:21 UTC, pascalwengerter commented
Just tried the new "Shared with me" logic, two findings:
- sorting in the "Status" in the Pending table doesn't really make sense - the column only contains actions and items disappear from the table upon interaction
- after accepting/declining shares, they don't show up in the Accepted/Declined tables anymore 🤔 investigating the new route params now, no console errors

2021-12-22 09:22 UTC, pascalwengerter commented
> Just tried the new "Shared with me" logic, two findings:
> 
>     * sorting in the "Status" in the Pending table doesn't really make sense - the column only contains actions and items disappear from the table upon interaction
> 
>     * after accepting/declining shares, they don't show up in the Accepted/Declined tables anymore thinking investigating the new route params now, no console errors

Update: View mode didn't change anymore after sorting params were added to the route. Browsing back to a "raw" shared-with-me route makes accepted/declined shares work as expected

2021-12-22 09:31 UTC, kulmann commented
> Update: View mode didn't change anymore after sorting params were added to the route. Browsing back to a "raw" shared-with-me route makes accepted/declined shares work as expected

good spot, thank you!

2021-12-22 10:07 UTC, kulmann commented
> > Update: View mode didn't change anymore after sorting params were added to the route. Browsing back to a "raw" shared-with-me route makes accepted/declined shares work as expected
> 
> good spot, thank you!

... and fixed. It was a type issue. The view mode computed property was not an int anymore, but a string.

2021-12-22 10:10 UTC, pascalwengerter commented
> > > Update: View mode didn't change anymore after sorting params were added to the route. Browsing back to a "raw" shared-with-me route makes accepted/declined shares work as expected
> > 
> > 
> > good spot, thank you!
> 
> ... and fixed. It was a type issue. The view mode computed property was not an int anymore, but a string.

Can confirm, just checked and it's fixed. Not having the status be sortable in the "pending" table could be changed later from my perspective

2021-12-22 10:17 UTC, pascalwengerter approved these changes
Code-wise LGTM and works like a charm, kudos for the test coverage!

2021-12-22 10:49 UTC, merged

2021-12-22 23:00 UTC, dschmidt commented on packages/web-app-files/src/composables/useSort/index.ts
> -      return options.items
Ah this probably fixed the need for the double unref, nice!