Draft: Add app helpers
owncloud/web pull request #6156
Opened 2021-12-15 14:58 UTC by dschmidt

## Description
This extracts some file and folder loading/saving from mediaviewer and drawio apps and finally moves them into a central place.
Functions `getFileInfo`, `putFileContents` and `getFileContents` are based on https://github.com/owncloud/web/pull/6125/commits/68b7332d09184134391f29681c702fa9d93aae92 by @diocas 
Thanks and kudos for that!
I wanted to solve the routing a bit differently and it was easier for me to just copy the relevant parts instead of revoking parts of your commit. I hope this is fine for you, if you prefer I can probably mark the commit as being authored by us two or cherry pick and revoke the routing part. Just let me know, thanks!

Names are not great, typescript types are basically not there, the big composable file can possibly be split into more modules, etc....
This is a PoC and just lays a ground for dicussion.

## Related Issue

## Motivation and Context
Creating an app needs deep knowledge of the possible views in oC Web  (public, private, shared, ...) and knowledge about the structure of the store. Also app code should be rather resilient against structural changes in oC Web (as much as reasonably possible at least). That is why we should provide apps a stable-ish API to run against.
This PR adds a composable providing a bunch of helper functions/properties/... usually needed to write applications handling files.
Do we need to/can we/should we consider namespace handling, too?

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] Api Concept
- [ ] Types
- [ ] Proper modularization
- [ ] Tests
- [ ] Remove dependency of `web-pkg` on `web-app-files` (?)

2021-12-15 16:44 UTC, diocas commented
All fine for me :)
The only reason I separated into 2 routes was to have a nicer name. But @kulmann explained that by using `contextRouteName` we know how to get back to the previous view... And I guess this doesn't break our (CERNBox's) universal EOS urls, so all good.

Can we apply the same logic to the `external` app? (I opened a similar PR for that as well)

2021-12-15 16:49 UTC, dschmidt commented
I will look into it, my goal is certainly to unify URL handling accross all apps. For now I want to port apps shipped inside oC Web, in the long run this should become sort of a universal toolkit also for apps implemented externally.

2021-12-17 00:24 UTC, kulmann reviewed
Nice unification! Didn't look into every detail, but the approach and direction this is going are nice and helpful. 👍

2021-12-19 19:23 UTC, dschmidt commented
Naming:
We have a `useDefaults` composable, maybe `useAppDefaults` isn't a too bad name then.
packages/web-runtime/src/container/api.ts uses `applicationName`, so we should probably use that instead of `appName` here.


About the other functions and apis:
As we are not going to release this as public api too soon, we can revisit that at some point.
It should be tested, that mediaviewer and draw-io still work on all routes they support. I've only tested the personal file view and public links.

The composable can (and should) be split into more granular pieces but that can be done at a later point as well.

2022-01-06 16:25 UTC, ownclouders commented
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21637/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

2022-01-06 16:33 UTC, ownclouders commented
Results for <strong>oC10IntegrationApp1</strong> https://drone.owncloud.com/owncloud/web/21637/68/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-06 16:50 UTC, dschmidt commented
> I will look into it, my goal is certainly to unify URL handling accross all apps. For now I want to port apps shipped inside oC Web, in the long run this should become sort of a universal toolkit also for apps implemented externally.

I looked at it briefly, but not having a working wopi setup or something like that it's a bit hard for me to test. In the long run we should definitely look to streamline this...

2022-01-06 17:48 UTC, dschmidt commented
Okay, drone is green - sonarcloud probably fails because of the `FIXME` (right?), IMHO that's still fine. Adding types for the whole sdk client is way out of scope for this PR and I don't feel like marking it as TODO just to make sonarcloud happy :)

2022-01-06 17:48 UTC, dschmidt commented
From my POV this is good to go!

2022-01-06 17:50 UTC, dschmidt commented on packages/web-pkg/src/composables/useAppDefaults/useAppFileLoading.ts
> +    // If the mediaFile does not contain the downloadURL we fallback to the normal
```suggestion
    // If the resource does not contain the downloadURL we fallback to the normal
```

2022-01-18 11:18 UTC, kulmann requested changes

2022-01-18 11:18 UTC, kulmann commented on packages/web-pkg/src/composables/useAppDefaults/useClient.ts
> +  return (getCurrentInstance().proxy as unknown as any).$client
The files app has a `ClientService`, I'd like to utilize that here. Would need to be moved to `web-pkg` first, obviously. What do you think?

2022-01-18 13:24 UTC, kulmann commented on packages/web-pkg/src/composables/useAppDefaults/useAppFileLoading.ts
> +  const putFileContents = (
The name of the composable, `useAppFileLoading` seems to be misleading if we also have `putFileContents`.

2022-01-19 09:58 UTC, kulmann approved these changes
😍

2022-01-19 11:12 UTC, merged