enable lazy table cells and fix tests
owncloud/web pull request #6204
Opened 2021-12-31 15:22 UTC by fschade

## Description
since lazy table cell rendering has landed in ODS we also should use it in web, the feature is not enabled by default and must be enabled via the configuration (`"resourceTableLazy": true`). 

## Related Issue
- part of https://github.com/owncloud/web/issues/6046, store needs further optimization

## Motivation and Context
as written in linked issue, current views kinda slow and should be snappy instead. This is just one piece of it and wiill need further investigation.

## How Has This Been Tested?
- local installation, unit tests and integration tests.

## Types of changes
- [X] New feature (non-breaking change which adds functionality)
- [X] Technical debt
- [X] Tests

## Checklist:
- [X] Code changes
- [ ] Unit tests added

2021-12-31 15:54 UTC, ownclouders commented
Results for <strong>oC10SharingPublic1</strong> https://drone.owncloud.com/owncloud/web/21471/37/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2021-12-31 15:54 UTC, ownclouders commented
Results for <strong>oC10Files2</strong> https://drone.owncloud.com/owncloud/web/21471/17/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-03 13:49 UTC, kulmann commented
Currently blocked by https://github.com/owncloud/web/pull/6142

2022-01-03 15:14 UTC, kulmann requested changes
- See comment about the option name
- Please add a line to the docs about the new option

2022-01-03 15:14 UTC, kulmann commented on packages/web-runtime/src/store/config.js
> +    resourceTableLazy: true,
What do you think about giving this option a more generic name? When we add more view modes (next up: grid view), we could reuse the same option. What do you think about `displayResourcesLazy` or similar?

2022-01-03 19:42 UTC, pascalwengerter reviewed
Can't comment on the code quality since it'll rebased anyhow after the icons have been changed, but feels amazing in the UI already!
Would it be an improvement to switch to lazy loading of `rows` instead of `cells` from a UX perspective?

2022-01-04 09:56 UTC, kulmann commented
> Would it be an improvement to switch to lazy loading of `rows` instead of `cells` from a UX perspective?

Would be an additional improvement, but for now the cells are good. The extra work is better spent in cleaning up the vuex store.

2022-01-04 15:29 UTC, ownclouders commented
Results for <strong>oc10SharingIntUsers3</strong> https://drone.owncloud.com/owncloud/web/21555/32/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-04 16:23 UTC, ownclouders commented
Results for <strong>oC10SharingAccept</strong> https://drone.owncloud.com/owncloud/web/21557/15/1
The following scenarios passed on retry:
- webUISharingAcceptSharesToRoot/acceptShares.feature:108

2022-01-04 17:05 UTC, pascalwengerter commented
Restarting CI, only a single pipeline failed and that one works fine locally...

2022-01-05 14:28 UTC, kulmann approved these changes
Not sure if we want to have the dockerized configs with or without lazy tables. But that can be decided later on as well. PR is good to go from my POV 👍

2022-01-06 20:57 UTC, merged