Persist sorting per view
owncloud/web pull request #6290
Opened 2022-01-20 12:48 UTC by kulmann

## Description
This PR adds a new composable (`useRouteQueryPersisted`) which takes care of syncing non-default query params into the locale storage automatically. It has been hooked into the `useSort` and `usePagination` composables (optional, can be overwritten, e.g. with mocks for tests).

With this we now persist the sort choices into the local storage per view. I.e. navigating into subfolders will keep the same sort choices. Navigating to different views will restore the historic sort choices of that respective view.

## Related Issue
- Fixes https://github.com/owncloud/web/issues/5930

## Motivation and Context
Improve UX.

## How Has This Been Tested?
Not yet, unit tests need to be added/adapted.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] changelog item

2022-01-20 13:17 UTC, kulmann commented
cc @dschmidt since this touches composables you have been working on

2022-01-20 14:16 UTC, dschmidt approved these changes
This is really nice!

When I introduced the sort composable, I was annoyed I had to make the same adjustments in several locations - this nicely gets rid of those duplications. Love it!

2022-01-20 14:21 UTC, dschmidt commented on packages/web-app-files/src/composables/pagination/usePagination.ts
> +  return computed(() => parseInt(String(perPageQuery.value)))
```suggestion
  return computed(() => parseInt(String(unref(perPageQuery))))
```

2022-01-20 14:21 UTC, dschmidt commented on packages/web-pkg/src/composables/localStorage/useLocalStorage.ts
> +    () => variable.value,
```suggestion
    () => unref(variable),
```

2022-01-20 14:22 UTC, dschmidt commented on packages/web-pkg/src/composables/router/useRouteQueryPersisted.ts
> +      if (routeQueryVariable.value) {
```suggestion
      if (unref(routeQueryVariable)) {
```

2022-01-20 14:22 UTC, dschmidt commented on packages/web-pkg/src/composables/router/useRouteQueryPersisted.ts
> +      if (routeQueryVariable.value) {
and following :-D

2022-01-20 14:23 UTC, kulmann commented on packages/web-app-files/src/composables/sort/useSort.ts
> +
I'd also be fine with 
```
routeName: unref(options.routeName || useRouteName())
```
In fact, that looks much better 😅 What do you think?

2022-01-20 14:37 UTC, kulmann commented on packages/web-app-files/src/composables/sort/useSort.ts
> +
but `unref(options.routeName)` doesn't evaluate to false, does it?

2022-01-20 16:02 UTC, pascalwengerter requested changes
Items per page seems to mostly work fine, just produced a `This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!` for me once in Firefox

Shared with me:
- `[Vue warn]: Property or method "targetRoute" is not defined on the instance but referenced during render.` upon page navigation with only pending shares, pending&accepted and pending&accepted&declined shares
- Accepted&declined shares table persist the same preference, but I suppose that is fine for now

Shared with others:
- Sorting by name works
- Sorting by Share receiver is broken
- Sorting by Sharedate is broken

Shared via Link
- Sorting by name works
- Sorting by Share receiver is broken
- Sorting by Sharedate is broken

2022-01-21 07:59 UTC, kulmann commented
> Items per page seems to mostly work fine, just produced a `This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html for further details and to join the discussion on related tools and features!` for me once in Firefox

Is that related to this PR? 🤔 

> Shared with me:
> 
> * `[Vue warn]: Property or method "targetRoute" is not defined on the instance but referenced during render.` upon page navigation with only pending shares, pending&accepted and pending&accepted&declined shares

That's on master, but I fixed it now. The pending shares table was referencing a targetRoute variable that didn't exist anymore - just deleted it, because you can't click on resources in the pending shares table anyway, so there is no need for a target route. Additionally fixed, that the `declined` shares table had `are-resources-clickable` set to `true`, which doesn't make sense either, so I set `are-resources-clickable` to `true` now only for accepted shares, otherwise it's `false`.


> * Accepted&declined shares table persist the same preference, but I suppose that is fine for now

Yes, unfortunately the way the table is built this is not that easily changed, so I'd like to keep it for now. The better UX would be, that accepted and declined shares have their own sorting. Would like to look into that separately.


> Shared with others:
> 
> * Sorting by name works
> * Sorting by Share receiver is broken
> * Sorting by Sharedate is broken

Sorting by `Shared with` fixed - this was again a bug from current master. The fix was to handle `undefined` values during sorting by interpreting them as empty strings for sorting (`undefined.toString()` explodes, obviously).
Sorting by sharedate was not broken, but needed a page reload after clicking the broken `Shared with` sort button.
Same for `Shared via Link`

2022-01-22 13:54 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/22095/40/1
The following scenarios passed on retry:
- webUISharingExternal/federationSharing.feature:106

2022-01-22 13:57 UTC, ownclouders commented
Results for <strong>oC10iPhone3</strong> https://drone.owncloud.com/owncloud/web/22095/49/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:33

2022-01-22 13:57 UTC, ownclouders commented
Results for <strong>oC10XGAPortrait3</strong> https://drone.owncloud.com/owncloud/web/22095/45/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:35
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:33

2022-01-22 13:58 UTC, ownclouders commented
Results for <strong>oC10iPhone1</strong> https://drone.owncloud.com/owncloud/web/22095/47/1
The following scenarios passed on retry:
- webUIPrivateLinks/accessingPrivateLinks.feature:9

2022-01-22 14:30 UTC, dschmidt approved these changes

2022-01-22 14:48 UTC, ownclouders commented
Results for <strong>oC10SharingExternal</strong> https://drone.owncloud.com/owncloud/web/22099/40/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-22 15:29 UTC, ownclouders commented
Results for <strong>oC10SharingPermission</strong> https://drone.owncloud.com/owncloud/web/22100/35/1
The following scenarios passed on retry:
- webUISharingPermissionsUsers/sharePermissionsUsers.feature:21

2022-01-22 15:33 UTC, ownclouders commented
Results for <strong>oCISSharingBasic</strong> https://drone.owncloud.com/owncloud/web/22100/53/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-23 10:49 UTC, merged

2022-01-23 10:50 UTC, kulmann commented
Force merged without waiting for another CI run - the last one was green and the two commits didn't change anything that could explode in tests.