Fix publicLinkPassword in apps
owncloud/web pull request #6299
Opened 2022-01-21 21:31 UTC by dschmidt

## Description
Removes a nonsense check from `publicLinkPassword` computed.
The code was just introduced and never released, so we don't need a changelog entry imho.

The second change is unrelated but I stumbled upon this while debugging why files could not be shown in mediaviewer...
It seemed to still work even with the double encoding, so I'm not even sure how to use it to break something, so again no changelog needed imho.

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-01-21 21:54 UTC, ownclouders commented
Results for <strong>oC10Files5</strong> https://drone.owncloud.com/owncloud/web/22092/20/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-01-22 13:25 UTC, fschade requested changes
i would prefer to use URL for construction if nothing speaks against it

2022-01-22 13:25 UTC, fschade commented on packages/web-pkg/src/composables/useAppDefaults/useAppFileHandling.ts
>      return [url, combinedQuery].filter(Boolean).join('?')
can't we use `URL` to construct the url object?

2022-01-22 13:32 UTC, fschade approved these changes

2022-01-22 13:37 UTC, merged