Fix update of favorite star in right sidebar after click
owncloud/web pull request #6330
Opened 2022-01-27 20:51 UTC by kulmann

## Description
The favorite star in the right sidebar caused an error on click and didn't update itself then. This PR fixes that. Used to chance to clean up some code fragments on the way.

## Related Issue
- Fixes #6328

## Motivation and Context
Hardening

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-01-27 20:57 UTC, pascalwengerter requested changes
Code looks cleaner, doesn't resolve the issue for me yet, though. Both "staring via breadcrumb action menu" and "staring a folder in the sidebar actions when inside and not having selected anything" are broken

2022-01-27 22:18 UTC, kulmann commented
> Code looks cleaner, doesn't resolve the issue for me yet, though. Both "staring via breadcrumb action menu" and "staring a folder in the sidebar actions when inside and not having selected anything" are broken

Checked it out, apparently already broken in master. Fixed it with https://github.com/owncloud/web/pull/6330/commits/66d42693442a1249770e0a67299f8badf370139a in this PR

2022-01-27 22:49 UTC, ownclouders commented
Results for <strong>oCISFiles2</strong> https://drone.owncloud.com/owncloud/web/22230/56/1
The following scenarios passed on retry:
- webUIMarkdownEditor/markdownFile.feature:21

2022-01-27 22:53 UTC, ownclouders commented
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/22230/64/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

2022-01-28 12:47 UTC, pascalwengerter approved these changes

2022-01-28 12:47 UTC, merged