[tests-only] Adds version page object for e2e tests
owncloud/web pull request #6354
Opened 2022-02-02 11:24 UTC by grgprarup

## Description
This PR adds version page object for e2e tests

## Related Issue

- Part of https://github.com/owncloud/web/issues/6344

## Motivation and Context
There was no separate version page, this PR makes new version page which makes easier to organize and manage code.

## How Has This Been Tested?

- locally
- ci

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [x] E2E tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-02-02 11:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/web?pullRequest=6354) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/web?pullRequest=6354) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/web?pullRequest=6354) it.</sub>

2022-02-02 12:37 UTC, ScharfViktor requested changes

2022-02-02 12:37 UTC, ScharfViktor commented on tests/e2e/support/page/files/version.ts
> +  private readonly fileVersionSidebarXPath: string
I like it, but I think it's the Locator, not the string. I would suggest to do like here: https://playwright.dev/docs/test-pom

2022-02-02 12:37 UTC, ScharfViktor commented on tests/e2e/support/page/files/version.ts
> +    this.fileVersionSidebarXPath = '//*[@id="oc-file-versions-sidebar"]/table/tbody/tr'
and here we can do something like: `this.fileVersionSidebarXPath = page.locator('//*[@id="oc-file-versions-sidebar"]/table/tbody/tr')`

2022-02-03 09:08 UTC, ScharfViktor approved these changes

2022-02-03 09:11 UTC, ScharfViktor commented
looks good to me. Thanks for the input. Perhaps @pascalwengerter can comment on something

2022-02-03 10:47 UTC, SwikritiT reviewed
LGTM

2022-02-03 12:39 UTC, phil-davis approved these changes

2022-02-03 13:23 UTC, merged