fix variable name in error object
owncloud/web pull request #6413
Opened 2022-02-10 11:04 UTC by individual-it

## Description
the variable name should be `error.resourceName`, `error.resource` is not used anywhere

## Related Issue

- Fixes #6412 
- part of #6337

## Motivation and Context
found when cleaning up unit test log messages:
```
  console.warn
    Cannot evaluate expression: resourceName

      356 |         title = this.$gettext('Failed to move "%{resourceName}"')
      357 |         this.showMessage({
    > 358 |           title: this.$gettextInterpolate(title, { resourceName: errors[0]?.resourceName }, true),
          | ^
      359 |           status: 'danger'
      360 |         })
      361 |         return

      at Object.evalInContext (node_modules/vue-gettext/dist/vue-gettext.js:280:21)
      at node_modules/vue-gettext/dist/vue-gettext.js:293:28
          at String.replace (<anonymous>)
      at Function.interpolate (node_modules/vue-gettext/dist/vue-gettext.js:247:24)
      at _callee5$ (packages/web-app-files/src/views/Personal.vue:358:1)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:293:22)
```

## How Has This Been Tested?
- reproducing example in #6412
- added assertion in unit test

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [x] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-02-10 11:47 UTC, ownclouders commented
Results for <strong>oC10SharingExternalRoot</strong> https://drone.owncloud.com/owncloud/web/22648/42/1
The following scenarios passed on retry:
- webUISharingExternalToRoot/federationSharing.feature:378

2022-02-10 11:47 UTC, ownclouders commented
Results for <strong>oC10SharingPermToRoot</strong> https://drone.owncloud.com/owncloud/web/22648/35/1
The following scenarios passed on retry:
- webUISharingPermissionToRoot/sharePermissionsUsers.feature:113

2022-02-10 11:48 UTC, ownclouders commented
Results for <strong>oCISFiles1</strong> https://drone.owncloud.com/owncloud/web/22648/55/1
The following scenarios passed on retry:
- webUIDeleteFilesFolders/deleteFilesFolders.feature:253

2022-02-10 14:46 UTC, kulmann requested changes
Good find and fix, thank you! 💪  Small small nitpicks, see comments below.

2022-02-10 14:46 UTC, kulmann commented on changelog/unreleased/bugfix-error-message-move
> +We fixed the error message when moving an item via drag-and-drop failed, not it shows the correct name of the item.
```suggestion
We fixed the error message when moving an item via drag-and-drop failed, now it shows the correct name of the item.
```

2022-02-10 14:46 UTC, kulmann commented on packages/web-app-files/tests/unit/views/Personal.spec.js
> +      //
leftover line?

2022-02-10 23:08 UTC, dschmidt commented on changelog/unreleased/bugfix-error-message-move
> +Bugfix: Failed move by drag 'n drop don't show the resource name in the error
```suggestion
Bugfix: Failed move by drag'n'drop doesn't show the resource name in the error
```

2022-02-11 03:09 UTC, individual-it commented
@dschmidt @kulmann thank you for your reviews, that have been rubbish mistakes. I've fixed them, please review again

2022-02-11 07:06 UTC, dschmidt commented on changelog/unreleased/bugfix-error-message-move
> +Bugfix: Failed move by drag'n drop doesn't show the resource name in the error
```suggestion
Bugfix: Failed move by drag'n'drop doesn't show the resource name in the error
```

2022-02-11 07:43 UTC, ownclouders commented
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/22673/66/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:94

2022-02-11 08:09 UTC, kulmann approved these changes

2022-02-11 08:09 UTC, merged