Space quota
owncloud/web pull request #6477
Opened 2022-02-24 10:23 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-03-01 15:23 UTC, ownclouders commented
Results for <strong>oCISSharingAndUpload</strong> https://drone.owncloud.com/owncloud/web/23154/66/1
The following scenarios passed on retry:
- webUIUpload/uploadEdgecases.feature:109

2022-03-01 15:26 UTC, ownclouders commented
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/23154/65/1
The following scenarios passed on retry:
- webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:62

2022-03-02 08:17 UTC, JanAckermann commented on packages/web-app-files/src/views/spaces/Project.vue
> +
Just for now

2022-03-02 09:43 UTC, ownclouders commented
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23164/69/1
The following scenarios passed on retry:
- webUITrashbinRestore/trashbinRestore.feature:46

2022-03-03 09:32 UTC, ownclouders commented
Results for <strong>oC10Files5</strong> https://drone.owncloud.com/owncloud/web/23215/20/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-03-03 09:32 UTC, ownclouders commented
Results for <strong>oC10IntegrationNotifications</strong> https://drone.owncloud.com/owncloud/web/23215/70/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.

2022-03-03 10:19 UTC, ownclouders commented
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/23218/67/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkPublicActions.feature:44

2022-03-03 10:47 UTC, JammingBen commented
Works well for me, one small detail I've found: Some options are hidden because the dropdown does not exceed the modal window.

![image](https://user-images.githubusercontent.com/50302941/156549380-97329a80-5c06-4ae2-a9ec-0cc0fd1011c9.png)

2022-03-03 11:58 UTC, JanAckermann commented
@JammingBen thx for feedback, problem with dropdown is in ods,  @pascalwengerter opened a pr

2022-03-03 14:43 UTC, ownclouders commented
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/23228/72/1
The following scenarios passed on retry:
- webUIUpload/upload.feature:111

2022-03-03 14:44 UTC, ownclouders commented
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23228/69/1
The following scenarios passed on retry:
- webUITrashbinDelete/trashbinDelete.feature:143

2022-03-04 11:04 UTC, ownclouders commented
Results for <strong>oCISSharingPublic2</strong> https://drone.owncloud.com/owncloud/web/23271/68/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:57

2022-03-04 11:05 UTC, ownclouders commented
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/23271/65/1
The following scenarios passed on retry:
- webUISharingFolderAdvancedPermissionMultipleUsers/sharedFolderWithMultipleUsersAdvancedPermissions.feature:65

2022-03-04 11:06 UTC, ownclouders commented
Results for <strong>oCISSharingPublic1</strong> https://drone.owncloud.com/owncloud/web/23271/67/1
The following scenarios passed on retry:
- webUISharingPublicBasic/publicLinkCreate.feature:190

2022-03-04 11:06 UTC, ownclouders commented
Results for <strong>oCISTrashbinUploadMoveJourney</strong> https://drone.owncloud.com/owncloud/web/23271/69/1
The following scenarios passed on retry:
- webUITrashbinDelete/trashbinDelete.feature:56

2022-03-04 16:20 UTC, kulmann requested changes
some small nitpicks 🙈

2022-03-04 16:20 UTC, kulmann commented on packages/web-app-files/tests/unit/components/Spaces/ReadmeContentModal.spec.js
> +describe('ReadeContentModal', () => {
```suggestion
describe('ReadmeContentModal', () => {
```

2022-03-04 16:20 UTC, kulmann commented on changelog/unreleased/enhancement-space-quota
> +We have implemented a way to update the space's quota
```suggestion
We have implemented a way to update the quota of a space
```

2022-03-04 16:20 UTC, kulmann commented on packages/web-app-files/src/mixins/spaces/actions/editQuota.js
> +          class: 'oc-files-actions-edit-quota-content-trigger'
```suggestion
          class: 'oc-files-actions-edit-quota-trigger'
```

2022-03-04 16:20 UTC, kulmann commented on packages/web-app-files/src/views/spaces/Project.vue
> +        <quota-modal v-if="quotaModalIsOpen" :cancel="closeQuotaModal" :space="space"></quota-modal>
You could write this as a self closing tag (same for the readme content modal), which is good practice IMO.

2022-03-04 16:20 UTC, kulmann commented on packages/web-app-files/src/components/Spaces/QuotaModal.vue
> +          v-text="$gettext('Select an item or enter your own value')"
```suggestion
          v-text="$gettext('Select a quota option or enter your own value')"
```

2022-03-04 16:20 UTC, kulmann commented on packages/web-app-files/src/components/Spaces/QuotaModal.vue
> +            title: this.$gettext('Space quota was edited successfully')
```suggestion
            title: this.$gettext('Space quota was changed successfully')
```

2022-03-04 16:37 UTC, kulmann approved these changes
Superb 👌 🥇

2022-03-05 11:23 UTC, ownclouders commented
Results for <strong>oC10XGAPortrait3</strong> https://drone.owncloud.com/owncloud/web/23304/46/1
The following scenarios passed on retry:
- webUISharingPublicDifferentRoles/shareByPublicLinkDifferentRoles.feature:33

2022-03-05 11:38 UTC, merged