Add test for changing role
owncloud/web pull request #6557
Opened 2022-03-09 09:39 UTC by SwikritiT

## Description
This PR was made by a automated script.
This is a update of drone.star file.

## Related Issue
- Part of issue:

2022-03-09 09:52 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/23424/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23424/tracing/alice-shares-folder-with-file-to-brian-alice-2022-3-9-09-51-55.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/23424/tracing/alice-shares-folder-with-file-to-brian-brian-2022-3-9-09-52-08.zip 


</p></details>

2022-03-22 10:18 UTC, SwikritiT commented
This PR needs to be merged first https://github.com/owncloud/web/pull/6541

2022-03-22 10:28 UTC, pascalwengerter reviewed
CI failed with linting errors. Also please wait for @fschade's feedback (he's not in the office today) on E2E tests before merging

2022-03-24 13:42 UTC, fschade requested changes
please see comments, thanks for you contribution.

2022-03-24 13:42 UTC, fschade commented on tests/e2e/cucumber/features/integrations/link.feature
> +    When "Alice" logs in
Please do not log in alice again, just keep her logged in the previous steps, then at the end log her out again.

Logging out is at the needed to tell playwright that the page context can be closed and de-registered.
The only reason to log-out and then re-login inside a test is when the steps between those take longer then the timeout from playwright.

2022-03-24 13:42 UTC, fschade commented on tests/e2e/support/objects/app-files/link/actions.ts
> +const fillPublicLinK = async (page, name, role, dateOfExpiration, password): Promise<void> => {
the K at the end should be lower-case.
Please also use an object arg in the function which makes a future refactoring more easy.

2022-03-24 13:42 UTC, fschade commented on tests/e2e/support/objects/app-files/link/index.ts
> +    await this.#page.goto(startUrl)
why not just use `args.newName` here, then we can skip all the boilerplate above.

2022-04-04 05:06 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/24392/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/24392/tracing/public-link-alice-2022-4-4-05-00-30.zip 


</p></details>

<!-- id: pr-6557 -->

2022-04-29 09:09 UTC, fschade commented
@SwikritiT can you rebase please

2022-04-29 09:26 UTC, pascalwengerter commented
> @SwikritiT can you rebase please

Just merged #6541 so rebasing should be simpler (I hope 😬 )

2022-04-29 09:27 UTC, pascalwengerter commented
Also, please use the "Squash and merge" option here (or squash commits locally while rebasing)

2022-05-04 12:03 UTC, kiranparajuli589 commented on tests/e2e/support/objects/app-files/link/actions.ts
> +  await page.locator('#files-file-link-add').click()
use var

2022-05-04 12:03 UTC, kiranparajuli589 commented on tests/e2e/support/objects/app-files/link/actions.ts
> +            `//*[@data-test-resource-name="%s"]/ancestor::tr//button[contains(@class, "files-quick-action-collaborators")]`,
use var

2022-05-05 15:43 UTC, fschade approved these changes
LGTM 🎸  Thanks for taking care

2022-05-05 15:43 UTC, merged