Use shared web-lint-config
owncloud/web pull request #6715
Opened 2022-04-01 15:43 UTC by dschmidt

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-04-05 11:35 UTC, fschade commented
regarding deps:
things like eslint or eslint-rules should go into peerDependencies, as a result the consuming application is responsible providing them.

In our monorepo it's not that important (!!only here, not the published version of those rules) because they all end up in roots node_modules.

a good read is https://withblue.ink/2020/06/07/is-this-a-dependency-or-devdependency.html

2022-04-05 11:37 UTC, fschade commented
@dschmidt can you explain what you mean with version strategy? i think first and foremost we have to decide how we publish those kind of individual packages.... e.g. lerna, ....

then the versions should be independent and we could follow semver.

2022-04-05 13:21 UTC, fschade commented on packages/tsconfig/tsconfig.json
> +{
would love o have the schema here

```
...
  "$schema": "https://json.schemastore.org/tsconfig",
...
```

2022-06-15 07:57 UTC, kulmann requested changes
Found one missed `@owncloud` to `@ownclouders` rename. ;-) Could you also rebase this PR? it has some conflicting files.

2022-06-15 07:57 UTC, kulmann commented on .prettierrc.json
> +"@owncloud/prettier-config"
```suggestion
"@ownclouders/prettier-config"
```

2022-10-08 07:42 UTC, closed without merging