[WIP] Add Contextual Helpers
owncloud/web pull request #6750
Opened 2022-04-07 11:42 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-04-11 11:37 UTC, pascalwengerter reviewed
Shall we add a config option to disable/enable contextual helpers from an admin's perspective?

2022-04-21 10:59 UTC, ownclouders commented
Results for <strong>oC10SharingIntGroupsToRoot</strong> https://drone.owncloud.com/owncloud/web/24797/29/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalGroupsToRootEdgeCases-shareWithGroupsEdgeCases_feature-L37.png
 ![webUISharingInternalGroupsToRootEdgeCases-shareWithGroupsEdgeCases_feature-L37.png](https://cache.owncloud.com/public/owncloud/web/24797/screenshots/webUISharingInternalGroupsToRootEdgeCases-shareWithGroupsEdgeCases_feature-L37.png) 


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.


<!-- id: pr-6750 -->

2022-04-21 11:37 UTC, JanAckermann approved these changes
NICE!

2022-04-21 11:52 UTC, pascalwengerter requested changes

2022-04-21 11:52 UTC, pascalwengerter commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
> +      <oc-contextual-helper v-if="resourceIsSpace && helpersEnabled" v-bind="spaceAddMemberHelp" />
Would it make sense to reduce this to one OcContextualHelper with only `v-if="helpersEnabled"` and handle the spaces differentiation in the v-bind computed property?

2022-04-21 11:52 UTC, pascalwengerter commented on yarn.lock
> +"owncloud-design-system@npm:^13.1.0-rc.5":
Should come with a changelog item ;)

2022-04-21 14:52 UTC, merged

2022-06-02 08:08 UTC, pascalwengerter commented
> can't see the helpers - where have they gone?

Fixed in #7084 by making them opt-out (I guess oCIS never opted in in the first place)