Sentry as option
owncloud/web pull request #6759
Opened 2022-04-07 21:05 UTC by diocas

Would you take this? This is quite useful for us to get user's issues without having to wait for a ticket.
I've made it optional and configurable.
But.. Our centrally managed Sentry instance doesn't run the latest version, so the config/package version in here is also not the latest.

2022-04-07 21:33 UTC, ownclouders commented
Results for <strong>oCISSharingPerm3</strong> https://drone.owncloud.com/owncloud/web/24585/66/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L50.png
 ![webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L50.png](https://cache.owncloud.com/public/owncloud/web/24585/screenshots/webUISharingFolderAdvancedPermissionMultipleUsers-sharedFolderWithMultipleUsersAdvancedPermissions_feature-L50.png) 


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.


<!-- id: pr-6759 -->

2022-04-07 22:07 UTC, dschmidt requested changes
In general personally (not speaking for team as a whole) I'm a fan of Sentry and of providing this. 🎉 

But I'm not happy with the PR as it is right now:

- I'm not a fan of the `*` imports
  Especially not where you changed the existing import.. Please use named imports (and maybe rename setUser to setSentryUser or sentrySetUser or something for more clarity)

- We should not introduce outdated dependencies
  Why can't you use an up to date version? Did they really have breaking changes?

2022-04-08 06:58 UTC, diocas commented
Thanks for the comments.
Yes, the latest versions are not compatible with the older. The biggest problem is that they introduced a new message that I cannot disable, and this would result in tons of errors.
I can try to see if we can update our central version.

2022-04-29 15:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/web?pullRequest=6759) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/web?pullRequest=6759) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: diocas<br/>:x: javfg<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/web?pullRequest=6759) it.</sub>

2022-04-29 15:11 UTC, javfg commented
Sorry for the commit message, I was meaning to upload that to my fork. :)

2022-05-03 12:57 UTC, diocas commented
@dschmidt now that @javfg did some improvements, can you do another review?

2022-05-12 14:47 UTC, pascalwengerter approved these changes
I'm fine with these changes (even though it adds 300kb to the vendor bundle), thanks for updating the dependency in the meantime! @dschmidt what about you?

2022-05-12 15:57 UTC, pascalwengerter commented on packages/web-runtime/src/container/bootstrap.ts
> +import Vue from 'vue'
As noted, please rebase and revert the change back to importing VueConstructor instead of Vue (and usage below, ofc)

2022-05-13 14:24 UTC, pascalwengerter commented on packages/web-runtime/src/container/bootstrap.ts
> +  if (runtimeConfiguration.sentry?.dsn) {
Also please add this to the docs with a quick note on how to enable

2022-05-16 10:18 UTC, javfg commented
Hey @pascalwengerter @dschmidt, I've applied the suggestions you requested. Can you take a look?

2022-05-16 10:20 UTC, pascalwengerter commented
> Hey @pascalwengerter @dschmidt, I've applied the suggestions you requested. Can you take a look?
> 
> Thanks!

Hey, yes it does look good but I reckon you'll need to rebase on the most recent `web` master one more time due to merge conflicts 🥴

2022-05-16 10:34 UTC, javfg commented
> > Hey @pascalwengerter @dschmidt, I've applied the suggestions you requested. Can you take a look?
> > Thanks!
> 
> Hey, yes it does look good but I reckon you'll need to rebase on the most recent `web` master one more time due to merge conflicts woozy_face

Just did, but the CI is still breaking. Did I miss something?

2022-05-16 10:36 UTC, pascalwengerter commented on packages/web-runtime/package.json
> +<<<<<<< HEAD
@javfg 👀

2022-05-16 11:07 UTC, javfg commented on packages/web-runtime/package.json
> +<<<<<<< HEAD
Sorry about that, should be fixed now.

2022-05-16 11:56 UTC, pascalwengerter approved these changes

2022-05-16 11:56 UTC, merged