Creating user via Graph in e2e tests and UI tests
owncloud/web pull request #6827
Opened 2022-04-28 09:37 UTC by ScharfViktor

Step 1:
- e2e tests with ocis use graphApi
Steps 2: 
- UI tests with ocis use graphApi

2022-04-28 09:39 UTC, pascalwengerter requested changes
Missing the middleware version bump in .drone.star

2022-04-28 09:42 UTC, pascalwengerter commented
> Missing the middleware version bump in .drone.star

I'm an idiot, we bumped it already yesterday as part of the Uppy-PR. Happy to merge if CI turns green

2022-04-28 09:42 UTC, ScharfViktor commented
> Missing the middleware version bump in .drone.star


https://github.com/owncloud/web/blob/97097063e15d2fe7961bcec863afaa540e17375e/.drone.star#L23

2022-04-28 10:20 UTC, ownclouders commented
Results for <strong>oCISSharingAutocompletion</strong> https://drone.owncloud.com/owncloud/web/24974/63/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletion_feature-L182.png
 ![webUISharingAutocompletion-shareAutocompletion_feature-L182.png](https://cache.owncloud.com/public/owncloud/web/24974/screenshots/webUISharingAutocompletion-shareAutocompletion_feature-L182.png) 

### webUISharingAutocompletion-shareAutocompletion_feature-L56.png
 ![webUISharingAutocompletion-shareAutocompletion_feature-L56.png](https://cache.owncloud.com/public/owncloud/web/24974/screenshots/webUISharingAutocompletion-shareAutocompletion_feature-L56.png) 

### webUISharingAutocompletion-shareAutocompletion_feature-L66.png
 ![webUISharingAutocompletion-shareAutocompletion_feature-L66.png](https://cache.owncloud.com/public/owncloud/web/24974/screenshots/webUISharingAutocompletion-shareAutocompletion_feature-L66.png) 


</p></details>

<!-- id: pr-6827 -->

2022-04-28 10:27 UTC, fschade commented on tests/e2e/support/api/graph/index.ts
> +export { createUser } from './user'
can be handled in one export e.g. `export { createUser, deleteUser } from './user'` or even `export * from './user'`

2022-04-28 10:28 UTC, fschade commented on tests/e2e/support/api/graph/user.ts
> +  const response = await request({
`const response = await request({
    method: 'POST',
    path: join('graph', 'v1.0', 'users'),
    body,
    user: admin
  })`

2022-04-28 10:29 UTC, fschade commented on tests/e2e/support/api/graph/user.ts
> +export const createUser = async ({ user, admin }: { user: User; admin: User }): Promise<void> => {
can we return the user here too? `: Promise<User>`

2022-04-28 10:30 UTC, fschade requested changes
found some smaller improvements, nothing crucial.
The me.ts file looks obsolete to me, can we refactor the ma func into user.ts too?

2022-04-28 10:34 UTC, ScharfViktor commented
> 

Good idea. I'll move "me" to "user"

2022-04-28 10:38 UTC, ScharfViktor commented
e2e tests passed. UI tests as expected failed. I'm doing fix after review and go to step 2

2022-04-29 13:03 UTC, ScharfViktor commented
CI is green. could you do a review?

before merge: need change - OCIS_COMMITID and  OC_TESTING_MIDDLEWARE

2022-05-02 07:54 UTC, pascalwengerter approved these changes
LGTM, please use the squash-merge option :) we need to take care of the flaky test next!

2022-05-02 07:55 UTC, fschade approved these changes
LGTM 🎸

2022-05-02 07:56 UTC, merged