Config option for hoverable quick actions
owncloud/web pull request #7022
Opened 2022-05-20 09:27 UTC by elizavetaRa

## Description
Adds the possibility to add hover effect for quick actions with the option "hoverableQuickActions" in config.json
The hover effect applies to "edit name", "add people" and "copy quicklink" actions in the corresponding hovered row.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/7021

## Motivation and Context
For CERNBox we don't want to show quick actions for each row, just for hovered ones

2022-05-20 10:05 UTC, ownclouders commented
Results for <strong>oC10iPhone3</strong> https://drone.owncloud.com/owncloud/web/25753/51/1
:boom: The acceptance tests pipeline failed. The build has been cancelled.


<!-- id: pr-7022 -->

2022-05-23 10:11 UTC, kulmann requested changes
Works like a charm - still have one change request: could you please add a description for the option to the options section in `docs/getting-started.md`?

2022-05-24 09:11 UTC, javfg commented
> Works like a charm - still have one change request: could you please add a description for the option to the options section in `docs/getting-started.md`?

Fixed! I also added a default (`false`), and made sure the buttons don't disappear if the user does not have a mouse (to avoid pain in phones/tablets).

2022-05-31 07:53 UTC, kulmann approved these changes
LGTM 👍

2022-05-31 07:53 UTC, merged