Use 'uploadDataDuringCreation' option when uploading via tus
owncloud/web pull request #7111
Opened 2022-06-10 12:59 UTC by JammingBen

## Description

## Related Issue
- https://github.com/owncloud/web/issues/7066

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2022-06-10 20:21 UTC, kulmann requested changes

2022-06-10 20:21 UTC, kulmann commented on packages/web-runtime/src/composables/upload/useUpload.ts
>  export interface UppyResource {
Could you please add a comment that this interface MUST never contain complex types / MUST always consist of primitive types only? With the serialization reasoning. I guess that's a fair warning that should stay in the code to not run into the same trap again in the future.

2022-06-10 20:21 UTC, kulmann commented on packages/web-runtime/src/composables/upload/useUpload.ts
> +    routeStorageId?: string
For the share jail / `SharedResource.vue` we also need the `shareId` as additional param. That doesn't come from `route.params` but `route.query` though.

2022-06-10 20:21 UTC, kulmann commented on changelog/unreleased/enhancement-upload-data-during-creation
> +Enhancement: Upload data during creation
I think the bugfix is worth a separate changelog item. 🚀

2022-06-13 08:23 UTC, kulmann commented on packages/web-runtime/src/services/uppyService.ts
> +      uploadDataDuringCreation: true
can we use capabilities here? the tus plugin is announced in the capabilities AFAIR.

2022-06-13 08:41 UTC, kulmann approved these changes
Nice 💪

2022-06-13 08:48 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/26156/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/26156/tracing/unstructured-collection-of-testable-space-interactions-alice-2022-6-13-08-46-58.zip 


</p></details>

<!-- id: pr-7111 -->

2022-06-13 12:10 UTC, merged