Add draft for permissionless/internal/alias-link shares for oCIS
owncloud/web pull request #7133
Opened 2022-06-15 15:23 UTC by pascalwengerter

## Description
Cleaning up my local git stash and came across this draft. Needs concepting how to properly turn this into an oCIS-only feature.

## Related Issue
- Fixes _tbd_ (I'm confident it exists somewhere 😅 )

2022-06-29 13:12 UTC, pascalwengerter commented
This does now work on the link-creator side, but I run into problems when trying to open the (permissionless) link - I'd expect it to render the login form, but it shows an error page (with a 401 when listing drives)

2022-07-07 21:19 UTC, kulmann commented
@pascalwengerter I took the liberty of rebasing this PR, as the public link resolving has changed in the web runtime today (see https://github.com/owncloud/web/pull/7072 for reference). However, whenever I want to create an internal link I get `invalid permissions` from the backend. Can you confirm that?

2022-07-15 09:42 UTC, pascalwengerter commented
> > @pascalwengerter I took the liberty of rebasing this PR, as the public link resolving has changed in the web runtime today (see #7072 for reference). However, whenever I want to create an internal link I get `invalid permissions` from the backend. Can you confirm that?
> 
> Did some investigation now and can confirm it doesn't work - I thought we had implemented the necessary changes in the SDK already, but getting an `invalid permissions` webdav response when trying to sending e.g. a "0" as zero-permission (sending _nothing_ doesn't work because that is the standard behavior when updating links without touching permissions). I've opened [an issue in the SDK](https://github.com/owncloud/owncloud-sdk/issues/1114)

Turns out sending a `0` permission is enough, it does work with https://github.com/cs3org/reva/pull/3079 (stopped CI, this PR needs a rebase & review once Julian's PR is merged in reva and then in oCIS and the oCIS commit ID is bumped)!

2022-07-15 09:43 UTC, pascalwengerter commented
> > > @pascalwengerter I took the liberty of rebasing this PR, as the public link resolving has changed in the web runtime today (see #7072 for reference). However, whenever I want to create an internal link I get `invalid permissions` from the backend. Can you confirm that?
> > 
> > 
> > Did some investigation now and can confirm it doesn't work - I thought we had implemented the necessary changes in the SDK already, but getting an `invalid permissions` webdav response when trying to sending e.g. a "0" as zero-permission (sending _nothing_ doesn't work because that is the standard behavior when updating links without touching permissions). I've opened [an issue in the SDK](https://github.com/owncloud/owncloud-sdk/issues/1114)
> 
> Turns out sending a `0` permission is enough, it does work with [cs3org/reva#3079](https://github.com/cs3org/reva/pull/3079) (stopped CI, this PR needs a rebase & review once Julian's PR is merged in reva and then in oCIS and the oCIS commit ID is bumped)!

Ideally we also get an E2E test for alias links in oCIS to make sure they don't break unnoticed in the near future

2022-07-21 09:57 UTC, kulmann commented
This PR handles **creating** internal / permissionless links, that works with updated ocis/reva as you mentioned. Respective commit id has been bumped in web already, so a rebase was sufficient. But: resolving an internal link is not handled in the public link resolve page. I'd like to merge this PR but flip the default of the capability to internal links being disabled, until we implement resolving internal links in a separate PR. Do you agree @pascalwengerter ?

2022-07-21 10:11 UTC, pascalwengerter commented
> This PR handles **creating** internal / permissionless links, that works with updated ocis/reva as you mentioned. Respective commit id has been bumped in web already, so a rebase was sufficient. But: resolving an internal link is not handled in the public link resolve page. I'd like to merge this PR but flip the default of the capability to internal links being disabled, until we implement resolving internal links in a separate PR. Do you agree @pascalwengerter ? 

Please do push to this PR as you deem necessary, I don't have any preference on how to proceed here ;)

2022-08-03 09:50 UTC, JammingBen commented
I rebased and updated the PR to go along with current master. No idea why the condition coverage does not cover `availableRoleOptions()` though. Locally, the tests call this method and reach the updated return statement 🤷 

Besides that, this should be ready for review. LGTM to me, although I'm not too invested in the topic.

2022-08-03 11:20 UTC, kulmann requested changes
Some nitpicks (see comments). Also: please update the ocis commit id in `.drone.env` to one after the alias capability value has changed in ocis.

2022-08-03 11:20 UTC, kulmann commented on changelog/unreleased/enhancement-permissionless-links
> +Enhancement: Permissionsless (internal) link shares
```suggestion
Enhancement: Permissionless (internal) link shares
```

2022-08-03 11:20 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
> +        this.capabilities.files_sharing?.public?.can_edit,
Let's introduce capability composables for these two capabilities (look for `useCapability...` for examples).

2022-08-03 11:51 UTC, JammingBen commented
Arghs I forgot the `.drone.env`, coming up next

2022-08-09 07:52 UTC, kulmann approved these changes

2022-08-09 14:52 UTC, merged