Edit user personal quota
owncloud/web pull request #7182
Opened 2022-06-27 09:46 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-06-28 12:26 UTC, JanAckermann commented on packages/web-app-user-management/src/views/Users.vue
>        })
Mock data, TBD

2022-08-01 09:22 UTC, kulmann commented
As far as I know this PR is on hold because some backend changes are to be done first. @JanAckermann do you have an updated status on that?

2022-08-01 09:27 UTC, JanAckermann commented
@kulmann still waiting for the backend implementation

2022-08-08 17:07 UTC, JanAckermann commented
WIP only blocked by https://github.com/owncloud/ocis/issues/4328

2022-08-08 20:55 UTC, JanAckermann commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +        <span v-else>NO DRIVE NO QUOTA</span>
TBD: What to show if user has no drive and quota, can not be set? 
@tbsbdr

2022-08-08 21:52 UTC, ownclouders commented
Results for <strong>oCISSharingAutocompletion</strong> https://drone.owncloud.com/owncloud/web/27422/63/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L43.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L43.png](https://cache.owncloud.com/public/owncloud/web/27422/screenshots/webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L43.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L78.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L78.png](https://cache.owncloud.com/public/owncloud/web/27422/screenshots/webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L78.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L79.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L79.png](https://cache.owncloud.com/public/owncloud/web/27422/screenshots/webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L79.png) 

### webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L80.png
 ![webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L80.png](https://cache.owncloud.com/public/owncloud/web/27422/screenshots/webUISharingAutocompletion-shareAutocompletionSpecialChars_feature-L80.png) 


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.


<!-- id: pr-7182 -->

2022-08-09 18:22 UTC, kulmann requested changes

2022-08-09 18:22 UTC, kulmann commented on packages/web-app-files/src/components/Spaces/QuotaModal.vue
> +    this.selectedOption = this.space.spaceQuota.total
```suggestion
    this.selectedOption = this.space.spaceQuota.total || 0
```
We want an int here, right? So if `total` is `undefined` we need to fall back to `0` then.

2022-08-09 18:22 UTC, kulmann commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +          :total-quota="editUser.drive.quota.total"
```suggestion
          :total-quota="editUser.drive.quota.total || 0"
```

2022-08-09 18:22 UTC, kulmann commented on packages/web-app-user-management/src/views/Users.vue
> +            <oc-loader v-if="loadAdditionalUserDataTask.isRunning" />
```suggestion
            <oc-loader v-if="loadAdditionalUserDataTask.isRunning || !loadAdditionalUserDataTask.last" />
```
If the task is not started `isRunning` evaluates to `false`.

For better readability you could also introduce a new computed prop.

2022-08-10 13:34 UTC, JanAckermann commented
align with:
https://github.com/owncloud/web/pull/7425

2022-08-11 07:24 UTC, kulmann requested changes

2022-08-11 07:24 UTC, kulmann commented on packages/web-app-files/src/components/Spaces/QuotaModal.vue
> +    ...mapMutations('Files', ['UPDATE_SPACE_FIELD']),
```suggestion
    ...mapMutations('runtime/spaces', ['UPDATE_SPACE_FIELD']),
```

2022-08-11 07:24 UTC, kulmann commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +        <div v-else v-translate>To set an individual quota, the user needs to login first.</div>
```suggestion
        <div v-else v-translate>To set an individual quota, the user needs to have logged in once.</div>
```

2022-08-11 07:24 UTC, kulmann commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +        <div v-else v-translate>To set an individual quota, the user needs to login first.</div>
@phil-davis any native-speaker recommendation here? 😇

2022-08-11 11:37 UTC, tbsbdr commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +        <div v-else v-translate>To set an individual quota, the user needs to login first.</div>
I think your proposal if fine, Benedikt.👍

2022-08-11 13:55 UTC, kulmann commented on packages/web-app-user-management/src/components/Users/SideBar/EditPanel.vue
> +        <div v-else v-translate>
Am I still allowed to say that this should ideally be a `<p>` tag instead of a `<div>`? 🙈 sorry that I didn't see that before...

2022-08-12 09:15 UTC, kulmann approved these changes
LGTM 👍

2022-08-12 09:15 UTC, merged