Rearange declined shares
owncloud/web pull request #7356
Opened 2022-07-27 10:15 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-07-27 10:59 UTC, ownclouders commented
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/27069/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2022-7-27-10-58-05.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2022-7-27-10-58-35.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/file-alice-2022-7-27-10-56-20.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/file-brian-2022-7-27-10-56-27.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/folder-alice-2022-7-27-10-54-56.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27069/tracing/folder-brian-2022-7-27-10-55-03.zip 


</p></details>

<!-- id: pr-7356 -->

2022-07-28 07:22 UTC, kulmann requested changes
Besides a few nitpicks I only see one visual issue: The spacing above and below the "empty"-messages is off (at least too little at the bottom). That looks especially clumsy when you have neither accepted nor declined shares (see screenshot). Could you give that some attention? Otherwise super happy about this PR, the section component turned out great and the code is easier to read than before. Good job 👍 

<img width="1369" alt="Screenshot 2022-07-28 at 09 18 05" src="https://user-images.githubusercontent.com/3532843/181445517-9d2089b1-f7fb-4e23-a6ec-f950fec08fc6.png">

2022-07-28 07:22 UTC, kulmann commented on changelog/unreleased/enhancement-declined-shares-not-easily-accessible
> +Enhancement: Declined shares are not easily accessible
```suggestion
Enhancement: Declined shares are now easily accessible
```

2022-07-28 07:22 UTC, kulmann commented on changelog/unreleased/enhancement-declined-shares-not-easily-accessible
> +Enhancement: Declined shares are not easily accessible
(otherwise it sounds like a bugfix item)

2022-07-28 07:22 UTC, kulmann commented on packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
> +    <no-content-message v-if="!items.length > 0" class="files-empty oc-flex-stretch" icon="group">
```suggestion
    <no-content-message v-if="!items.length" class="files-empty oc-flex-stretch" icon="group">
```

2022-07-28 07:22 UTC, kulmann commented on packages/web-app-files/src/views/shares/SharedWithMe.vue
> +      ></shared-with-me-section>
Can be a self closing tag (same for the other 2 sections)

2022-07-28 07:43 UTC, JanAckermann commented
done

2022-07-28 07:56 UTC, kulmann approved these changes
🥳

2022-07-28 08:17 UTC, merged