Redesign share panel
owncloud/web pull request #7372
Opened 2022-07-29 10:04 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-07-29 12:58 UTC, ownclouders commented
Results for <strong>oCISSharingInternal2</strong> https://drone.owncloud.com/owncloud/web/27175/61/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingInternalUsers-shareWithUsers_feature-L139.png
 ![webUISharingInternalUsers-shareWithUsers_feature-L139.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsers-shareWithUsers_feature-L139.png) 

### webUISharingInternalUsers-shareWithUsers_feature-L322.png
 ![webUISharingInternalUsers-shareWithUsers_feature-L322.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsers-shareWithUsers_feature-L322.png) 

### webUISharingInternalUsers-shareWithUsers_feature-L331.png
 ![webUISharingInternalUsers-shareWithUsers_feature-L331.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsers-shareWithUsers_feature-L331.png) 

### webUISharingInternalUsersCollaborator-shareWithUsers_feature-L34.png
 ![webUISharingInternalUsersCollaborator-shareWithUsers_feature-L34.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsersCollaborator-shareWithUsers_feature-L34.png) 

### webUISharingInternalUsersCollaborator-shareWithUsers_feature-L35.png
 ![webUISharingInternalUsersCollaborator-shareWithUsers_feature-L35.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsersCollaborator-shareWithUsers_feature-L35.png) 

### webUISharingInternalUsersCollaborator-shareWithUsers_feature-L36.png
 ![webUISharingInternalUsersCollaborator-shareWithUsers_feature-L36.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsersCollaborator-shareWithUsers_feature-L36.png) 

### webUISharingInternalUsersCollaborator-shareWithUsers_feature-L37.png
 ![webUISharingInternalUsersCollaborator-shareWithUsers_feature-L37.png](https://cache.owncloud.com/public/owncloud/web/27175/screenshots/webUISharingInternalUsersCollaborator-shareWithUsers_feature-L37.png) 


</p></details>
:boom: The acceptance tests pipeline failed. The build has been cancelled.


<!-- id: pr-7372 -->

2022-08-01 08:18 UTC, kulmann requested changes
I see quite some code deletion in this PR that don't have clear acceptance criteria in the linked issue. Would like to clarify with @tbsbdr here or in the issue if e.g. removing the file size info or invite help text is really intended or just missing in the design.

2022-08-01 08:20 UTC, kulmann commented
Please note that I changed the PR description to state `Works towards #7340` instead of fixing it, because rearranging the dropdowns will happen in another PR https://github.com/owncloud/web/pull/7365

2022-08-01 08:20 UTC, JanAckermann commented
@kulmann This has been spoken through in detail, all code deletion was done with intention

2022-08-01 09:14 UTC, kulmann commented
> @kulmann This has been spoken through in detail, all code deletion was done with intention

Then let's please take the time and write down the decisions in the issue

2022-08-01 14:18 UTC, kulmann commented
Needs a rebase now

2022-08-01 14:31 UTC, JanAckermann commented
done

2022-08-01 15:28 UTC, kulmann approved these changes
Cool 👍

2022-08-01 15:28 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
> -      return cernFeatures
@elizavetaRa @diocas decision was made to remove the description message below the sharing invite form. If you can't drop the line from your UI we'll have to find a different solution. Please reach out then.

2022-08-01 15:29 UTC, merged