[full-ci][tests-only] use oCIS from the cache used from multiple repos
owncloud/web pull request #7523
Opened 2022-08-25 08:47 UTC by kiranparajuli589

Signed-off-by: Kiran Parajuli <kiranparajuli589@gmail.com>

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-08-25 09:10 UTC, ownclouders commented
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/27817/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27817/tracing/file-alice-2022-8-25-09-09-08.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27817/tracing/file-brian-2022-8-25-09-09-16.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27817/tracing/folder-alice-2022-8-25-09-07-38.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/27817/tracing/folder-brian-2022-8-25-09-07-45.zip 


</p></details>

<!-- id: pr-7523 -->

2022-08-26 02:15 UTC, grgprarup commented on .drone.star
> +            "pwd && ls -la %s/$OCIS_COMMITID" % dir["base"],
```suggestion
```
Do we need this?

2022-08-26 07:29 UTC, kiranparajuli589 commented on .drone.star
> +            "pwd && ls -la %s/$OCIS_COMMITID" % dir["base"],
nope. removed

2022-08-26 07:32 UTC, grgprarup reviewed
lgtm

2022-08-29 06:38 UTC, individual-it approved these changes

2022-08-29 06:39 UTC, individual-it requested changes
why moving the files one level higher up?

2022-08-29 10:27 UTC, kiranparajuli589 commented
> why moving the files one level higher up?

yes previously it was under the `web` directory, but now the oCIS cache is saved irrespective of repositories caching them. so getting it out from the `web` allows us to use the same cache from SDK or any other repo CI. The same location is used in the owncloud SDK CI so that they can use the same resource if they're trying to get oCIS of same commitID

2022-08-29 10:39 UTC, individual-it approved these changes

2022-08-29 10:40 UTC, merged