Enhancement: Make arrow-key navigation global
owncloud/web pull request #7569
Opened 2022-09-01 11:25 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-09-02 12:20 UTC, lookacat commented
A directive is not suitable for this case so I chose data-attribute and .closest instead to check if the parent of the focused element has custom key bindings

2022-09-02 13:18 UTC, kulmann requested changes
- `ESC` for deselecting all files now only works after I clicked into the file list via mouse.
- using the arrow keys doesn't set a focus. IMO it should, i.e. when you use the down arrow on initial page load the focus should be moved to the selected row but stays in its initial element (hitting TAB once moves the focus the `skip to main` in such a case, which is the very first focusable element in the document).

2022-09-05 13:32 UTC, kulmann requested changes

2022-09-05 13:32 UTC, kulmann commented on packages/web-app-files/src/components/FilesList/KeyboardActions.vue
> +    document.addEventListener('keydown', this.handleShortcuts)
Since you made all event handlers global now, can you delete the `keybindOnElementIds` prop now?

2022-09-05 13:32 UTC, kulmann commented on packages/web-app-files/src/components/FilesList/KeyboardActions.vue
> +      const customKeyBindings = (window.getSelection().focusNode as HTMLElement)?.closest(
Make sure to have an empty folder and then use the keyboard: throws a lot of errors (see browser console) like `Uncaught TypeError: window.getSelection(...).focusNode?.closest is not a function`

2022-09-05 14:47 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/28084/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/28084/tracing/public-link-for-space-alice-2022-9-5-02-45-01.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/28084/tracing/public-link-for-space-brian-2022-9-5-02-45-27.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/28084/tracing/public-link-for-space-marie-2022-9-5-02-45-31.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-7569 -->

2022-09-12 14:36 UTC, kulmann requested changes

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      // here1
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      // here5
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      console.log('!!!!!')
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      // here4
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      await new Promise((resolve) => setTimeout(resolve, 2000))
not acceptable

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      await new Promise((resolve) => setTimeout(resolve, 2000))
not acceptable

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      // here3
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      // here2
dev leftover, please remove

2022-09-12 14:36 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
> +    data-custom-key-bindings="true"
Can't we just set the `data-custom-key-bindings="true"` on the `SideBar.vue` component?

2022-09-12 14:36 UTC, kulmann commented on packages/web-app-files/src/components/FilesList/KeyboardActions.vue
> +      if (!closestSelectionEl) return true
Why not `return false`? 🤔 Confused by this.

2022-09-12 15:48 UTC, lookacat commented on tests/acceptance/pageObjects/FilesPageElement/filesList.js
> +      await new Promise((resolve) => setTimeout(resolve, 2000))
i think its dev leftover sorry

2022-09-14 10:58 UTC, kulmann requested changes

2022-09-14 10:58 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
> +  <div id="oc-files-file-link" class="oc-position-relative" data-custom-key-bindings="true">
`data-custom-key-bindings="true"` can be removed because `SideBar.vue` already has it (parent container)

2022-09-14 10:58 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
> +  <div id="oc-files-sharing-sidebar" class="oc-position-relative" data-custom-key-bindings="true">
`data-custom-key-bindings="true"` can be removed because `SideBar.vue` already has it (parent container)

2022-09-14 10:58 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
> +  <div id="oc-files-sharing-sidebar" class="oc-position-relative" data-custom-key-bindings="true">
`data-custom-key-bindings="true"` can be removed because `SideBar.vue` already has it (parent container)

2022-09-14 10:58 UTC, kulmann commented on packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.js.snap
> +<div id="oc-files-sharing-sidebar" data-custom-key-bindings="true" class="oc-position-relative">
snapshots need to be updated when sidebar panels have been changed

2022-09-14 12:15 UTC, kulmann approved these changes
🚀

2022-09-14 13:28 UTC, merged