Hide actions in space trash bins in case of insufficient permissions
owncloud/web pull request #7768
Opened 2022-10-11 12:17 UTC by JammingBen

## Description
Actions in space trash bins are now hidden if the current user has insufficient permissions.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/7702

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2022-10-11 12:58 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/29033/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29033/tracing/participant-management-alice-2022-10-11-12-54-43.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29033/tracing/participant-management-anonymous-2022-10-11-12-55-03.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29033/tracing/participant-management-brian-2022-10-11-12-54-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29033/tracing/participant-management-carol-2022-10-11-12-54-52.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-7768 -->

2022-10-12 18:36 UTC, kulmann requested changes

2022-10-12 18:36 UTC, kulmann commented on packages/web-app-files/src/mixins/actions/restore.ts
> +            if (isProjectSpace && ![...manager, ...editor].includes(this.user.uuid)) {
Could you introduce two functions `isManager` and `isEditor` on the project space interface and implement them with the code you have here? That would remove some duplication... could be used as follows:
```js
if (isProjectSpaceResource(this.space) && (this.space.isManager(this.user.uuid) || this.space.isEditor(this.user.uuid))
```

2022-10-13 10:18 UTC, kulmann commented on packages/web-app-files/src/mixins/actions/delete.js
> +              isProjectSpace &&
```suggestion
              isProjectSpaceResource(this.space) &&
```
why assign it to a const? you could use it inline..

2022-10-13 12:06 UTC, kulmann approved these changes
nice 🤩

2022-10-13 12:06 UTC, merged