feat: resolve public link into user context if available
owncloud/web pull request #7802
Opened 2022-10-14 13:50 UTC by kulmann

## Description
If we already have an active user session (only possible in current tab/window) we redirect any public link to the private link and thus into the correct space.
Not possible yet for fresh browser tabs. To be enhanced soon but further research needed....

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2022-10-14 14:12 UTC, ownclouders commented
Results for <strong>oC10SharingPublic2</strong> https://drone.owncloud.com/owncloud/web/29116/37/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicManagement-shareByPublicLink_feature-L78.png
 ![webUISharingPublicManagement-shareByPublicLink_feature-L78.png](https://cache.owncloud.com/public/owncloud/web/29116/screenshots/webUISharingPublicManagement-shareByPublicLink_feature-L78.png) 


</p></details>
:boom: The oC10SharingPublic2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-7802 -->

2022-10-14 14:40 UTC, dschmidt approved these changes

2022-10-14 16:17 UTC, JammingBen requested changes

2022-10-14 16:17 UTC, JammingBen commented on packages/web-runtime/src/pages/resolvePublicLink.vue
> +      if (this.tokenInfo?.alias_link || this.isUserContext) {
This won't work for oC10 as the condition will evaluate to `true` in an authenticated context, without having `tokenInfo`.

2022-10-14 16:43 UTC, tbsbdr commented
desribed resolving-behaviour works only, if 

✅ `Albert` --shares-public-link with-> `Albert`

doesn't work if:

❌ `Albert` --shares-public-link with-> `Marie`

then Marie sees the public link page, even if she's logged in in the same tab.

Or can anyone confirm that the Marie can resolve the link?

2022-10-24 11:41 UTC, kulmann commented
Most parts extracted into https://github.com/owncloud/web/pull/7851 - will need a rebase after that is merged. That will reduce the changeset of this PR to a few lines of code.

2023-06-30 10:35 UTC, kulmann commented
Superseded by https://github.com/owncloud/web/pull/9299

2023-06-30 10:35 UTC, closed without merging