Enable rename user
owncloud/web pull request #7919
Opened 2022-11-04 06:29 UTC by JanAckermann

## Description

## Related Issue

- Fixes https://github.com/owncloud/web/issues/7604

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-11-04 06:30 UTC, JanAckermann commented
Change user name is not supported by backend currently:
```
{"error":{"code":"notSupported","innererror":{"date":"2022-11-04T06:29:42Z","request-id":"62af0378-0f36-4f6c-aa63-165092c2f33b"},"message":"changing the user name is currently not supported"}}
```

2022-11-04 06:51 UTC, ownclouders commented
Results for <strong>oC10IntegrationApp2</strong> https://drone.owncloud.com/owncloud/web/29623/74/1
:boom: The oC10IntegrationApp2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-7919 -->

2023-02-16 08:46 UTC, JammingBen requested changes
One small nitpick, rest LGTM

2023-02-16 08:46 UTC, JammingBen commented on packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
> +          )
Please don't use `$gettextInterpolate` anymore, since it's deprecated. You can simply interpolate in `$gettext` directly.

2023-02-16 09:02 UTC, JammingBen commented on packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
> +          )
Now you have 2 `$gettext` 😄 

```suggestion
          this.formData.userName.errorMessage = this.$gettext(
            'User "%{userName}" already exists',
            { userName: this.editUser.onPremisesSamAccountName }
          )
```

2023-02-16 09:15 UTC, JanAckermann commented on packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
> +          )
i see, there is more to do

2023-02-16 09:45 UTC, JammingBen approved these changes
👍  (needs a linter run though)

2023-02-16 11:00 UTC, kulmann approved these changes
💯

2023-02-16 12:09 UTC, merged