Implement zoom
owncloud/web pull request #7977
Opened 2022-11-16 09:31 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-11-16 09:54 UTC, ownclouders commented
Results for <strong>oC10SharingPublic2</strong> https://drone.owncloud.com/owncloud/web/29892/37/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L62.png
 ![webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L62.png](https://cache.owncloud.com/public/owncloud/web/29892/screenshots/webUISharingPublicExpire-shareByPublicLinkExpiringLinks_feature-L62.png) 


</p></details>
:boom: The oC10SharingPublic2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-7977 -->

2022-11-16 14:55 UTC, JanAckermann commented
I really don't know what to "unit-test" here

2022-11-18 13:12 UTC, kulmann requested changes
The controls for zoom feel a bit jumpy, depending on the percentage value shown in the controls. Could you make this a fixed width somehow?
Other than that only a nitpick about some code deduplication. Feature itself works like a charm, I love it!

I was a bit irritated that the zoom and rotate controls only appear after the image is loaded (that looks funny when browsing through a folder of only images, because the zoom and rotate controls disappear and then reappear all the time). But that will be somewhat fixed when we introduce preloading of images. So nothing we need to worry about here.

2022-11-18 13:12 UTC, kulmann commented on packages/web-app-preview/src/App.vue
> +      this.currentImageZoom = Math.max(0.1, Math.round(this.currentImageZoom * 0.8 * 20) / 20)
Please introduce a method similar to the following:

```js
calculateZoom(zoom: number, factor: number) {
      return Math.round(zoom * factor * 20) / 20
    }
```

and use it in all the places where you have the respective Math.round statement at the moment.

2022-11-18 13:13 UTC, JanAckermann commented
Thx for the feedback!

2022-11-28 11:08 UTC, kulmann approved these changes
Love it 😍

2022-11-28 11:08 UTC, merged