Implement full screen mode
owncloud/web pull request #7994
Opened 2022-11-18 08:49 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2022-11-18 09:11 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/29971/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29971/tracing/file-alice-2022-11-18-09-07-42.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/29971/tracing/file-brian-2022-11-18-09-08-05.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-7994 -->

2022-11-21 16:48 UTC, kulmann requested changes
I don't know if `full screen` is the correct term for this... might be that the wording needs to be adjusted.
One thing that confused me when flipping though images fast, was, that the loading screen lacks the lightbox styles. i.e. you get thrown out of the (now called) full screen mode for the loading state, and then back into the full screen mode when the image has been loaded. That needs fixing, the lightbox should stay there at all times until the user goes back.

One more thing for making this great: the `ESC` key should only clear the full screen mode, but as of now it triggers the `closeApp` action instead. Could you look into that?

2022-11-21 16:48 UTC, kulmann commented on packages/web-app-preview/src/App.vue
> +      isFullScreenModeActivated: true,
Should `false` initially

2022-11-21 16:48 UTC, kulmann commented on packages/web-app-preview/src/App.vue
> +            <oc-icon fill-type="line" name="fullscreen" />
Could you try using the icon `fullscreen-exit` when the fullscreen mode is active?

2022-11-28 11:14 UTC, kulmann approved these changes
Awesome 😎

2022-11-28 13:21 UTC, merged