Update help texts (contextual and role)
owncloud/web pull request #7998
Opened 2022-11-18 12:46 UTC by mmattel

## Description
Improves help texts for the `Internal` role.

## Related Issue
- Fixes #7938

## Motivation and Context
Make the role clear to readers

## How Has This Been Tested?
Text only

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

2022-11-18 12:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/owncloud/web?pullRequest=7998) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/owncloud/web?pullRequest=7998) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/owncloud/web?pullRequest=7998) it.</sub>

2022-11-18 13:11 UTC, mmattel commented
Maybe someone can help, the linter complains but I just have exchanged text...?

2022-11-18 13:14 UTC, kulmann commented
> Maybe someone can help, the linter complains - but I just have replaced text...?

You can probably run `pnpm lint` to fix it. If it can't be fixed automatically, there will be errors displayed which you can fix manually.

2022-11-18 13:16 UTC, kulmann requested changes

2022-11-18 13:16 UTC, kulmann commented on packages/web-app-files/src/helpers/contextualHelpers.js
> +        'The recipient of this link can access the shared content only if he has already an account with at least viewing permissions to that shared content. This role is beneficial to point an exist
I don't agree that this text makes it easier to understand. I don't have better ideas... maybe @tbsbdr can have a look.

2022-11-18 13:47 UTC, mmattel commented
I fixed the linter complains with `pnpm lint --fix`

2023-02-09 16:21 UTC, kulmann commented
don't see that this PR is going anywhere at the moment. closing as stalled (trying to clean up the repo). please come up with a new PR when there's agreement in the issue.

2023-02-09 16:21 UTC, closed without merging