[tests-only] Add unit tests for the text editor
owncloud/web pull request #8002
Opened 2022-11-18 15:32 UTC by JammingBen

This also includes a mock for the `useAppDefaults` composable.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

2022-11-18 15:40 UTC, JammingBen commented
SonarCloud fails because of 0.0% condition coverage... makes sense 🤡 
![image](https://user-images.githubusercontent.com/50302941/202743249-9521a65c-7c90-4528-a284-4bcb7c61f70e.png)

2022-11-20 08:53 UTC, dschmidt approved these changes
I like, can we add this to stable instead?

2022-11-24 09:07 UTC, dschmidt approved these changes

2022-11-24 09:07 UTC, dschmidt commented on packages/web-app-text-editor/tests/unit/app.spec.ts
> +  const store = createStore(Vuex.Store, storeOptions)
Out of scope for this PR, but:

I don't like that you use options from test helpers but have to add `vuex-extensions` to the package dependencies, I would like to see this handled in `web-test-helpers` completely.
We should really throw some time at unit tests at some point, unify the setup and clean up stuff like this.

2022-11-24 09:09 UTC, kulmann requested changes

2022-11-24 09:09 UTC, kulmann commented on packages/web-test-helpers/src/mocks/useAppDefaultsMock.ts
> +export const useAppDefaultsMock = (
Still amazed by the mocks with the partial type for options 😎

2022-11-24 09:09 UTC, kulmann commented on packages/web-app-text-editor/tests/unit/app.spec.ts
> +  it('shows the preview', async () => {
Could you make this a `describe` block about previews and then check that different file types show/don't show the preview? The preview is only there for markdown. E.g. a `.txt` file will not have a preview.

2022-11-24 09:29 UTC, kulmann approved these changes

2022-11-24 10:10 UTC, merged