Fix resolving drives in search results
owncloud/web pull request #8045
Opened 2022-11-30 10:40 UTC by JammingBen

## Description
Resolving shares and project spaces in the personal space when using the search has been fixed.

## Details

Currently, you can't access incoming shares or project spaces via search result from your personal space. This does not work because technically, Vue does not detect a route change when navigating into such resources. We're still on the same route: `files/spaces/...`. So the `DriveResolver` won't get called again -> no resource (re-)loading.

One solution to overcome this is to specify a `key` in the router view, which I did here. The key is the current drive, e.g. `personal`, `share` or `project`. When the key changes, Vue will detect a router change and resolve the route again.

I have to admit, the way to retrieve the drive is ugly: `this.$route.path.split('/')[3]`. I'm open for better solutions :D

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8034

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2022-11-30 13:19 UTC, kulmann requested changes
Can you think of a regression-test in jest? We could write one for the `GenericSpace` view that checks the call to the loader task whenever the `item` or `space` changes.

2022-11-30 14:42 UTC, kulmann approved these changes
💯

2022-12-01 12:30 UTC, kulmann commented on packages/web-app-files/src/views/spaces/GenericSpace.vue
> +      if (this.loadResourcesTask.isRunning) {
For the record: If `space` and `item` (= relative item path in that space) **both** changed, the loader task is called twice. This is skipping one of the task executions.

2022-12-01 12:34 UTC, JanAckermann approved these changes

2022-12-01 14:21 UTC, merged