[tests-only] Add missing sidebar unit tests
owncloud/web pull request #8114
Opened 2022-12-14 14:07 UTC by JammingBen

Do not merge before https://github.com/owncloud/web/pull/8103 has been merged.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

2022-12-19 21:12 UTC, kulmann requested changes

2022-12-19 21:12 UTC, kulmann commented on packages/web-app-files/tests/unit/components/SideBar/NoSelection.spec.ts
> +    expect(wrapper).toMatchSnapshot()
```suggestion
    expect(wrapper.html()).toMatchSnapshot()
```

2022-12-19 21:12 UTC, kulmann commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Shared/RoleItem.spec.ts
> +    expect(wrapper).toMatchSnapshot()
```suggestion
    expect(wrapper.html()).toMatchSnapshot()
```

2022-12-19 21:12 UTC, kulmann commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Links/CreateQuickLink.spec.ts
> +    expect(wrapper).toMatchSnapshot()
```suggestion
    expect(wrapper.html()).toMatchSnapshot()
```

2022-12-19 21:12 UTC, kulmann commented on packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/EditDropdown.spec.ts
> +      expect(wrapper).toMatchSnapshot()
```suggestion
      expect(wrapper.html()).toMatchSnapshot()
```

2023-01-23 22:31 UTC, kulmann commented
@JammingBen could you revisit your PR and bring it up to date?

2023-01-24 12:58 UTC, kulmann approved these changes

2023-01-25 08:56 UTC, JanAckermann approved these changes

2023-01-25 09:13 UTC, merged