Group share recipients
owncloud/web pull request #8161
Opened 2022-12-28 12:28 UTC by fschade

## Description
This pr allows to select groups as share recipients. So far it was only possible to select users.

## Related Issue
- Fixeshttps://github.com/owncloud/web/issues/8160

## Motivation and Context
be able to share resources to groups instead of user only.

## How Has This Been Tested?
- [ ] e2e tests
- [ ] unit tests

## Screenshots (if appropriate):

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [X] Tests

## Checklist:
- [ ] Code changes
- [ ] Unit tests added
- [ ] E2E tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:
- [ ] Basic implementation
- [ ] Changelog
- [ ] Testing

2023-01-02 15:20 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/31076/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-alice-2023-1-2-03-15-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-brian-2023-1-2-03-15-53.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-carol-2023-1-2-03-15-58.zip 


</p></details>

<!-- id: pr-8161-oCIS -->

2023-01-02 15:20 UTC, ownclouders commented
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/31076/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/file-alice-2023-1-2-03-18-47.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/file-brian-2023-1-2-03-18-54.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-alice-2023-1-2-03-16-18.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-brian-2023-1-2-03-16-24.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/re-sharing-carol-2023-1-2-03-16-31.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31076/tracing/upload-resources-in-personal-space-alice-2023-1-2-03-20-17.zip 


</p></details>

<!-- id: pr-8161-oC10 -->

2023-01-03 06:08 UTC, individual-it commented
should we create an e2e user story for that or integrate it in a existing story?

2023-01-03 08:11 UTC, fschade commented
> should we create an e2e user story for that or integrate it in a existing story?

That would be nice, can you talk to @lookacat , he planned to create one today. But please as separate pr, we need to get this merged today.

thank you 😘

2023-01-03 08:25 UTC, individual-it commented
@fschade we will not be able to do it anyway soon, but I've added the issue to our project https://github.com/owncloud/web/issues/8160 and will pick it

2023-01-03 09:02 UTC, JammingBen requested changes

2023-01-03 09:02 UTC, JammingBen commented on packages/web-runtime/src/store/spaces.ts
> +  loadSpaceMembers(context, { graphClient, space }: { graphClient: Ref<Graph>; space: any }) {
```suggestion
  loadSpaceMembers(context, { graphClient, space }: { graphClient: Ref<Graph>; space: SpaceResource }) {
```

2023-01-03 09:02 UTC, JammingBen commented on packages/web-runtime/src/store/spaces.ts
> +    console.log(additionalParams)
🙈

2023-01-03 09:10 UTC, JammingBen commented
Also, loading my personal space gives me console errors: 
![image](https://user-images.githubusercontent.com/50302941/210327766-e08c1789-40c5-4dd8-99c2-e1d55787eaf2.png)

Does it work for you @fschade ?

2023-01-03 09:46 UTC, fschade commented
> Also, loading my personal space gives me console errors: ![image](https://user-images.githubusercontent.com/50302941/210327766-e08c1789-40c5-4dd8-99c2-e1d55787eaf2.png)
> 
> Does it work for you @fschade ?

It needs the latest master ocis, which version is in use?

2023-01-03 09:52 UTC, JammingBen commented
@fschade Ahhh sorry, now it works 🙈  Thanks!

I found another nitpick though:

1. Invite group `physics-lovers`
2. Search for `physics-lovers` again -> it should not be in the autocomplete result, but it is. You can even select it:

![image](https://user-images.githubusercontent.com/50302941/210334146-2984d1d8-a0d0-4fcc-8394-937cb54fb42d.png)

2023-01-03 11:11 UTC, fschade commented
> I found another nitpick though:

fixed in https://github.com/owncloud/web/pull/8161/commits/53e94f8ee7b5d6a3debb5fa6aed624a644380866

2023-01-03 11:21 UTC, JammingBen approved these changes
Nice 🚀

2023-01-03 11:45 UTC, merged