Enable get route title
owncloud/web pull request #8199
Opened 2023-01-10 08:42 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-01-11 14:33 UTC, kulmann requested changes

2023-01-11 14:33 UTC, kulmann commented on packages/web-pkg/src/composables/appDefaults/useAppDocumentTitle.ts
> +      basename(unref(unref(currentFileContext).fileName)) || unref(currentRoute)?.meta?.title
```suggestion
      basename(unref(unref(currentFileContext).fileName)) || $gettext(unref(currentRoute)?.meta?.title)
```

The route titles are statically defined and only ever wrapped in a dummy `$gettext` helper that ensures string **extraction** to transifex. The dummy helpers never do actual runtime translations, thus you to feed the respective string into the actual `$gettext` function.

2023-01-12 08:41 UTC, kulmann approved these changes
Nice improvement 👍

2023-01-12 13:00 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/31479/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-alice-2023-1-12-12-57-19.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-anonymous-2023-1-12-12-57-48.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-brian-2023-1-12-12-57-28.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-carol-2023-1-12-12-57-38.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-marie-2023-1-12-12-57-31.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31479/tracing/participant-management-richard-2023-1-12-12-57-34.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-8199-oCIS -->

2023-01-12 13:36 UTC, merged