Extend multiple space selection details
owncloud/web pull request #8230
Opened 2023-01-13 09:49 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-01-16 09:52 UTC, JammingBen requested changes

2023-01-16 09:52 UTC, JammingBen commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +        <p class="preview-text" data-testid="selectedFilesText" v-text="selectedSpacesString" />
Let's either remove `data-testid` (as we don't use it in the tests), or rename it to `selectedSpacesText`. The same goes for the testids down below.

2023-01-16 09:52 UTC, JammingBen commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +      return filesize(total)
TIL: We have a nice `formatFileSize` helper 🙂 Let's use that. It needs `$language.current` as second param, you can get that from `useTranslations()`.

2023-01-16 09:52 UTC, JammingBen commented on packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetailsMultiple.spec.ts
> +}
This file looks like a lot of copy-paste, which is actually not needed here. You can probably remove `spaceShare` and all the store-related stuff in `createWrapper` (except for `defaultStoreMockOptions` maybe).

```suggestion
```

2023-01-16 09:52 UTC, JammingBen commented on packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetailsMultiple.spec.ts
> +        }
```suggestion
```

2023-01-16 09:52 UTC, JammingBen commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +      <table class="details-table" :aria-label="detailsTableLabel">
`detailsTableLabel` does not exist yet.

2023-01-16 10:48 UTC, kulmann requested changes

2023-01-16 10:48 UTC, kulmann commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +          <th scope="col" class="oc-pr-s" v-text="$gettext('Total:')" />
```suggestion
          <th scope="col" class="oc-pr-s" v-text="$gettext('Total quota:')" />
```

2023-01-16 10:48 UTC, kulmann commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +          <th scope="col" class="oc-pr-s" v-text="$gettext('Remaining:')" />
```suggestion
          <th scope="col" class="oc-pr-s" v-text="$gettext('Remaining quota:')" />
```

2023-01-16 10:48 UTC, kulmann commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +          <th scope="col" class="oc-pr-s" v-text="$gettext('Used:')" />
```suggestion
          <th scope="col" class="oc-pr-s" v-text="$gettext('Used quota:')" />
```

2023-01-17 09:36 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/31706/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-alice-2023-1-17-09-33-17.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-anonymous-2023-1-17-09-33-51.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-brian-2023-1-17-09-33-26.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-carol-2023-1-17-09-33-39.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-marie-2023-1-17-09-33-30.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31706/tracing/participant-management-richard-2023-1-17-09-33-34.zip 


</p></details>

<!-- id: pr-8230-oCIS -->

2023-01-17 12:02 UTC, JammingBen approved these changes
LGTM 🥳 Minor nitpick, approving anyway since it's a "code-readability"-thing.

2023-01-17 12:02 UTC, JammingBen commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +      return enabled
I'd prefer this for more readability:

```suggestion
      return props.selectedSpaces.filter((s) => !s.disabled).length
```

2023-01-17 12:02 UTC, JammingBen commented on packages/web-pkg/src/components/sideBar/Spaces/Details/SpaceDetailsMultiple.vue
> +      return disabled
^ Same here.

2023-01-18 08:37 UTC, merged