Fix quota display in spaces management table
owncloud/web pull request #8238
Opened 2023-01-13 15:20 UTC by JammingBen

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2023-01-13 15:56 UTC, JammingBen commented
Let's wait for https://github.com/owncloud/web/pull/8235 to be merged, probably fixes the failing unit test.

2023-01-16 08:22 UTC, kulmann requested changes

2023-01-16 08:22 UTC, kulmann commented on packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
> +      return filesize(space.spaceQuota.total)
Could you use the `formatFileSize` helper from `web-pkg/src/helpers/filesize` instead? For two reasons:
1. makes sure that the correct localization is used
2. handles invalid values in a consistent way

2023-01-16 08:58 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/31637/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-alice-2023-1-16-08-54-59.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-anonymous-2023-1-16-08-55-36.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-brian-2023-1-16-08-55-09.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-carol-2023-1-16-08-55-24.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-marie-2023-1-16-08-55-14.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31637/tracing/participant-management-richard-2023-1-16-08-55-18.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-8238-oCIS -->

2023-01-16 09:38 UTC, merged