Use SpaceNoSelection for spaces
owncloud/web pull request #8249
Opened 2023-01-16 14:39 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-01-16 14:59 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/31670/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-alice-2023-1-16-02-55-50.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-anonymous-2023-1-16-02-56-31.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-brian-2023-1-16-02-56-01.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-carol-2023-1-16-02-56-17.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-marie-2023-1-16-02-56-06.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/31670/tracing/participant-management-richard-2023-1-16-02-56-11.zip 


</p></details>

<!-- id: pr-8249-oCIS -->

2023-01-17 08:50 UTC, JanAckermann requested changes

2023-01-17 08:50 UTC, JanAckermann commented on changelog/unreleased/enhancement-spaces-list-in-admin-settings
> +https://github.com/owncloud/web/pull/8249
/issues/* at last pls

2023-01-17 08:51 UTC, lookacat commented on changelog/unreleased/enhancement-spaces-list-in-admin-settings
> +https://github.com/owncloud/web/pull/8249
sí

2023-01-17 09:02 UTC, JanAckermann approved these changes

2023-01-17 10:20 UTC, merged