Init admin settings general appearance section
owncloud/web pull request #8375
Opened 2023-02-06 09:00 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-02-08 10:37 UTC, ownclouders commented
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/32556/63/1
:boom: The oCISSharingInternal2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-8375-oCIS -->

2023-02-08 14:15 UTC, JanAckermann commented
Stupid sonarCloud.... demanding on imports are conditions that have to be covered -.-

2023-02-08 14:41 UTC, JammingBen commented
I probably need some oCIS branch checked out to make it work...? Because uploading does not work for me.

> Stupid sonarCloud.... demanding on imports are conditions that have to be covered -.-

Yeah, that's super annoying :( Especially with the composition API I feel that SonarCloud does a terrible job at analyzing coverage.

2023-02-09 08:38 UTC, ownclouders commented
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/32606/75/1
:boom: The oC10IntegrationApp2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-8375-oC10 -->

2023-02-09 14:32 UTC, kulmann commented on config/vite_ocis/config.json
> +      "text/plain"
ocis supports more mime types:
```json
"image/gif",
"image/png",
"image/jpeg",
"text/plain",
"image/tiff",
"image/bmp",
"image/x-ms-bmp"
```

2023-02-09 14:33 UTC, JanAckermann commented on config/vite_ocis/config.json
> +      "text/plain"
Ok, I'll follow up all configs later on

2023-02-09 14:46 UTC, kulmann requested changes

2023-02-09 14:46 UTC, kulmann commented on packages/web-app-admin-settings/src/components/General/AppearanceSection.vue
> +        <h3>Logo</h3>
missing translation

2023-02-09 14:46 UTC, kulmann commented on packages/web-app-admin-settings/src/mixins/general/resetLogo.ts
> +          title: this.$gettext('Logo was reset successfully')
```suggestion
          title: this.$gettext('Logo was reset successfully. Reloading page...')
```
We should announce the page reload

2023-02-09 14:46 UTC, kulmann commented on packages/web-app-admin-settings/src/views/General.vue
> +        <div class="oc-px-m oc-">
broken class ;-)

2023-02-09 14:46 UTC, kulmann commented on packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
> +      <div class="oc-flex oc-flex-middle oc-width-1-1">
That's also done in https://github.com/owncloud/web/pull/8398 right? Could you avoid the conflicting change? Or do you really need the wrapping divs here?

2023-02-09 22:00 UTC, kulmann approved these changes
🥳

2023-02-09 22:00 UTC, merged