Clarify `config.json` installation path
owncloud/web pull request #8388
Opened 2023-02-07 11:55 UTC by enbrnz

## Description
When installing ownCloud Web in ownCloud 10 as app, the supplied `config.json.sample-oc10` is in `/path/to/owncloud/apps/web/config/` The `config.json` needs to be installed inside `/path/to/owncloud/config/` and not `/path/to/owncloud/apps/web/config/`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2023-02-07 12:23 UTC, kulmann requested changes
Thanks for helping to make this better! :heart: 
I'd like to propose a different solution. The page you edited is more focused on working from the repo clone. We have a different docs page available for the app deployment, which is: https://github.com/owncloud/web/blob/master/docs/deployments/oc10-app.md

Of course that one is in the same way not sufficiently specific about the config location. Also the devdocs url of the page could be added as a hint here, e.g. `If you're setting up ownCloud Web for ownCloud 10 as an app, please refer to https://owncloud.dev/clients/web/deployments/oc10-app/`

Or maybe even as a big disclaimer at the top of this docs page. 🤔 

What do you think?

2023-02-15 17:27 UTC, kulmann commented
@enbrnz ^

2023-02-16 13:00 UTC, enbrnz commented
Thanks for the reminder ping.

> The page you edited is more focused on working from the repo clone. We have a different docs page available for the app deployment, which is: https://github.com/owncloud/web/blob/master/docs/deployments/oc10-app.md

Oh, I didn't even know that page. 

> Or maybe even as a big disclaimer at the top of this docs page. 🤔
> 
> What do you think?

Yes, I think that would be better in this case. 



> Also the devdocs url of the page could be added as a hint here

I guess because web is going to stay a "technology preview" for ownCloud 10 it won't appear in the official ownCloud documentation? 

If not it could also make sense to the deployment doc into the official docs with a tech preview disclaimer?

2023-02-16 13:10 UTC, kulmann commented
@enbrnz the app deployment actually part of the `next` branch of official documentation, see https://doc.owncloud.com/webui/next/owncloud_web/

cc @mmattel the docs page is also not showing a technology preview warning for use with oc10. Could you add that please?

2023-02-16 13:43 UTC, mmattel approved these changes

2023-02-16 13:43 UTC, mmattel commented
1. This PR correctly fixes the issue @enbrnz is highlighting, I approve it therefore.
2. We have NEVER been told that web for oc10 is a tech preview, this is completely new. It was up to now an app for the smooth transition and that users can get used to it.
3. I completely disagree on making admin docs that link to content on dev docs. This is against the sense and purpose. For admins, the admin docs are the single source of thruth. There are extremely rare cases where we link. If something has to be documented not related to developers, it has to be in the admin (or user) docs.

2023-02-16 13:44 UTC, enbrnz commented
> 2\. We have NEVER been told that web for oc10 is a tech preview, this is completely new. It was up to now an app for the smooth transition and that users can get used to it.

That's just something I heard in the office, perhaps get an official statement from @hodyroff or @tbsbdr

2023-02-16 13:47 UTC, mmattel commented
My latest statement was from @tbsbdr and there was no mentioning about a tech-preview...?

2023-02-16 13:50 UTC, kulmann commented
> * This PR correctly fixes the issue @enbrnz is highlighting, I approve it therefore.

No it doesn't. @enbrnz wanted to address the `app` deployment and changed something in the dev docs page that describes running from source in a dev environment.


> * We have NEVER been told that web for oc10 is a tech preview, this is completely new. It was up to now an app for the smooth transition and that users can get used to it.

https://marketplace.owncloud.com/apps/web

First sentence `ownCloud Web currently is a technology preview.`. I think it doesn't get more official than that.


> * I completely disagree on making admin docs that link to content on dev docs. This is against the sense and purpose. For admins, the admin docs are the single source of thruth. There are extremely rare cases where we link. If something has to be documented not related to developers, it has to be in the admin (or user) docs.

That's not even what @enbrnz proposed. He suggested to delete the dev docs page and only keep your official docs page.

2023-02-16 13:53 UTC, mmattel commented
ok, means we should transport the content to the web admin docs - or?

2023-02-16 13:55 UTC, hodyroff commented
As per https://marketplace.owncloud.com/apps/web "ownCloud Web currently is a technology preview." we don't plan to change this for oC10 anytime soon. For ownCloud Infinite Scale it is part of the product offering of course.

2023-05-30 06:05 UTC, pascalwengerter commented
@enbrnz now that the discussion above seems to have been resolved, do you want to finalize this one? :)

2024-02-02 14:44 UTC, kulmann commented
This is stale and outdated by now... I'll close here. Thanks for the contribution and discussion!

2024-02-02 14:44 UTC, closed without merging