Define basic steps
owncloud/web pull request #8527
Opened 2023-03-02 12:22 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-03-03 08:27 UTC, ownclouders commented
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/33287/69/1
:boom: The oCISSharingPublic2 tests pipeline failed. The build has been cancelled.


<!-- id: pr-8527-oCIS -->

2023-03-03 11:05 UTC, JanAckermann approved these changes

2023-03-03 12:10 UTC, kulmann requested changes
Looks good and straightforward. Not happy with the details of the two verifications in the actions though (see comments). Could you research that part please?

2023-03-03 12:10 UTC, kulmann commented on tests/e2e/support/objects/app-admin-settings/general/actions.ts
> +  await page.waitForSelector('text=Logo was reset successfully. Reloading page...')
Please avoid checks on text if possible. What about waiting until the page is reloaded and then check the img src? The way it's implemented right now has the downside of not knowing if the reset really worked or it just printed the success message (as a false positive).

2023-03-03 12:10 UTC, kulmann commented on tests/e2e/support/objects/app-admin-settings/general/actions.ts
> +  await page.waitForSelector('text=Logo was uploaded successfully')
Please avoid checks on text if possible. What about waiting until the page is reloaded and then check the img src? The way it's implemented right now has the downside of not knowing if the upload really worked or it just printed the success message (as a false positive).

2023-03-06 09:01 UTC, merged

2023-03-06 10:44 UTC, kulmann reviewed
Ok, so post merge review: Looks good now!
Note: for running the test in local dockerized dev env, the `:ro` flag on the `dist` volume mount needs to be removed. Otherwise the logo upload fails (which is expected on a readonly `dist` folder mount).