Fix quota modal text for users
owncloud/web pull request #8603
Opened 2023-03-13 11:37 UTC by JammingBen

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8572

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2023-03-13 12:10 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/33580/12/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/copy-and-move-resources-in-personal-space-alice-2023-3-13-12-00-45.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/quick-link-alice-2023-3-13-12-02-26.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/quick-link-anonymous-2023-3-13-12-02-34.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/user-login-can-be-managed-in-the-admin-settings-admin-2023-3-13-11-59-34.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/user-login-can-be-managed-in-the-admin-settings-admin-2023-3-13-11-59-40.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33580/tracing/user-login-can-be-managed-in-the-admin-settings-alice-2023-3-13-11-59-39.zip 


</p></details>
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-8603-oCIS -->

2023-03-13 14:14 UTC, ownclouders commented
Results for <strong>e2e-tests oC10</strong> https://drone.owncloud.com/owncloud/web/33585/11/1
<details><summary>:boom: To see the trace, please open the link in the console ...</summary>

<p>


#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-alice-2023-3-13-02-09-23.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-brian-2023-3-13-02-09-53.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/alice-can-share-this-weeks-meal-plan-with-all-parents-carol-2023-3-13-02-09-59.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/re-sharing-alice-2023-3-13-02-12-44.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/re-sharing-brian-2023-3-13-02-12-32.zip 

#### npx playwright show-trace https://cache.owncloud.com/public/owncloud/web/33585/tracing/re-sharing-carol-2023-3-13-02-12-37.zip 


</p></details>
:boom: The e2e-oc10 tests pipeline failed. The build has been cancelled.


<!-- id: pr-8603-oC10 -->

2023-03-13 22:35 UTC, kulmann requested changes
Some nitpicks about strings. Hope those make sense. Otherwise good 👍

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          'Space quota of %{count} spaces was changed successfully',
```suggestion
          'Quota of %{count} spaces was changed successfully',
```

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          'User quota of %{count} users was changed successfully',
```suggestion
          'Quota of %{count} users was changed successfully',
```

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          'Failed to change space quota for %{count} spaces',
```suggestion
          'Failed to change quota for %{count} spaces',
```

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          'Failed to change user quota for %{count} users',
```suggestion
          'Failed to change quota for %{count} users',
```

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          return $gettext('Change quota for user %{name}', {
```suggestion
          return $gettext('Change quota for user "%{name}"', {
```

2023-03-13 22:35 UTC, kulmann commented on packages/web-pkg/src/components/Spaces/QuotaModal.vue
> +          return $gettext('Change quota for space %{name}', {
```suggestion
          return $gettext('Change quota for space "%{name}"', {
```

2023-03-14 15:45 UTC, kulmann approved these changes
nice 💪

2023-03-14 15:46 UTC, merged