Implement batch action for editing the login state of users
owncloud/web pull request #8799
Opened 2023-04-12 13:50 UTC by JammingBen

## Description
Adds a batch action to the users list in the admin settings which allows the admin to batch-edit the login state of users.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8798

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots
<img width="468" alt="image" src="https://user-images.githubusercontent.com/50302941/231478298-f65a83b2-d414-4baf-b888-da382d243771.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2023-04-12 14:03 UTC, ownclouders commented
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/34659/51/1
:boom: The oCISWebdavLockProtection tests pipeline failed. The build has been cancelled.


<!-- id: pr-8799-oCIS -->

2023-04-12 14:03 UTC, ownclouders commented
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/34659/50/1
:boom: The oCISBasic tests pipeline failed. The build has been cancelled.


<!-- id: pr-8799-oCIS -->

2023-04-12 14:03 UTC, ownclouders commented
Results for <strong>e2e-tests oCIS</strong> https://drone.owncloud.com/owncloud/web/34659/12/1
:boom: The e2e-ocis tests pipeline failed. The build has been cancelled.


<!-- id: pr-8799-oCIS -->

2023-04-12 14:03 UTC, ownclouders commented
Results for <strong>acceptance oC10</strong> https://drone.owncloud.com/owncloud/web/34659/14/1
:boom: The oC10FileFolderOperations tests pipeline failed. The build has been cancelled.


<!-- id: pr-8799-oC10 -->

2023-04-13 10:04 UTC, kulmann requested changes
The other modals have a lengthy, very detailed title and a short label. For text consistency, should this modal be changed as follows for consistency?

title: `Edit login for "Albert Einstein"` / `Edit login for 3 users`
dropdown label: `Login status`

2023-04-13 10:04 UTC, kulmann commented on packages/web-app-admin-settings/src/composables/actions/users/useUserActionsEditLogin.ts
> +      label: () => $gettext('Edit Login'),
```suggestion
      label: () => $gettext('Edit login'),
```

2023-04-13 15:39 UTC, merged