Fix quicklink icon alignment
owncloud/web pull request #8822
Opened 2023-04-17 08:40 UTC by lookacat

## Description
We've fixed the alignment of the quicklink icons.
(There is no better solution but to hard set pixel values because the icons itself have the exact same size and padding, its just because of the form of the icons that it looks like the padding is wrong)
For more details see https://github.com/owncloud/web/issues/8606

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8606

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-04-17 10:21 UTC, kulmann commented on packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
> +  margin-left: 4px; // to align with the other elements
Please use `var(--oc-space-xsmall)`

2023-04-17 10:56 UTC, lookacat commented on packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
> +  margin-left: 4px; // to align with the other elements
yes

2023-04-17 11:10 UTC, kulmann requested changes
Please also adjust for the icon in the sharing panel, see screenshot

<img width="437" alt="Screenshot 2023-04-17 at 13 09 11" src="https://user-images.githubusercontent.com/3532843/232467542-e0ebc8c8-402f-4fb1-8146-403919f0fb66.png">

2023-04-17 22:38 UTC, ChrisEdS commented
> Please also adjust for the icon in the sharing panel, see screenshot
> 
> <img alt="Screenshot 2023-04-17 at 13 09 11" width="437" src="https://user-images.githubusercontent.com/3532843/232467542-e0ebc8c8-402f-4fb1-8146-403919f0fb66.png">

I'm I wrong or are these two different icons for the same thing (expiration date)?

<img width="91" alt="image" src="https://user-images.githubusercontent.com/33026403/232625294-29a11b81-7cd6-49a2-bd83-7076f0679e84.png">

and 

<img width="71" alt="image" src="https://user-images.githubusercontent.com/33026403/232625338-f3e9345f-9bcf-459d-98b6-d42037d6e581.png">

2023-04-17 22:50 UTC, kulmann commented
@ChrisEdS correct, good spot. Let’s only use one. 🙈 I prefer the one we have for links. You?

2023-04-17 22:56 UTC, ChrisEdS commented
Yep, seems like the one without the "date picked" is used as "remove date" icon

<img width="337" alt="image" src="https://user-images.githubusercontent.com/33026403/232627703-3857c18f-0c76-483d-b4b9-2c672bb61b45.png">

2023-04-18 07:03 UTC, lookacat commented
ok will look into it when i'm done with the other ticket

2023-04-18 13:24 UTC, lookacat commented
done

2023-04-21 13:14 UTC, JanAckermann commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
> +  margin-top: 5px;
4px not possible?

2023-04-21 13:14 UTC, JanAckermann requested changes

2023-04-21 13:14 UTC, JanAckermann commented on packages/web-app-files/src/components/SideBar/Shares/Links/DetailsAndEdit.vue
> +  margin-left: var(--oc-space-xsmall); // to align with the other elements
please in class

2023-04-26 07:24 UTC, lookacat commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
> +  margin-top: 5px;
looks wrong

2023-04-26 07:37 UTC, lookacat commented on packages/web-app-files/src/components/SideBar/Shares/Collaborators/ListItem.vue
> +  margin-top: 5px;
1px off

2023-04-26 09:37 UTC, JanAckermann approved these changes

2023-04-26 10:03 UTC, kulmann approved these changes
👍

2023-04-26 10:03 UTC, merged