WIP
owncloud/web pull request #8938
Opened 2023-04-27 10:08 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-04-27 12:39 UTC, lookacat commented on packages/web-app-files/src/components/FilesList/ContextActions.vue
> +    const { actions: createNewFile } = useFileActionsCreateNewFile({
this is just for demonstration purposes only to test if the action works

2023-04-27 14:05 UTC, JammingBen reviewed
I love where this is going!

2023-04-28 09:09 UTC, JanAckermann requested changes

2023-04-28 09:09 UTC, JanAckermann commented on packages/web-app-files/src/composables/actions/files/useFileActionsCreateNewFile.ts
> +    console.log('mimetypesAllowedForCreation', mimetypesAllowedForCreation)
dev leftover?

2023-04-28 12:28 UTC, JammingBen requested changes
Few smaller things from my side, looks quite good overall.

Types need to be improved, but that can be done in a follow-up IMO because they should be added and used globally (talking about `newFileHandlers` and `mimetypesAllowedForCreation`).

Also, we definitely need to test this with a WOPI instance before merging.

2023-04-28 12:28 UTC, JammingBen commented on packages/web-app-files/src/composables/actions/files/useFileActionsCreateNewFile.ts
> +      const addAppProviderFile = false
I believe you can even remove `addAppProviderFile` and just pass `openAction`. In `handler` where we check `addAppProviderFile ? ...` we can simply check `!openAction ? ...`

2023-05-02 07:07 UTC, lookacat commented on packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
> +                    $gettextInterpolate($gettext('%{name}'), { name: mimeTypeAction.label() })
yes right

2023-05-02 13:16 UTC, ownclouders commented
Results for <strong>acceptance oCIS</strong> https://drone.owncloud.com/owncloud/web/35355/58/1
<details><summary>:boom: The acceptance tests failed on retry. Please find the screenshots inside ...</summary>

<p>


### webUITextEditor-textFile_feature-L13.png
 ![webUITextEditor-textFile_feature-L13.png](https://cache.owncloud.com/public/owncloud/web/35355/screenshots/webUITextEditor-textFile_feature-L13.png) 


</p></details>

<!-- id: pr-8938-oCIS -->

2023-05-03 12:54 UTC, JammingBen reviewed
One last nitpick from my side, rest LGTM!

2023-05-03 12:54 UTC, JammingBen commented on packages/web-app-files/src/components/SideBar/Shares/Links/CreateQuickLink.vue
This file looks like it slipped in accidentally.

2023-05-03 13:37 UTC, merged