Fix preview app file loading
owncloud/web pull request #8975
Opened 2023-05-04 07:00 UTC by JammingBen

## Description
Fixes a bug where the preview app would load the files of an image's source location instead of the files in the actual file list.

This happened because the preview app called `loadFolderForFileContext` which loads all files of the current file's source location. This is not needed IMO (at least currently) because you can only open the preview app from a files list where files are already loaded.

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8932

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

2023-05-05 07:43 UTC, JanAckermann approved these changes
💪

2023-05-05 08:15 UTC, kulmann requested changes
Unfortunately not that simple, sorry. Works when you come from the files app (from whatever view you had), but is entirely broken in case you do a page reload / load from a bookmark.

2023-05-05 08:45 UTC, JammingBen commented
> Unfortunately not that simple, sorry. Works when you come from the files app (from whatever view you had), but is entirely broken in case you do a page reload / load from a bookmark.

Arghs, I feared some scenario like that would exist 😄

2023-05-05 09:12 UTC, JammingBen commented
Unless somebody has an easy workaround, I'd like to postpone that fix because it gets quite complicated.

The folder loader which is used to load the files does this based on the given space. While this is fine for generic space views, it is not for views like `Shared via link`. As a result, we need to load the files individually based on the current view, ideally by re-using (parts of) the corresponding folder loader - which of course lives in the files app.

2023-05-05 11:57 UTC, kulmann commented
> Unless somebody has an easy workaround, I'd like to postpone that fix because it gets quite complicated.
> 
> The folder loader which is used to load the files does this based on the given space. While this is fine for generic space views, it is not for views like `Shared via link`. As a result, we need to load the files individually based on the current view, ideally by re-using (parts of) the corresponding folder loader - which of course lives in the files app.

I suppose that @dschmidt has an opinion on this. ;-) Loading the files for the correct context (including the loader tasks) should be part of the `useAppDefaults` composable. Or in other words: extension developers need this kind of functionality. Quite some refactoring involved. I don't see an easy workaround.

2023-05-05 11:59 UTC, dschmidt commented
I'm happy if F5 works 😬

2023-05-17 12:14 UTC, JammingBen commented
Closing here for now as the solution will probably look totally different from this PR.

2023-05-17 12:14 UTC, closed without merging