feat: shrink most table columns to their minimum
owncloud/web pull request #8978
Opened 2023-05-04 10:19 UTC by kulmann

## Description
- shrinks table columns that took a weirdly high amount of horizontal space
- adds a prop validator for allowed view modes in the resource table
- invisible sort buttons in the table header no don't take up horizontal space anymore (otherwise alignment looks weird for shrinked columns)
- gave more horizontal padding to the table cells so that the overall look and feel of the table is not crimped

## Related Issue

- Fixes https://github.com/owncloud/web/issues/8599

## Screenshots

### now:
<img width="1285" alt="Screenshot 2023-05-04 at 12 09 54" src="https://user-images.githubusercontent.com/3532843/236176997-65884194-54aa-4288-ae5b-016fd4372c70.png">

### before:
<img width="1283" alt="Screenshot 2023-05-04 at 12 10 55" src="https://user-images.githubusercontent.com/3532843/236177063-35d4a631-6d3a-4581-badf-d851eb8991b4.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-05-04 10:21 UTC, kulmann commented
Targeting this enhancement to `master` as it's clearly not a bugfix... ;-)

Also, I know that @lookacat you discussed this yesterday with @tbsbdr - heard about it too late and already had most of the changes ready... sorry that I took this issue away from you. 🤗 

@tbsbdr Please try out this PR. Especially if the click on sortable headers feels jumpy for you (table headers that are aligned to the right get pushed/pulled horizontally a little bit when the sort icon appears/disappears).

2023-05-04 11:28 UTC, tbsbdr requested changes
woha, nice!

1. click on sortable header: yes, feels a little bit jumpy; If you figure out a solution on how to avoid the jumpynes within reasonable efforts, I would be happy to avoid jumpynes. If a fix is too expensive, I would trade jumpynes for better readibility of the filename.
2. spacing between checkbox and resource icon is increased; can't judge anymore if this is an improvement as I'm too much used to the ui. Only thing that would speak against increasing it is so save space. up to you, this is just my 2 cents. 

![screenshot_000885](https://user-images.githubusercontent.com/26610733/236188641-413a48f7-fcac-438c-a9a4-dcdf23f25794.png)

2023-05-04 11:32 UTC, tbsbdr commented
especially makes a difference on small screens ❤️ best to test if one decreases resoultion to somewhat 1200 px width

2023-05-04 12:54 UTC, kulmann commented
@tbsbdr regarding jumpiness and paddings:

### jumpiness

We can avoid the jumpiness by keeping the width of the sorting icons even in the invisible state. The effect is that column headers that are aligned to the right have an offset from the right cell border (width of an oc-icon basically). Header text and body cell texts don't appear aligned anymore then. See screenshot (e.g. the `Modified` column). I would prefer to use the correct right alignment and accept the jumpiness.

<img width="1283" alt="Screenshot 2023-05-04 at 14 49 19" src="https://user-images.githubusercontent.com/3532843/236210118-7ad76937-7854-4864-8435-d1774c935ae6.png">

### paddings

With smaller horizontal paddings I had the feeling that all the shrinked columns feel very crowded. See screenshot, especially the table headers. But I'm fine with both the smaller (`xsmall`) and bigger (`small`) horizontal padding.

<img width="1285" alt="Screenshot 2023-05-04 at 14 48 47" src="https://user-images.githubusercontent.com/3532843/236210219-614f657b-633d-4e8b-9502-8220808222de.png">

2023-05-04 14:24 UTC, tbsbdr approved these changes

2023-05-04 14:25 UTC, tbsbdr commented
ah okay, thanks for the explanation. then all fine from my side 👍

2023-05-04 14:39 UTC, JammingBen commented
Hmm, maybe it's because I need to get used to it, but I'm not the biggest fan, especially on bigger screens. The right side looks totally crowded. The benefits are mainly for smaller screens, maybe we could limit it to those? @tbsbdr 

<img width="2337" alt="image" src="https://user-images.githubusercontent.com/50302941/236240967-410d581b-1d34-48dd-bb04-94906185f1fd.png">

2023-05-04 15:12 UTC, tbsbdr commented
> especially on bigger screens.

saw that as well and thought its mainly my viewing habit + my guess is, that most desktop users got =< 1920 screenwidth (ex https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide )

> The benefits are mainly for smaller screens, maybe we could limit it to those?

I'm not against improving if effort is reasonable - just a remark that we might move into the 20% zone of pareto, but ... 🤠

2023-05-05 06:41 UTC, JammingBen approved these changes
Fair enough. It would probably need quite some work and would make things overall more complicated :)

Pipeline stills fails though, not sure if related 🤔

2023-05-05 09:07 UTC, kulmann commented
> Fair enough. It would probably need quite some work and would make things overall more complicated :)
> 
> Pipeline stills fails though, not sure if related 🤔

The quick actions caused line wraps before on small resolutions and now don't because I "fixed" that (it was looking ugly). Now the three dots button scrolls out of the window horizontally on the XGA resolution. Will need to adjust how columns get hidden on smaller resolutions to fix this issue and resolve CI pipelines.

2023-05-05 19:58 UTC, merged

2023-05-05 20:03 UTC, gennaios commented
Nice. Thanks. I'm the filer of the issue of hard to see file names. I'll test this out sometime.

Thinking maybe in the future there could be more options or refinement. Some of the buttons like share or link, perhaps some other popular cloud services have made different decisions such as hiding them under the more menu, or presenting some different set of options? Overall my impression is that the UI could be cleaner and some of the options might necessarily be used all the time, e.g. create link, add share, etc. and we might not need to see them all the time in file lists..

2023-05-08 15:53 UTC, tbsbdr commented
@gennaios you can test it on:

- https://ocis.ocis-web.latest.owncloud.works/
- user: einstein
- password: relativity

2023-06-17 11:03 UTC, gennaios commented
@tbsbdr looks good. I think add people/shareand copy link icons could be removed? I think one isn't going to use it that often to need the icon on every row. It's not like one is going to use it all the time I think to warrant a separate button. As they're both in the context menu along with other options such as rename, add tags, etc., I think such is good enough as one isn't going to use them as often as browsing, searching, etc. Same as with a local desktop file manager, some options are not always used and like a file manager, I prefer a clean look.