WIP add location filter chip in search
owncloud/web pull request #9304
Opened 2023-06-28 08:33 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-07-03 07:57 UTC, lookacat commented
The glitch when selecting a different location scope while the search page is open is related to the backend not yet working, it just stops the update of the component for some reason. So probably fixed as soon as the backend works.

2023-07-11 14:52 UTC, JammingBen requested changes

2023-07-11 14:52 UTC, JammingBen commented on packages/design-system/src/components/OcSearchBarFilter/OcSearchBarFilter.vue
> +import 'vue-select/dist/vue-select.css'
Is this line needed?

2023-07-11 14:52 UTC, JammingBen commented on packages/design-system/src/components/OcSearchBarFilter/OcSearchBarFilter.vue
> +  }
Composition API please 🙂

2023-07-11 14:52 UTC, JammingBen commented on packages/web-app-files/src/components/Search/List.vue
> -        if (isChange && isLocationCommonActive(router, 'files-common-search')) {
Why did you remove all that code? It now fires a search on every route change, we should avoid that. Wouldn't it be sufficient to add a check if the `useScope` param has changed?

2023-07-11 14:52 UTC, JammingBen commented on packages/web-app-search/src/portals/SearchBar.vue
> +    ])
Would be nice to have a type somewhere so we can re-use it across the app.

2023-07-11 14:52 UTC, JammingBen commented on packages/web-pkg/src/composables/search/constants.ts
> +  static readonly queryName: string = 'location-filter'
This query name is not used anywhere, it it?

2023-07-14 13:08 UTC, JammingBen approved these changes
Nice work! 🥳

2023-07-14 13:09 UTC, merged