Keyboard shortcuts - Admin Settings
owncloud/web pull request #9498
Opened 2023-07-28 14:46 UTC by jacob-nv

## Description

Adding keyboard navigation to admin settings.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-08-01 07:43 UTC, JammingBen requested changes
Shift + click is a bit buggy for me. It only works the first time, but after de-selecting all resources and trying again, it won't.

Also, could you please make a single click on the row work like in the files app? So you don't necessarily need to click in the checkbox directly.

2023-08-01 07:43 UTC, JammingBen commented on packages/web-app-admin-settings/src/composables/scrollTo/useScrollTo.ts
> +  }
I think we can remove this, it's heavily bound to the files app (resource usage, store commit on `Files/SET_FILE_SELECTION`).

2023-08-02 06:01 UTC, JammingBen commented
Still facing a few issues:

* Clicking the "(de-)select all" checkbox on the top left side breaks shift+click selection
* Clicking a single row (mouse only, no shift or ctrl) should de-select previously selected rows (see files app)
* Select all users via the "(de-)select all" checkbox, then click on one of the selected users -> it will disappear from the list

2023-08-02 14:56 UTC, jacob-nv commented
> Still facing a few issues:
> 
> * Clicking the "(de-)select all" checkbox on the top left side breaks shift+click selection
> * Clicking a single row (mouse only, no shift or ctrl) should de-select previously selected rows (see files app)
> * Select all users via the "(de-)select all" checkbox, then click on one of the selected users -> it will disappear from the list

Everything fixed

2023-08-07 11:55 UTC, JammingBen reviewed
Works well! Just some nitpicks regarding terminology & types from my side.

Edit: Ah, unit tests are still failing: https://drone.owncloud.com/owncloud/web/37984/9/5

2023-08-07 11:55 UTC, JammingBen commented on packages/web-app-admin-settings/src/composables/keyboardActions/useKeyboardTableMouseActions.ts
> +  paginatedResources: Ref<Resource[]>,
`Resource` is only for files, we need `Group[] | User[] | Space[]` or maybe a generic interface? We probably only need the `id` prop, right?

2023-08-07 11:55 UTC, JammingBen commented on packages/web-app-admin-settings/src/composables/keyboardActions/useKeyboardTableMouseActions.ts
> +  let fileListClickedShiftEvent
`fileList...` -> `resourceList...` I propose.

2023-08-07 11:55 UTC, JammingBen commented on packages/web-app-admin-settings/src/composables/keyboardActions/useKeyboardTableMouseActions.ts
> +    )
File is not fitting here, I'd replace it with `resource` again.

2023-08-10 05:24 UTC, merged