Implement file locking information
owncloud/web pull request #9566
Opened 2023-08-10 08:47 UTC by lookacat

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-08-22 15:02 UTC, JanAckermann commented on packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
> +      const lockedUserResult = await clientService.graphAuthenticated.users.getUser(
I don't know if this is feasible, I don't think non-admin users can call this endpoint

2023-08-22 15:03 UTC, JanAckermann requested changes
LGTM, besides retrieving the lock user data

2023-08-23 07:28 UTC, lookacat commented on packages/design-system/src/components/OcTile/OcTile.vue
> +        return $gettext('This item is processing')
okay i see

2023-08-23 12:30 UTC, JanAckermann commented on packages/web-app-files/src/composables/actions/files/useFileActionsDelete.ts
> +        if (resources.length === 1 && resources[0].locked) {
unit test pls

2023-08-23 12:30 UTC, JanAckermann commented on packages/web-app-files/src/composables/actions/files/useFileActionsMove.ts
> +        if (resources.length === 1 && resources[0].locked) {
unit test pls

2023-08-23 12:30 UTC, JanAckermann commented on packages/web-app-files/src/composables/actions/files/useFileActionsRename.ts
> +        if (resources.length === 1 && resources[0].locked) {
unit test pls

2023-08-23 12:32 UTC, JanAckermann requested changes

2023-08-23 12:32 UTC, JanAckermann commented on packages/design-system/src/components/OcResource/OcResource.vue
> -
why remove this ?

2023-08-23 13:54 UTC, JanAckermann approved these changes

2023-08-24 07:43 UTC, merged