Add tests for basic password text input functionallity
owncloud/web pull request #9686
Opened 2023-09-11 13:19 UTC by JanAckermann

## Description

## Related Issue

- Fixes <issue_link>

## Motivation and Context

## How Has This Been Tested?

- test environment:
- test case 1:
- test case 2:
- ...

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [ ] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link> 

## Open tasks:

- [ ] ...

2023-09-11 13:38 UTC, lookacat commented on packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
> +      it('should copy password to password if clicked', async () => {
find the name of the test confusing, maybe 'should copy password to clipboard if clicked'

2023-09-11 13:40 UTC, lookacat commented on packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
> +      it('should should show password plaintext/veiled if clicked', async () => {
should should :D

2023-09-11 13:40 UTC, lookacat requested changes
two naming issues rest LGTM 👍🏼

2023-09-11 13:42 UTC, lookacat approved these changes

2023-09-12 07:51 UTC, JammingBen approved these changes

2023-09-12 08:16 UTC, merged