[tests-only][full-ci] added e2e test for adding banned password for public link
owncloud/web pull request #9798
Opened 2023-10-12 11:36 UTC by PrajwolAmatya

## Description
This PR adds the test for adding the banned password for public link. 
Used the existing password in banned-paswword-list like: `password` and `12345678`

## Related Issue

- https://github.com/owncloud/web/issues/9795

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Technical debt
- [x] Tests

## Checklist:

- [ ] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
- [ ] Documentation ticket raised: <link>

2023-10-13 11:17 UTC, saw-jan commented on .drone.star
> +        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "/srv/config/drone/password-policy-banned-passwords.txt",
or simply
```suggestion
        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "/srv/config/drone/banned-passwords.txt",
```

2023-10-13 11:18 UTC, saw-jan commented on tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
> +    """
```suggestion
      """
      Unfortunately, your password is commonly used. please pick a harder-to-guess password for your safety
      """
```

2023-10-13 11:18 UTC, saw-jan commented on tests/e2e/cucumber/features/smoke/spaces/publicLink.feature
> +  Scenario Outline: add banned password for public link
better to add steps as journey
```suggestion
  Scenario: add banned password for public link
```

2023-10-13 11:21 UTC, saw-jan commented on tests/e2e/cucumber/steps/ui/links.ts
> +    await linkObject.addBannedPassword({ resource, linkName, newPassword })
```suggestion
    await linkObject.setPassword({ resource, linkName, newPassword })
```

2023-10-13 11:21 UTC, saw-jan commented on tests/e2e/support/objects/app-files/link/actions.ts
> +
```suggestion
```

2023-10-13 11:21 UTC, saw-jan commented on tests/e2e/support/objects/app-files/link/actions.ts
> +const setPassword = async (args: addPasswordArgs): Promise<void> => {
```suggestion
const fillPassword = async (args: addPasswordArgs): Promise<void> => {
```

2023-10-16 06:03 UTC, saw-jan requested changes
this should work without having to copy file

2023-10-16 06:03 UTC, saw-jan commented on .drone.star
> +        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "/srv/config/drone/banned-passwords.txt",
```suggestion
        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "%s/tests/drone/password-policy-banned-passwords.txt" % dir["web"],
```

2023-10-16 06:03 UTC, saw-jan commented on .drone.star
> +                "cp %s/tests/drone/password-policy-banned-passwords.txt /srv/config/drone/banned-passwords.txt" % dir["web"],
```suggestion
```

2023-10-16 06:05 UTC, saw-jan commented on tests/e2e/support/objects/app-files/link/index.ts
> +  async setPassword(args: Omit<po.addPasswordArgs, 'page'>): Promise<void> {
```suggestion
  async fillPassword(args: Omit<po.addPasswordArgs, 'page'>): Promise<void> {
```

2023-10-16 06:15 UTC, saw-jan commented on .drone.star
> +        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "%s/tests/drone/password-policy-banned-passwords.txt" % dir["web"],
```suggestion
        "FRONTEND_PASSWORD_POLICY_BANNED_PASSWORDS_LIST": "%s/tests/drone/banned-passwords.txt" % dir["web"],
```

2023-10-16 06:22 UTC, saw-jan approved these changes
LGTM :+1:

2023-10-16 06:33 UTC, SagarGi commented on tests/e2e/cucumber/steps/ui/links.ts
> +    expect(errorMessage).toBe(actualErrorMessage)
```suggestion
    expect(actualErrorMessage).toBe(errorMessage)
```

2023-10-16 06:34 UTC, SagarGi approved these changes
Other LGTM :+1:

2023-10-16 07:02 UTC, ScharfViktor approved these changes

2023-10-16 07:21 UTC, merged